import type { paths } from "./generated";

export type Project = { id: string; groupId: string; name: string; role: "MANAGER" | "MEMBER" | "VIEWER" };
export type Schedule = { id: string; projectId: string; title: string; status: string; rowVersion: number; businessRevision: number; startsAt: string; endsAt: string; description?: string | null; createdBy: string; participants: Array<{ memberUserId?: string | null; externalEmail?: string | null; acknowledged: boolean }>; changes: Array<{ businessRevision: number; type: string; changedBy: string; createdAt: string }> };
export type Problem = { code?: string; traceId?: string; fieldErrors?: Array<{ field: string; message: string }> };
export type Configuration = paths["/api/v1/system/configuration"]["get"]["responses"][200]["content"]["application/json"];

export class ApiError extends Error { constructor(readonly status: number, readonly problem: Problem) { super(problem.code ?? `HTTP_${status}`); } }
async function parse<T>(response: Response): Promise<T> { if (!response.ok) { let problem: Problem = {}; try { problem = await response.json() as Problem; } catch { /* no problem payload */ } throw new ApiError(response.status, problem); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; }
export async function read<T>(path: string): Promise<T> { return parse<T>(await fetch(path, { credentials: "include" })); }
async function token() { return read<{ headerName: string; token: string }>("/api/v1/csrf"); }
export async function mutate<T>(path: string, method = "POST", body?: unknown): Promise<T> { const current = await token(); return parse<T>(await fetch(path, { method, credentials: "include", headers: { "content-type": "application/json", [current.headerName]: current.token }, body: body === undefined ? undefined : JSON.stringify(body) })); }
export const api = {
  configuration: () => read<Configuration>("/api/v1/system/configuration"), me: () => read<{ id: string; authorities: string[] }>("/api/v1/me"),
  projects: () => read<Project[]>("/api/v1/projects?page=0&limit=100"), dashboard: (id: string) => read<{ projectId: string; memberCount: number; scheduleCount: number; pendingAcknowledgementCount: number; calendarRiskCount: number; upcomingSchedules: Schedule[]; actionQueue: Schedule[] }>(`/api/v1/projects/${id}/dashboard`),
  schedules: (id: string, from?: string, to?: string) => read<Schedule[]>(`/api/v1/projects/${id}/schedules?page=0&limit=100${from ? `&from=${encodeURIComponent(from)}` : ""}${to ? `&to=${encodeURIComponent(to)}` : ""}`), detail: (p: string, id: string) => read<Schedule>(`/api/v1/projects/${p}/schedules/${id}?historyLimit=100`),
  save: (p: string, id: string | undefined, body: unknown) => mutate<Schedule>(id ? `/api/v1/projects/${p}/schedules/${id}` : `/api/v1/projects/${p}/schedules`, id ? "PATCH" : "POST", body), acknowledge: (p: string, id: string, revision: number) => mutate<Schedule>(`/api/v1/projects/${p}/schedules/${id}/acknowledge`, "POST", { expectedBusinessRevision: revision }),
  invite: (groupId: string, body: unknown) => mutate(`/api/v1/groups/${groupId}/invitations`, "POST", body), invitation: (tokenValue: string) => read<{ id: string; projectId: string; email: string; token: string; status: string; expiresAt: string }>(`/api/v1/invitations/${tokenValue}`), resolve: (tokenValue: string, action: "accept" | "reject") => mutate(`/api/v1/invitations/${tokenValue}/${action}`),
  notifications: () => read<Array<{ id: string; type: string; link?: string | null; readAt?: string | null; createdAt: string }>>("/api/v1/notifications?page=0&limit=100"), readNotification: (id: string) => mutate(`/api/v1/notifications/${id}/read`), members: (p: string) => read<Array<{ userId: string; role: string }>>(`/api/v1/projects/${p}/members?page=0&limit=100`), role: (p: string, userId: string, role: string) => mutate(`/api/v1/projects/${p}/members/${userId}`, "PATCH", { role }),
  calendar: () => read<{ status: string; configurationRequired: boolean }>("/api/v1/calendar/connection"), reconnect: () => mutate<{ status: string; configurationRequired: boolean }>("/api/v1/calendar/reconnect"), projection: (p: string, s: string) => read<{ status: string; retryClassification?: string | null; businessRevision: number }>(`/api/v1/projects/${p}/schedules/${s}/calendar`), retryProjection: (p: string, s: string) => mutate(`/api/v1/projects/${p}/schedules/${s}/calendar/retry`)
};
