package com.aierp.schedule;

import com.aierp.platform.events.EventJournal; import com.aierp.platform.web.*; import com.aierp.project.api.ProjectAccess;
import com.aierp.schedule.api.*; import com.aierp.schedule.api.ScheduleWorkspaceController.*;
import tools.jackson.databind.*; import tools.jackson.databind.json.JsonMapper; import java.math.*; import java.sql.*; import java.time.*; import java.util.*; import java.util.stream.*;
import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.orm.ObjectOptimisticLockingFailureException; import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*;

@Service
public class ScheduleWorkspaceService {
    private static final Set<String> COLORS=Set.of("gray","blue","green","amber","red","purple","pink","teal");
    private final SchedulePropertyRepository properties; private final SchedulePropertyOptionRepository options; private final SchedulePropertyValueRepository values;
    private final ScheduleSavedViewRepository views; private final ScheduleDashboardViewRepository dashboards; private final ScheduleRepository schedules;
    private final ProjectAccess access; private final ScheduleService scheduleService; private final JdbcTemplate jdbc; private final JsonMapper mapper; private final EventJournal events;
    public ScheduleWorkspaceService(SchedulePropertyRepository properties,SchedulePropertyOptionRepository options,SchedulePropertyValueRepository values,
        ScheduleSavedViewRepository views,ScheduleDashboardViewRepository dashboards,ScheduleRepository schedules,ProjectAccess access,ScheduleService scheduleService,
        JdbcTemplate jdbc,JsonMapper mapper,EventJournal events) { this.properties=properties;this.options=options;this.values=values;this.views=views;this.dashboards=dashboards;this.schedules=schedules;this.access=access;this.scheduleService=scheduleService;this.jdbc=jdbc;this.mapper=mapper;this.events=events; }

    @Transactional(readOnly=true) public Workspace workspace(UUID project,UUID user) {
        access.role(project,user); var ps=properties.findByProjectIdOrderByPositionAscIdAsc(project); var result=new ArrayList<Property>(); ps.forEach(p->result.add(property(p)));
        var resultViews=new ArrayList<View>(); resultViews.add(builtin("builtin-calendar",ViewType.CALENDAR)); resultViews.add(builtin("builtin-cards",ViewType.CARDS)); resultViews.add(builtin("builtin-list",ViewType.LIST));
        views.findByProjectId(project).stream().filter(v->!v.archived && (v.scope==ScheduleSavedViewEntity.Scope.SHARED || user.equals(v.ownerId))).sorted(Comparator.comparing(v->v.name)).forEach(v->resultViews.add(view(v)));
        var d=dashboards.findByProjectId(project); return new Workspace(result,resultViews,d.isEmpty()?null:(d.get().dashboardViewId==null?d.get().builtinView:d.get().dashboardViewId.toString()),d.map(x->x.rowVersion).orElse(0L));
    }
    @Transactional public Property createProperty(UUID project,PropertyWrite w,UUID user) { access.lockProject(project); access.requireManager(project,user); validateName(w.name()); if(w.type()==null) throw new ValidationFailure("type","Property type is required"); if(properties.countByProjectId(project)>=50) throw new ValidationFailure("properties","At most 50 properties");
        var p=new SchedulePropertyEntity();p.id=UUID.randomUUID();p.projectId=project;p.name=w.name().trim();p.propertyType=w.type();p.position=w.position()==null?nextPosition(project):w.position();p.archived=Boolean.TRUE.equals(w.archived()); validatePosition(p.position);properties.saveAndFlush(p);replaceOptions(p,w.options(),true);audit(project,user,"WORKSPACE_PROPERTY_CREATED",p.id);return property(p); }
    @Transactional public Property updateProperty(UUID project,UUID id,PropertyWrite w,UUID user) { access.lockProject(project); access.requireManager(project,user); var p=properties.findByIdAndProjectId(id,project).orElseThrow(NoSuchElementException::new); if(w.rowVersion()==null) throw new ValidationFailure("rowVersion","rowVersion is required"); if(p.rowVersion!=w.rowVersion()) throw stale(id); boolean scalarChanged=false; if(w.name()!=null){validateName(w.name());var name=w.name().trim();scalarChanged|=!Objects.equals(p.name,name);p.name=name;} if(w.type()!=null&&w.type()!=p.propertyType) throw new ValidationFailure("type","Property type is immutable"); if(w.position()!=null){validatePosition(w.position());scalarChanged|=p.position!=w.position();p.position=w.position();} if(w.archived()!=null){scalarChanged|=p.archived!=w.archived();p.archived=w.archived();} boolean optionsChanged=replaceOptions(p,w.options(),false); if(scalarChanged) properties.saveAndFlush(p); else if(optionsChanged){if(properties.advanceVersion(id,w.rowVersion())!=1)throw stale(id);p=properties.findByIdAndProjectId(id,project).orElseThrow();} audit(project,user,"WORKSPACE_PROPERTY_UPDATED",id);return property(p); }

    @Transactional public View createView(UUID project,ViewWrite w,UUID user) { access.lockProject(project); checkViewScope(w.scope(),project,user); validateView(w.config(),project); var scope=w.scope()==Scope.SHARED?ScheduleSavedViewEntity.Scope.SHARED:ScheduleSavedViewEntity.Scope.PERSONAL; long existing=scope==ScheduleSavedViewEntity.Scope.SHARED?views.countByProjectIdAndScope(project,scope):views.countByProjectIdAndScopeAndOwnerId(project,scope,user); if(existing>=100) throw new ValidationFailure("views","View limit reached"); var v=new ScheduleSavedViewEntity();v.id=UUID.randomUUID();v.projectId=project;v.name=name(w.name());v.scope=scope;v.ownerId=user;v.config=mapper.convertValue(w.config(),Map.class);v.archived=Boolean.TRUE.equals(w.archived());views.saveAndFlush(v);audit(project,user,"WORKSPACE_VIEW_CREATED",v.id);return view(v); }
    @Transactional public View updateView(UUID project,UUID id,ViewWrite w,UUID user) { access.lockProject(project); access.role(project,user); var v=views.lockByIdAndProjectId(id,project).orElseThrow(NoSuchElementException::new); if(v.scope==ScheduleSavedViewEntity.Scope.SHARED) access.requireManager(project,user); else { if(!user.equals(v.ownerId)) throw new AccessDeniedException("VIEW_OWNER_REQUIRED"); access.requireWriter(project,user,null); } if(v.rowVersion!=(w.rowVersion()==null?-1:w.rowVersion())) throw stale(id); if(w.scope()!=null&&w.scope()!=Scope.valueOf(v.scope.name())) throw new ValidationFailure("scope","View scope is immutable"); if(w.name()!=null)v.name=name(w.name()); if(w.config()!=null){validateView(w.config(),project);v.config=mapper.convertValue(w.config(),Map.class);} if(w.archived()!=null)v.archived=w.archived();views.saveAndFlush(v);audit(project,user,"WORKSPACE_VIEW_UPDATED",id);return view(v); }
    @Transactional public Dashboard dashboard(UUID project,DashboardWrite w,UUID user) {
        access.lockProject(project);access.requireManager(project,user);if(w.rowVersion()==null||w.rowVersion()<0)throw new ValidationFailure("rowVersion","A nonnegative rowVersion is required");var existing=dashboards.findByProjectId(project);long current=existing.map(d->d.rowVersion).orElse(0L);if(current!=w.rowVersion())throw stale(project);
        UUID selected=null;String builtin="builtin-cards";if(w.viewId()!=null){if(Set.of("builtin-calendar","builtin-cards","builtin-list").contains(w.viewId()))builtin=w.viewId();else{try{selected=UUID.fromString(w.viewId());}catch(IllegalArgumentException e){throw new ValidationFailure("viewId","Unknown view");}var v=views.findByIdAndProjectId(selected,project).orElseThrow(()->new ValidationFailure("viewId","Unknown view"));if(v.archived||v.scope!=ScheduleSavedViewEntity.Scope.SHARED)throw new ValidationFailure("viewId","Only active shared views may be selected");}}
        ScheduleDashboardViewEntity d;if(existing.isEmpty()){if(dashboards.insertInitial(project,selected,builtin)!=1)throw stale(project);d=dashboards.findByProjectId(project).orElseThrow();}else{d=existing.get();d.dashboardViewId=selected;d.builtinView=builtin;d=dashboards.saveAndFlush(d);}audit(project,user,"WORKSPACE_DASHBOARD_VIEW_UPDATED",project);return new Dashboard(w.viewId(),d.rowVersion);
    }

    @Transactional(isolation=Isolation.REPEATABLE_READ,readOnly=true) public QueryResult query(UUID project,Query q,UUID user) { access.role(project,user);if(q==null||q.config()==null)throw new ValidationFailure("config","Query config is required");validateView(q.config(),project);int page=q.page()==null?0:q.page(),size=q.size()==null?50:q.size();if(page<0||page>100000||size<1||size>100)throw new ValidationFailure("page","Page or size out of range");if(q.from()!=null&&q.to()!=null&&!q.from().isBefore(q.to()))throw new ValidationFailure("to","Must be after from");var props=properties.findByProjectIdOrderByPositionAscIdAsc(project).stream().collect(Collectors.toMap(p->p.id,p->p));var sql=new StringBuilder("select s.id from schedule.project_schedule s where s.project_id=?");var args=new ArrayList<Object>();args.add(project);if(q.from()!=null){sql.append(" and s.ends_at>?");args.add(Timestamp.from(q.from()));}if(q.to()!=null){sql.append(" and s.starts_at<?");args.add(Timestamp.from(q.to()));}appendFilters(sql,args,q.config().filters(),props);long total=count(sql,args);appendSort(sql,args,q.config().sorts(),props);sql.append(" limit ? offset ?");args.add(size);args.add((long)page*size);var ids=jdbc.queryForList(sql.toString(),UUID.class,args.toArray());var entities=schedules.findByProjectIdAndIdIn(project,ids);var byId=scheduleService.summaries(entities).stream().collect(Collectors.toMap(ScheduleController.ScheduleResponse::id,x->x));var raw=values.findByProjectIdAndScheduleIdIn(project,ids).stream().collect(Collectors.groupingBy(v->v.scheduleId));var records=ids.stream().map(id->new ScheduleWorkspaceController.Record(byId.get(id),raw.getOrDefault(id,List.of()).stream().collect(Collectors.toMap(v->v.propertyId,this::jsonValue)))).toList();var groups=groups(project,q,props);return new QueryResult(records,total,(long)(page+1)*size<total,page,size,groups,Instant.now()); }

    @Transactional(readOnly=true) public ScheduleWorkspaceController.Record record(UUID project,UUID id,UUID user) { var schedule=scheduleService.detail(project,id,user);var map=values.findByProjectIdAndScheduleId(project,id).stream().collect(Collectors.toMap(v->v.propertyId,this::jsonValue));return new ScheduleWorkspaceController.Record(schedule,map); }
    @Transactional public ScheduleWorkspaceController.Record createRecord(UUID project,RecordWrite w,UUID user) { access.lockProject(project);if(w.schedule()==null)throw new ValidationFailure("schedule","Schedule is required");var s=scheduleService.create(project,w.schedule(),user);var entity=schedules.lockByIdAndProjectId(s.id(),project).orElseThrow();applyValues(project,entity,user,w.values(),false);return record(project,s.id(),user); }
    @Transactional public ScheduleWorkspaceController.Record updateRecord(UUID project,UUID id,RecordWrite w,UUID user) { access.lockProject(project);if(w.schedule()==null)throw new ValidationFailure("schedule","Schedule is required");var s=scheduleService.update(project,id,w.schedule(),user);var entity=schedules.lockByIdAndProjectId(id,project).orElseThrow();boolean changed=applyValues(project,entity,user,w.values(),false);if(changed){entity.updatedAt=Instant.now();schedules.saveAndFlush(entity);audit(project,user,"WORKSPACE_CUSTOM_VALUE_UPDATED",id);}return record(project,id,user); }
    @Transactional public ScheduleWorkspaceController.Record updateValues(UUID project,UUID id,ValuesWrite w,UUID user) { access.lockProject(project);access.requireWriter(project,user,null);var s=schedules.lockByIdAndProjectId(id,project).orElseThrow(NoSuchElementException::new);access.requireWriter(project,user,s.createdBy);if(w.rowVersion()==null)throw new ValidationFailure("rowVersion","rowVersion is required");if(s.rowVersion!=w.rowVersion())throw stale(id);if(s.status==ScheduleEntity.Status.CANCELLED)throw new IllegalStateException("SCHEDULE_CANCELLED");if(w.values()==null||w.values().isEmpty())return record(project,id,user);boolean changed=applyValues(project,s,user,w.values(),true);if(changed){s.updatedAt=Instant.now();schedules.saveAndFlush(s);audit(project,user,"WORKSPACE_CUSTOM_VALUE_UPDATED",id);}return record(project,id,user); }

    private boolean applyValues(UUID project,ScheduleEntity s,UUID user,Map<UUID,JsonNode> incoming,boolean rejectEmpty) { if(incoming==null)return false;boolean changed=false;var ps=properties.findByProjectIdOrderByPositionAscIdAsc(project).stream().collect(Collectors.toMap(p->p.id,p->p));for(var e:incoming.entrySet()){var p=ps.get(e.getKey());if(p==null)throw new ValidationFailure("values","Unknown property");var existing=values.findByProjectIdAndScheduleIdAndPropertyId(project,s.id,p.id).orElse(null);if(e.getValue()==null||e.getValue().isNull()){if(existing!=null){values.delete(existing);changed=true;}continue;}if(existing!=null&&sameValue(p,existing,e.getValue()))continue;if(p.archived)throw new ValidationFailure("values","Archived property cannot receive values");var parsed=parseValue(p,e.getValue());if(existing==null){existing=new SchedulePropertyValueEntity();existing.id=UUID.randomUUID();existing.projectId=project;existing.scheduleId=s.id;existing.propertyId=p.id;}existing.valueType=p.propertyType;existing.textValue=null;existing.numberValue=null;existing.checkboxValue=null;existing.dateValue=null;existing.optionId=null;switch(p.propertyType){case TEXT->existing.textValue=parsed.text;case NUMBER->existing.numberValue=parsed.number;case CHECKBOX->existing.checkboxValue=parsed.bool;case DATE->existing.dateValue=parsed.date;case SINGLE_SELECT->existing.optionId=parsed.option;}values.save(existing);changed=true;}values.flush();return changed; }
    private boolean sameValue(SchedulePropertyEntity p,SchedulePropertyValueEntity existing,JsonNode incoming){if(p.propertyType==SchedulePropertyEntity.PropertyType.SINGLE_SELECT){try{if(!incoming.isTextual())throw new IllegalArgumentException();return Objects.equals(existing.optionId,UUID.fromString(incoming.textValue()));}catch(IllegalArgumentException e){throw new ValidationFailure("values","Value type is invalid");}}var parsed=parseValue(p,incoming);return switch(p.propertyType){case TEXT->Objects.equals(existing.textValue,parsed.text);case NUMBER->existing.numberValue!=null&&existing.numberValue.compareTo(parsed.number)==0;case CHECKBOX->Objects.equals(existing.checkboxValue,parsed.bool);case DATE->Objects.equals(existing.dateValue,parsed.date);case SINGLE_SELECT->false;};}
    private Parsed parseValue(SchedulePropertyEntity p,JsonNode n){try{switch(p.propertyType){case TEXT-> {if(!n.isTextual()||n.textValue().length()>2000)throw new ValidationFailure("values","Text value must be <=2000 characters");return new Parsed(n.textValue(),null,null,null,null);}case NUMBER-> {if(!n.isNumber()||!Double.isFinite(n.doubleValue()))throw new ValidationFailure("values","Finite number required");return new Parsed(null,new BigDecimal(n.asText()),null,null,null);}case CHECKBOX-> {if(!n.isBoolean())throw new ValidationFailure("values","Boolean required");return new Parsed(null,null,n.booleanValue(),null,null);}case DATE-> {if(!n.isTextual()||!n.textValue().matches("\\d{4}-\\d{2}-\\d{2}"))throw new ValidationFailure("values","ISO date required");return new Parsed(null,null,null,LocalDate.parse(n.textValue()),null);}case SINGLE_SELECT-> {if(!n.isTextual())throw new ValidationFailure("values","Option ID required");var id=UUID.fromString(n.textValue());var o=options.findByIdAndPropertyId(id,p.id).orElseThrow(()->new ValidationFailure("values","Unknown option"));if(o.archived)throw new ValidationFailure("values","Archived option cannot receive values");return new Parsed(null,null,null,null,id);}}}catch(DateTimeException|IllegalArgumentException ex){if(ex instanceof ValidationFailure vf)throw vf;throw new ValidationFailure("values","Value type is invalid");}throw new ValidationFailure("values","Value type is invalid");}
    private record Parsed(String text,BigDecimal number,Boolean bool,LocalDate date,UUID option){}

    private void appendFilters(StringBuilder sql,List<Object> a,List<Filter> fs,Map<UUID,SchedulePropertyEntity> ps){for(Filter f:fs==null?List.<Filter>of():fs){String field=f.field();String op=f.operator().name();if(field.startsWith("property:")){UUID id=UUID.fromString(field.substring(9));var p=ps.get(id);if(p==null)throw new ValidationFailure("filters","Unknown property");String expr=propertyExpr("v",p);if(op.equals("IS_EMPTY")){sql.append(" and not exists (select 1 from schedule.schedule_property_value v where v.schedule_id=s.id and v.property_id=? and ").append(expr).append(" is not null)");a.add(id);}else if(op.equals("IS_NOT_EMPTY")){sql.append(" and exists (select 1 from schedule.schedule_property_value v where v.schedule_id=s.id and v.property_id=? and ").append(expr).append(" is not null)");a.add(id);}else if(op.equals("NE")){sql.append(" and (not exists (select 1 from schedule.schedule_property_value v where v.schedule_id=s.id and v.property_id=?) or exists (select 1 from schedule.schedule_property_value v where v.schedule_id=s.id and v.property_id=? and ").append(expr).append(" <> ?))");a.add(id);a.add(id);a.add(operand(f.value(),p.propertyType));}else{a.add(id);sql.append(" and exists (select 1 from schedule.schedule_property_value v where v.schedule_id=s.id and v.property_id=? and ").append(predicate(expr,op,f.value(),a,p.propertyType)).append(")");}}else{String expr=fixedExpr(field);sql.append(" and ").append(predicate(expr,op,f.value(),a,null));}}}
    private String predicate(String expr,String op,JsonNode n,List<Object>a){return predicate(expr,op,n,a,null);}
    private String predicate(String expr,String op,JsonNode n,List<Object>a,SchedulePropertyEntity.PropertyType type){return switch(op){case "IS_EMPTY"->"("+expr+" is null)";case "IS_NOT_EMPTY"->"("+expr+" is not null)";case "EQ","NE","CONTAINS","GT","GTE","LT","LTE"->{if(n==null||n.isNull())throw new ValidationFailure("value","Filter operand required");String sqlop=switch(op){case "EQ"->"=";case "NE"->"<>";case "CONTAINS"->"like";case "GT"->">";case "GTE"->">=";case "LT"->"<";default->"<=";};String placeholder="?";if(type==null&&("s.starts_at".equals(expr)||"s.ends_at".equals(expr))){if(!n.isTextual())throw new ValidationFailure("value","Timestamp required");a.add(Timestamp.from(Instant.parse(n.textValue())));}else if(type==null&&"s.created_by".equals(expr)){if(!n.isTextual())throw new ValidationFailure("value","UUID required");a.add(UUID.fromString(n.textValue()));}else if(op.equals("CONTAINS")){if(!n.isTextual())throw new ValidationFailure("value","Text operand required");a.add("%"+escapeLike(n.textValue())+"%");placeholder="? escape '!'";}else a.add(operand(n,type));yield "("+expr+" "+sqlop+" "+placeholder+" )";}default->throw new ValidationFailure("operator","Unsupported operator");};}
    private Object operand(JsonNode n,SchedulePropertyEntity.PropertyType type){try{if(type==SchedulePropertyEntity.PropertyType.DATE){if(!n.isTextual()||!n.textValue().matches("\\d{4}-\\d{2}-\\d{2}"))throw new IllegalArgumentException();return java.sql.Date.valueOf(LocalDate.parse(n.textValue()));}if(type==SchedulePropertyEntity.PropertyType.CHECKBOX){if(!n.isBoolean())throw new IllegalArgumentException();return n.booleanValue();}if(type==SchedulePropertyEntity.PropertyType.SINGLE_SELECT){if(!n.isTextual())throw new IllegalArgumentException();return UUID.fromString(n.textValue());}if(type==SchedulePropertyEntity.PropertyType.NUMBER){if(!n.isNumber()||!Double.isFinite(n.doubleValue()))throw new IllegalArgumentException();return n.numberValue();}if(!n.isTextual())throw new IllegalArgumentException();return n.textValue();}catch(RuntimeException e){throw new ValidationFailure("value","Filter operand has the wrong type");}}
    private String escapeLike(String text){return text.replace("!","!!").replace("%","!%").replace("_","!_");}
    private String fixedExpr(String f){return switch(f){case "title"->"s.title";case "startsAt"->"s.starts_at";case "endsAt"->"s.ends_at";case "status"->"s.status";case "createdBy"->"s.created_by";default->throw new ValidationFailure("field","Unknown field");};}
    private String propertyExpr(String a,SchedulePropertyEntity p){return switch(p.propertyType){case TEXT->a+".text_value";case NUMBER->a+".number_value";case CHECKBOX->a+".checkbox_value";case DATE->a+".date_value";case SINGLE_SELECT->a+".option_id";};}
    private void appendSort(StringBuilder sql,List<Object>a,List<SortSpec> sorts,Map<UUID,SchedulePropertyEntity> ps){if(sorts==null||sorts.isEmpty()){sql.append(" order by s.starts_at asc nulls last,s.id asc");return;}sql.append(" order by ");var list=new ArrayList<String>();for(var s:sorts){String x;if(s.field().startsWith("property:")){var id=UUID.fromString(s.field().substring(9));var p=ps.get(id);if(p==null)throw new ValidationFailure("sorts","Unknown property");if(p.propertyType==SchedulePropertyEntity.PropertyType.SINGLE_SELECT)x="(select o.position from schedule.schedule_property_value v join schedule.schedule_property_option o on o.id=v.option_id where v.schedule_id=s.id and v.property_id=?)";else x="(select "+propertyExpr("v",p)+" from schedule.schedule_property_value v where v.schedule_id=s.id and v.property_id=?)";a.add(id);}else x=fixedExpr(s.field());list.add(x+" "+(s.direction()==Direction.DESC?"desc":"asc")+" nulls last");}sql.append(String.join(",",list)).append(",s.id asc");}
    private long count(StringBuilder sql,List<Object>a){return jdbc.queryForObject("select count(*) from ("+sql+") q",Long.class,a.toArray());}
    private List<Group> groups(UUID project,Query q,Map<UUID,SchedulePropertyEntity> ps){if(q.config().groupBy()==null)return List.of();var p=ps.get(q.config().groupBy());if(p==null||p.propertyType!=SchedulePropertyEntity.PropertyType.SINGLE_SELECT)throw new ValidationFailure("groupBy","Group must be a single select property");StringBuilder base=new StringBuilder("select g.id,coalesce(g.label,'Unassigned') label,g.color,count(*) from schedule.project_schedule s left join schedule.schedule_property_value v on v.schedule_id=s.id and v.property_id=? left join schedule.schedule_property_option g on g.id=v.option_id where s.project_id=?");var a=new ArrayList<Object>();a.add(q.config().groupBy());a.add(project);if(q.from()!=null){base.append(" and s.ends_at>?");a.add(Timestamp.from(q.from()));}if(q.to()!=null){base.append(" and s.starts_at<?");a.add(Timestamp.from(q.to()));}appendFilters(base,a,q.config().filters(),ps);base.append(" group by g.id,g.label,g.color order by g.label");var rows=jdbc.queryForList(base.toString(),a.toArray());return rows.stream().map(r->new Group((UUID)r.get("id"),(String)r.get("label"),(String)r.get("color"),((Number)r.get("count")).longValue())).toList();}

    private Property property(SchedulePropertyEntity p){return new Property(p.id,p.name,p.propertyType,p.position,p.archived,p.rowVersion,options.findByPropertyIdOrderByPositionAscIdAsc(p.id).stream().map(o->new Option(o.id,o.label,o.color,o.archived)).toList());}
    private View view(ScheduleSavedViewEntity v){return new View(v.id.toString(),v.name,v.scope==ScheduleSavedViewEntity.Scope.SHARED?Scope.SHARED:Scope.PERSONAL,v.ownerId,v.rowVersion,v.archived,mapper.convertValue(v.config,ViewConfig.class));}
    private View builtin(String id,ViewType t){return new View(id,id.replace("builtin-",""),Scope.BUILTIN,null,0,false,new ViewConfig(t,List.of(),List.of(new SortSpec("startsAt",Direction.ASC)),null,null,List.of("title","startsAt","endsAt","status")));}
    private boolean replaceOptions(SchedulePropertyEntity p,List<OptionWrite> os,boolean create){if(os==null)return false;if(p.propertyType!=SchedulePropertyEntity.PropertyType.SINGLE_SELECT)throw new ValidationFailure("options","Options require SINGLE_SELECT");if(os.size()>100)throw new ValidationFailure("options","At most 100 options");var existing=options.findByPropertyIdOrderByPositionAscIdAsc(p.id);if(!create&&os.stream().map(OptionWrite::id).filter(Objects::nonNull).collect(Collectors.toSet()).size()!=existing.size())throw new ValidationFailure("options","All current options are required");boolean changed=false;for(int i=0;i<os.size();i++){var w=os.get(i);var o=w.id()==null?new SchedulePropertyOptionEntity():options.findByIdAndPropertyId(w.id(),p.id).orElseThrow(()->new ValidationFailure("options","Unknown option"));if(o.id==null){o.id=UUID.randomUUID();changed=true;}o.propertyId=p.id;if(w.label()==null||w.label().isBlank()||w.label().length()>80)throw new ValidationFailure("options","Option label is invalid");if(!COLORS.contains(w.color()))throw new ValidationFailure("options","Option color is invalid");String label=w.label().trim();boolean archived=Boolean.TRUE.equals(w.archived());changed|=!Objects.equals(o.label,label)||!Objects.equals(o.color,w.color())||o.position!=i||o.archived!=archived;o.label=label;o.color=w.color();o.position=i;o.archived=archived;options.save(o);}options.flush();return changed;}
    private void validateView(ViewConfig c,UUID project){if(c==null||c.type()==null)throw new ValidationFailure("type","View type is required");if(c.filters()!=null&&c.filters().size()>10)throw new ValidationFailure("filters","At most 10 filters");if(c.sorts()!=null&&c.sorts().size()>3)throw new ValidationFailure("sorts","At most 3 sorts");if(c.visibleFields()!=null&&new HashSet<>(c.visibleFields()).size()>30)throw new ValidationFailure("visibleFields","At most 30 fields");var ps=properties.findByProjectIdOrderByPositionAscIdAsc(project).stream().collect(Collectors.toMap(p->p.id,p->p));Stream.concat(Stream.ofNullable(c.groupBy()),Stream.ofNullable(c.legendBy())).filter(Objects::nonNull).forEach(id->{var p=ps.get(id);if(p==null)throw new ValidationFailure("config","Unknown property");if(p.propertyType!=SchedulePropertyEntity.PropertyType.SINGLE_SELECT)throw new ValidationFailure("config","Group and legend require SINGLE_SELECT");});if(c.visibleFields()!=null)c.visibleFields().forEach(f->fieldProperty(f,ps));if(c.sorts()!=null)c.sorts().forEach(s->{fieldProperty(s.field(),ps);if(s.direction()==null)throw new ValidationFailure("sorts","Direction is required");});if(c.filters()!=null)c.filters().forEach(f->validateFilter(f,fieldProperty(f.field(),ps)));}
    private void validateFilter(Filter f,SchedulePropertyEntity p){if(f.operator()==null)throw new ValidationFailure("operator","Operator is required");var o=f.operator();if(o==Operator.IS_EMPTY||o==Operator.IS_NOT_EMPTY){if(f.value()!=null&&!f.value().isNull())throw new ValidationFailure("value","Empty operators take no operand");return;}if(p!=null){if(!allowed(p.propertyType,o))throw new ValidationFailure("operator","Operator is not valid for property type");operand(f.value(),p.propertyType);if(p.propertyType==SchedulePropertyEntity.PropertyType.SINGLE_SELECT){UUID id=(UUID)operand(f.value(),p.propertyType);options.findByIdAndPropertyId(id,p.id).orElseThrow(()->new ValidationFailure("value","Unknown option"));}return;}Set<Operator> allowed=switch(f.field()){case "title"->Set.of(Operator.EQ,Operator.NE,Operator.CONTAINS);case "startsAt","endsAt"->Set.of(Operator.EQ,Operator.NE,Operator.GT,Operator.GTE,Operator.LT,Operator.LTE);case "status","createdBy"->Set.of(Operator.EQ,Operator.NE);default->Set.of();};if(!allowed.contains(o))throw new ValidationFailure("operator","Operator is not valid for field");if(f.value()==null||f.value().isNull())throw new ValidationFailure("value","Filter operand required");try{if("startsAt".equals(f.field())||"endsAt".equals(f.field())){if(!f.value().isTextual())throw new IllegalArgumentException();Instant.parse(f.value().textValue());}else if("createdBy".equals(f.field())){if(!f.value().isTextual())throw new IllegalArgumentException();UUID.fromString(f.value().textValue());}else if("status".equals(f.field())){if(!f.value().isTextual())throw new IllegalArgumentException();ScheduleEntity.Status.valueOf(f.value().textValue());}else if(!f.value().isTextual())throw new IllegalArgumentException();}catch(RuntimeException ex){throw new ValidationFailure("value","Filter operand has the wrong type");}}
    private SchedulePropertyEntity fieldProperty(String field,Map<UUID,SchedulePropertyEntity> ps){if(field==null)throw new ValidationFailure("field","Field is required");if(field.startsWith("property:")){try{var p=ps.get(UUID.fromString(field.substring(9)));if(p==null)throw new ValidationFailure("field","Unknown property");return p;}catch(IllegalArgumentException e){throw new ValidationFailure("field","Unknown property");}}if(!Set.of("title","startsAt","endsAt","status","createdBy").contains(field))throw new ValidationFailure("field","Unknown field");return null;}
    private boolean allowed(SchedulePropertyEntity.PropertyType t,Operator o){return switch(t){case TEXT->Set.of(Operator.EQ,Operator.NE,Operator.CONTAINS,Operator.IS_EMPTY,Operator.IS_NOT_EMPTY).contains(o);case NUMBER,DATE->Set.of(Operator.EQ,Operator.NE,Operator.GT,Operator.GTE,Operator.LT,Operator.LTE,Operator.IS_EMPTY,Operator.IS_NOT_EMPTY).contains(o);case CHECKBOX,SINGLE_SELECT->Set.of(Operator.EQ,Operator.NE,Operator.IS_EMPTY,Operator.IS_NOT_EMPTY).contains(o);};}
    private void checkViewScope(Scope s,UUID project,UUID user){if(s==null||s==Scope.BUILTIN)throw new ValidationFailure("scope","Saved scope is required");if(s==Scope.SHARED)access.requireManager(project,user);else access.requireWriter(project,user,null);}
    private void validateName(String n){if(n==null||n.isBlank()||n.trim().length()>80)throw new ValidationFailure("name","Name must contain 1 to 80 characters");}
    private String name(String n){validateName(n);return n.trim();}private int nextPosition(UUID p){return properties.findByProjectIdOrderByPositionAscIdAsc(p).stream().mapToInt(x->x.position).max().orElse(-1)+1;}private void validatePosition(int p){if(p<0||p>10000)throw new ValidationFailure("position","Position is out of range");}
    private ObjectOptimisticLockingFailureException stale(UUID id){return new ObjectOptimisticLockingFailureException(ScheduleWorkspaceService.class,id);}
    private JsonNode jsonValue(SchedulePropertyValueEntity v){return switch(v.valueType){case TEXT->mapper.getNodeFactory().textNode(v.textValue);case NUMBER->mapper.getNodeFactory().numberNode(v.numberValue);case CHECKBOX->mapper.getNodeFactory().booleanNode(Boolean.TRUE.equals(v.checkboxValue));case DATE->mapper.getNodeFactory().textNode(v.dateValue.toString());case SINGLE_SELECT->mapper.getNodeFactory().textNode(v.optionId.toString());};}
    private void audit(UUID project,UUID user,String action,UUID id){events.record(action, id, project, user, List.of(), 0);}
}
