import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.env.PROJECT_PLAN_EVIDENCE_DIR || "D:/Project/Ai ERP/.tmp/evidence/project-plan-views-20260927/attempt2";
await fs.mkdir(root, { recursive: true });
const playwrightPath = process.env.PLAYWRIGHT_ENTRY || "C:/Users/hanyu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.js";
const chromePath = process.env.CHROME_EXECUTABLE || "C:/Program Files/Google/Chrome/Application/chrome.exe";
const playwright = await import(pathToFileURL(playwrightPath).href);
const chromium = playwright.default?.chromium ?? playwright.chromium;
const browser = await chromium.launch({ headless: true, executablePath: chromePath });
const checks = [];
const expect = (value, text) => { if (!value) throw new Error(text); checks.push(text); };
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await context.newPage();
page.setDefaultTimeout(8_000);
const base = `${process.env.PROJECT_PLAN_UI_URL || "http://127.0.0.1:5173"}/#/projects/p1/plan?view=`;
const ready = async (view) => { await page.goto(`${base}${view}`, { waitUntil: "domcontentloaded" }); await page.getByRole("heading", { name: "계획", exact: true }).waitFor(); await page.locator(".plan-snapshot-meta").waitFor(); await page.waitForTimeout(150); };
try {
  let dialog;
  await ready("roadmap");
  expect(await page.locator(".plan-snapshot-meta").innerText().then(text => /필터 항목 \d+개/.test(text)), "complete snapshot exposes filtered ITEM count");
  expect((await page.getByText(/목표 범위 밖/).count()) > 0, "roadmap exposes TASK forecast variance without overwriting manual targets");
  for (const view of ["hierarchy", "tasks", "board", "milestones", "calendar"]) {
    await page.getByRole("link", { name: view === "hierarchy" ? "계층" : view === "tasks" ? "작업" : view === "board" ? "보드" : view === "milestones" ? "Milestone" : "월간" }).click();
    await page.getByRole("heading", { name: "계획" }).waitFor();
  }
  await ready("hierarchy"); await page.getByLabel("TASK·Milestone도 펼쳐 보기").click(); await page.waitForURL(/types=EPIC%2CTOPIC%2CTASK%2CMILESTONE/); await page.getByRole("button", { name: "실행 작업 1", exact: true }).waitFor(); expect(true, "hierarchy leaf toggle refetches TASK and Milestone matches from the server");
  await ready("tasks");
  const search = page.getByLabel("검색");
  await search.fill("실행 작업 12"); await page.getByRole("button", { name: "필터 적용" }).click();
  expect(new URL(page.url()).hash.includes("q=%EC%8B%A4%ED%96%89"), "filter query persists in URL");
  await page.getByRole("button", { name: "필터 초기화" }).click();
  expect(!new URL(page.url()).hash.includes("q="), "filter reset removes old query parameters");
  await page.waitForFunction(() => document.querySelector('input[name="q"]')?.value === ""); expect(true, "filter reset clears the visible search control");
  await page.locator('select[name="assigneeId"]').selectOption("u1"); await page.getByRole("button", { name: "필터 적용" }).click();
  expect(new URL(page.url()).hash.includes("assigneeId=u1"), "assignee filter persists");
  await ready("tasks");
  await page.getByLabel("그룹").selectOption("parent");
  const taskRows = await page.locator(".plan-semantic-table tbody tr:not(.plan-group-row)").count();
  const parentGroups = await page.locator(".plan-group-row").count();
  expect(parentGroups > 0 && parentGroups < taskRows, "parent grouping combines sibling TASK rows under their parent");
  await page.getByRole("button", { name: "다음", exact: true }).click();
  await page.getByLabel("검색").fill("실행 작업 12"); await page.getByRole("button", { name: "필터 적용" }).click();
  await page.getByRole("button", { name: "실행 작업 12", exact: true }).waitFor();
  expect((await page.getByText(/51–/).count()) === 0, "task pagination clamps to the first valid page after filters narrow results");
  await page.goto(`${base}hierarchy&types=TASK&q=%EC%8B%A4%ED%96%89%20%EC%9E%91%EC%97%85%2012`, { waitUntil: "domcontentloaded" });
  await page.getByRole("button", { name: "실행 작업 12", exact: true }).waitFor();
  expect(true, "filtered hierarchy renders a matching child even when its parent is context only");
  await ready("milestones");
  expect((await page.getByText(/실행 작업 5/).count()) > 0 && (await page.getByText(/실행 작업 6|충돌 뒤 재시도/).count()) > 0, "milestone impact resolves unfinished successors from the complete graph");
  await page.goto(`${base}hierarchy&scopeId=topic-1`, { waitUntil: "domcontentloaded" }); await page.locator(".plan-snapshot-meta").waitFor();
  await page.getByRole("button", { name: "새 TASK" }).click();
  dialog = page.getByRole("dialog");
  expect(await dialog.getByLabel("상위 항목").inputValue() === "topic-1", "scoped create defaults to the selected container parent");
  await dialog.getByRole("button", { name: "취소" }).click();
  await ready("tasks");
  const task = page.locator(".plan-semantic-table .plan-title").first();
  await task.click(); await page.getByRole("dialog").getByRole("button", { name: "편집" }).click();
  dialog = page.getByRole("dialog"); await dialog.getByRole("textbox", { name: "제목", exact: true }).fill("편집 성공 확인"); await Promise.all([page.waitForResponse((response) => response.request().method() === "PATCH" && /\/plan\/items\//.test(response.url())), dialog.getByRole("button", { name: "저장", exact: true }).click()]); await dialog.waitFor({ state: "detached" }); await page.getByText("편집 성공 확인", { exact: true }).waitFor();
  await page.getByRole("button", { name: "새 Topic" }).click(); dialog = page.getByRole("dialog"); await dialog.getByRole("textbox", { name: "제목", exact: true }).fill("새 UI Topic"); await dialog.getByLabel("레이블").fill("검토, UI"); await Promise.all([page.waitForResponse((response) => response.request().method() === "POST" && response.url().endsWith("/plan/items")), dialog.getByRole("button", { name: "저장", exact: true }).click()]); await dialog.waitFor({ state: "detached" });
  await ready("roadmap"); await page.reload({ waitUntil: "domcontentloaded" }); await page.locator(".plan-snapshot-meta").waitFor(); expect(await page.getByRole("button", { name: "새 UI Topic", exact: true }).count() > 0, "create persists a plan item without provider calls");
  await ready("calendar"); expect((await page.locator(".calendar-more").count()) > 0, "month overflow collapses busy days behind an explicit more control"); await page.locator(".calendar-more").first().click(); expect((await page.getByRole("dialog").locator("li").count()) > 3, "month overflow dialog exposes all hidden plan items"); await page.keyboard.press("Escape"); await page.locator(".calendar-toolbar select").selectOption("EPIC"); await page.getByRole("button", { name: /운영 안정화/ }).first().waitFor(); expect(true, "calendar EPIC selection refetches and renders EPIC records"); await page.locator(".calendar-toolbar select").selectOption("TOPIC"); await page.getByRole("button", { name: /데이터 품질/ }).first().waitFor(); expect(true, "calendar TOPIC selection refetches and renders TOPIC records"); await page.locator(".calendar-toolbar select").selectOption("ALL"); await page.getByRole("button", { name: /운영 안정화/ }).first().waitFor(); await page.getByRole("button", { name: /데이터 품질/ }).first().waitFor(); expect(true, "calendar ALL selection refetches and renders all plan kinds");
  await page.goto(`${base}calendar&types=EPIC%2CTOPIC&calendarKind=EPIC`, { waitUntil: "domcontentloaded" }); await page.locator(".plan-snapshot-meta").waitFor(); await page.getByRole("button", { name: /운영 안정화/ }).first().waitFor(); await page.getByRole("button", { name: /데이터 품질/ }).first().waitFor(); expect(await page.locator(".calendar-toolbar select").inputValue() === "CUSTOM", "calendar renders a mixed EPIC and TOPIC query with an explicit custom type label");
  await page.goto(`${base}calendar&types=APPOINTMENT`, { waitUntil: "domcontentloaded" }); await page.locator(".plan-snapshot-meta").waitFor(); await page.getByRole("button", { name: "실행 작업 1", exact: true }).waitFor(); await page.getByRole("button", { name: /베타 검토/ }).first().waitFor(); expect(true, "appointment-only overlay input falls back to the calendar plan defaults for server and rendering");
  await ready("calendar"); await page.locator(".calendar-toolbar select").selectOption("EPIC");
  expect(new URL(page.url()).hash.includes("calendarKind=EPIC"), "calendar kind persists in URL");
  await page.locator('select[name="types"]').selectOption("TASK"); await page.getByRole("button", { name: "필터 적용" }).click(); await page.locator(".calendar-toolbar select").waitFor(); expect(await page.locator(".calendar-toolbar select").inputValue() === "TASK", "common type filter overrides a stale calendarKind with one effective interpretation"); await page.getByRole("button", { name: /실행 작업 1/ }).first().waitFor(); await page.locator(".calendar-toolbar select").selectOption("EPIC");
  await page.getByLabel("월").fill("2026-10"); await page.waitForTimeout(100); expect(page.url().includes("month=2026-10"), "calendar month persists in URL");
  await page.getByLabel("검색").fill("검토"); await page.getByRole("button", { name: "필터 적용" }).click();
  expect(page.url().includes("month=2026-10") && page.url().includes("calendarKind=EPIC"), "filter apply preserves calendar month and type context");
  await page.getByLabel("기존 일정 함께 보기").click(); await page.waitForURL(/types=.*APPOINTMENT/); const septemberSchedules = page.waitForRequest((request) => { const url = new URL(request.url()); return url.pathname === "/api/v1/projects/p1/schedules" && url.searchParams.get("from") === "2026-08-31T15:00:00.000Z" && url.searchParams.get("to") === "2026-09-30T15:00:00.000Z"; }); await page.getByLabel("월").fill("2026-09"); await septemberSchedules; expect(true, "appointment overlay requests Asia/Seoul month boundaries as exact UTC instants");
  await page.getByText("기존 일정 · 읽기 전용").first().waitFor();
  expect((await page.locator(".calendar-appointment").count()) > 0, "appointment overlay loads separately and remains read-only");
  expect(await page.locator(".calendar-weekdays span").count() === 7, "calendar renders weekday context");
  await ready("tasks"); await page.getByRole("button", { name: "실행 작업 16", exact: true }).click(); await page.getByRole("dialog").getByRole("button", { name: "편집" }).click(); dialog = page.getByRole("dialog");
  await dialog.getByRole("textbox", { name: "제목", exact: true }).fill("충돌 뒤 재시도"); let forced = true;
  await page.route("**/api/v1/projects/p1/plan/items/task-16", async route => { if (route.request().method() === "PATCH" && forced) { forced = false; await route.fulfill({ status: 409, contentType: "application/problem+json", body: JSON.stringify({ code: "CONFLICT" }) }); } else await route.continue(); });
  await dialog.getByRole("button", { name: "저장", exact: true }).click(); await dialog.getByRole("alert").waitFor(); await dialog.getByRole("button", { name: "내 입력을 최신 version으로 재시도" }).click();
  await page.unroute("**/api/v1/projects/p1/plan/items/task-16"); await page.reload({ waitUntil: "domcontentloaded" }); await page.locator(".plan-snapshot-meta").waitFor(); await page.getByText("충돌 뒤 재시도", { exact: true }).first().waitFor(); expect(true, "409 draft rebase retries successfully");
  let quickForced = true;
  await page.route("**/api/v1/projects/p1/plan/items/task-11", async route => { if (route.request().method() === "PATCH" && quickForced) { quickForced = false; await route.fulfill({ status: 409, contentType: "application/problem+json", body: JSON.stringify({ code: "CONFLICT" }) }); } else await route.continue(); });
  await page.route("**/api/v1/projects/p1/plan", async route => { if (route.request().method() !== "GET") return route.continue(); const response = await route.fetch(); const body = await response.json(); body.items = body.items.map((item) => item.id === "task-11" ? { ...item, description: "동료 최신 설명", assigneeId: "u2", rowVersion: item.rowVersion + 1 } : item); await route.fulfill({ response, json: body }); });
  await page.getByLabel("실행 작업 11 상태").selectOption("DONE");
  dialog = page.getByRole("dialog"); await dialog.waitFor();
  expect(await dialog.getByLabel("상태").inputValue() === "DONE" && await dialog.getByLabel("설명").inputValue() === "동료 최신 설명" && await dialog.getByLabel("담당자").inputValue() === "u2", "quick write 409 reapplies only the intended field over the latest server item"); await dialog.getByRole("alert").waitFor();
  await dialog.getByRole("button", { name: "취소", exact: true }).click(); await page.unroute("**/api/v1/projects/p1/plan/items/task-11"); await page.unroute("**/api/v1/projects/p1/plan");
  await ready("tasks"); await page.getByRole("button", { name: "실행 작업 11", exact: true }).click();
  await page.route("**/api/v1/projects/p1/plan/items/task-11/history?*", async route => { const url = new URL(route.request().url()); const historyPage = Number(url.searchParams.get("page")); await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ entries: [{ id: `history-${historyPage}`, actorId: historyPage ? "removed-user" : "u2", occurredAt: "2026-09-10T00:00:00Z", version: historyPage + 2, reason: "범위 조정", before: { parentId: "topic-1", title: "실행 작업 11", description: "이전 설명", deadline: "2026-09-20", labels: ["이전"], predecessorIds: ["task-1"] }, after: { parentId: "topic-2", title: "실행 작업 11", description: "새 설명", deadline: "2026-09-21", labels: ["새 레이블"], predecessorIds: ["milestone-1"] } }], hasNext: historyPage === 0 }) }); });
  await page.getByRole("dialog").getByRole("button", { name: "변경 이력" }).click();
  await page.getByText(/변경자 .*u2|변경자 .*구성원/).waitFor(); await page.getByRole("button", { name: "이전 이력" }).click();
  await page.getByText("변경자 확인할 수 없는 사용자 (removed-user)").waitFor();
  await page.getByRole("dialog").getByText("변경 내용").click(); await page.getByText(/새 설명/).waitFor(); expect(true, "history pages expose actor identity and readable parent, dependency, label, description and deadline changes");
  await page.unroute("**/api/v1/projects/p1/plan/items/task-11/history?*"); await page.getByRole("dialog").getByRole("button", { name: "닫기" }).click();
  await ready("roadmap"); await page.getByRole("button", { name: "목표일 편집" }).click(); await page.getByLabel("종료일").fill("2026-11-30");
  let targetForced = true; await page.route("**/api/v1/projects/p1/plan", async route => { if (route.request().method() === "PATCH" && targetForced) { targetForced = false; await route.fulfill({ status: 409, contentType: "application/problem+json", body: JSON.stringify({ code: "CONFLICT" }) }); } else await route.continue(); });
  await page.getByRole("button", { name: "저장", exact: true }).click(); await page.getByText("프로젝트 목표가 변경되었다.").waitFor(); await page.getByRole("button", { name: "내 입력을 최신 version으로 재시도" }).click(); await page.unroute("**/api/v1/projects/p1/plan");
  await ready("roadmap"); expect((await page.getByText(/2026-11-30/).count()) > 0, "project target 409 preserves and retries proposed dates");
  await ready("tasks"); await page.getByLabel("실행 작업 19 담당자").selectOption("u2"); await page.waitForTimeout(150); expect(await page.getByLabel("실행 작업 19 담당자").inputValue() === "u2", "assignee updates inline alongside title, state and date controls"); const keyboardTask = page.getByRole("button", { name: "실행 작업 17", exact: true }); await keyboardTask.focus(); await page.keyboard.press("Enter"); dialog = page.getByRole("dialog"); await dialog.waitFor(); expect(await dialog.evaluate((node) => node.contains(document.activeElement)), "keyboard opening moves focus inside the detail dialog"); await page.keyboard.press("Escape"); await dialog.waitFor({ state: "detached" }); expect(await keyboardTask.evaluate((node) => node === document.activeElement), "Escape closes the dialog and restores focus to its caller");
  await ready("roadmap");
  for (const width of [1440, 768, 390, 320]) { await page.setViewportSize({ width, height: 900 }); await page.evaluate(() => scrollTo(0, 0)); await page.screenshot({ path: path.join(root, `viewport-${width}-top.png`), fullPage: false }); expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth <= 1), `${width}px has no page overflow`); }
  await page.setViewportSize({ width: 720, height: 450 }); expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth <= 1), "200% zoom equivalent layout reflows without page overflow");
  await page.setViewportSize({ width: 1440, height: 900 }); await ready("tasks"); await page.getByRole("button", { name: "실행 작업 18", exact: true }).click(); await page.getByRole("dialog").screenshot({ path: path.join(root, "detail-1440.png") }); await page.keyboard.press("Escape");
  const laContext = await browser.newContext({ viewport: { width: 1440, height: 900 }, timezoneId: "America/Los_Angeles" }); const laPage = await laContext.newPage(); await laPage.goto(`${base}tasks`, { waitUntil: "domcontentloaded" }); await laPage.locator(".plan-snapshot-meta").waitFor(); expect(await laPage.getByLabel("실행 작업 1 시작일").inputValue() === "2026-09-02", "date-only planning fields do not shift in America/Los_Angeles"); await laContext.close();
  const viewerContext = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const viewerPage = await viewerContext.newPage(); await viewerPage.route("**/api/v1/projects?*", async route => { const response = await route.fetch(); const body = await response.json(); await route.fulfill({ response, json: body.map((project) => project.id === "p1" ? { ...project, role: "VIEWER" } : project) }); }); await viewerPage.goto(`${base}tasks`, { waitUntil: "domcontentloaded" }); await viewerPage.locator(".plan-snapshot-meta").waitFor(); expect(await viewerPage.getByRole("button", { name: "새 TASK" }).isDisabled(), "VIEWER can read the plan while write actions remain disabled"); await viewerContext.close();
  await ready("tasks"); await page.route("**/api/v1/projects/p1/plan/items/task-17", route => route.fulfill({ status: 403, contentType: "application/problem+json", body: JSON.stringify({ code: "FORBIDDEN" }) })); await page.getByLabel("실행 작업 17 상태").selectOption("DONE"); await page.getByText(/권한이 변경되어 편집을 잠갔습니다/).waitFor(); expect(await page.getByRole("button", { name: "새 TASK" }).isDisabled(), "403 role revocation clears plan/member caches and locks protected writes"); await page.unroute("**/api/v1/projects/p1/plan/items/task-17");
  console.log(JSON.stringify({ passed: checks.length, evidenceRoot: root }));
} finally { await browser.close(); }
