import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ApiError, api, type PropertyOption, type ScheduleProperty, type ScheduleWorkspace, type ScheduleWorkspaceRecord, type ViewWrite, type WorkspaceConfig, type WorkspaceField, type WorkspaceFilter, type WorkspaceView } from "../api/client";
import { accessRead, isAccessError, keys, refreshSchedule, useMe, useProject } from "../state";
import { Dialog, Link, Notice, ProjectMissing, QueryState, Shell, go } from "../ui";
import { dateInZone, displayTime, localDateTimeToUtc, utcToLocalDateTime, viewWindow } from "../time";
import { readWorkspaceCalendar, Schedules as LegacySchedules, workspaceCalendarIdentity } from "./Schedules";
import { useUnsavedChanges } from "../unsaved-changes";
import "./schedule-workspace.css";

const builtin = (id: "builtin-calendar" | "builtin-cards" | "builtin-list", type: WorkspaceConfig["type"], name: string): WorkspaceView => ({ id, name, scope: "BUILTIN", ownerId: null, rowVersion: 0, archived: false, config: { type, filters: [], sorts: type === "CALENDAR" ? [{ field: "startsAt", direction: "ASC" }] : [], groupBy: null, legendBy: null, visibleFields: ["title", "startsAt", "endsAt", "status"] } });
const builtinViews = [builtin("builtin-calendar", "CALENDAR", "캘린더"), builtin("builtin-cards", "CARDS", "카드"), builtin("builtin-list", "LIST", "목록")];
const fixedFieldNames: Record<string, string> = { title: "제목", startsAt: "시작", endsAt: "종료", status: "상태", createdBy: "작성자" };
const fieldName = (field: WorkspaceField, properties: ScheduleProperty[]) => field.startsWith("property:") ? properties.find(p => p.id === field.slice(9))?.name ?? "보관된 속성" : fixedFieldNames[field] ?? field;
const optionLabel = (value: unknown, property: ScheduleProperty | undefined) => { if (value === null || value === undefined || value === "") return "설정 안 함"; if (!property) return String(value); const option = property.options.find(item => item.id === value); return option ? `${option.label}${option.archived ? " · 보관됨" : ""}` : String(value); };
const signature = (config: WorkspaceConfig) => JSON.stringify(config);
const setContext = (id: string, extras: Record<string, string | number | undefined> = {}) => { const params = new URLSearchParams(window.location.hash.split("?")[1] ?? ""); params.set("view", id); for (const [key, value] of Object.entries(extras)) { if (value === undefined) params.delete(key); else params.set(key, String(value)); } go(`${window.location.hash.replace(/^#/, "").split("?")[0]}?${params.toString()}`); };
const returnSuffix = () => { const query = window.location.hash.split("?")[1]; return query ? `?return=${encodeURIComponent(query)}` : ""; };
const hashContext = () => { const params = new URLSearchParams(window.location.hash.split("?")[1] ?? ""); const rawView = params.get("view") ?? "builtin-calendar"; const rawPage = Number(params.get("page") ?? 0); const rawDate = params.get("date"); return { view: rawView === "week" || rawView === "month" ? "builtin-calendar" : rawView === "list" ? "builtin-list" : rawView, page: Number.isInteger(rawPage) && rawPage >= 0 ? rawPage : 0, date: rawDate && /^\d{4}-\d{2}-\d{2}$/.test(rawDate) ? rawDate : dateInZone(new Date().toISOString(), "Asia/Seoul"), mode: rawView === "week" || params.get("mode") === "week" ? "week" as const : "month" as const }; };
const normalizeLegacyHash = () => {
    const [path, query = ""] = window.location.hash.replace(/^#/, "").split("?");
    const params = new URLSearchParams(query);
    const legacy = params.get("view");
    if (legacy !== "month" && legacy !== "week" && legacy !== "list") return;
    params.set("view", legacy === "list" ? "builtin-list" : "builtin-calendar");
    if (legacy === "month" || legacy === "week") params.set("mode", legacy);
    else params.delete("mode");
    params.set("page", "0");
    window.history.replaceState(null, "", `#${path}?${params.toString()}`);
    window.dispatchEvent(new HashChangeEvent("hashchange"));
};

function Value({ field, record, properties }: { field: WorkspaceField; record: ScheduleWorkspaceRecord; properties: ScheduleProperty[] }) {
    if (field === "title") return <strong>{record.schedule.title}</strong>;
    if (field === "startsAt") return <time dateTime={record.schedule.startsAt}>{displayTime(record.schedule.startsAt)}</time>;
    if (field === "endsAt") return <time dateTime={record.schedule.endsAt}>{displayTime(record.schedule.endsAt)}</time>;
    if (field === "status") return <span>{record.schedule.status === "CONFIRMED" ? "확정" : record.schedule.status === "CANCELLED" ? "취소" : "초안"}</span>;
    if (field === "createdBy") return <span>{record.schedule.createdBy}</span>;
    const property = properties.find(item => item.id === field.slice(9));
    const value = record.values[property?.id ?? ""];
    return <span>{property?.type === "CHECKBOX" ? (value === null || value === undefined ? "설정 안 함" : value ? "예" : "아니오") : optionLabel(value, property)}</span>;
}

function Legend({ value, property }: { value: unknown; property?: ScheduleProperty }) {
    if (!property) return null;
    if (value === null || value === undefined || value === "") return <span className="workspace-legend"><i aria-hidden="true" data-color="gray" />설정 안 함</span>;
    const option = property.options.find(item => item.id === value);
    return <span className="workspace-legend"><i aria-hidden="true" data-color={option?.color ?? "gray"} />{option ? `${option.label}${option.archived ? " · 보관됨" : ""}` : `보관된 옵션 · ${String(value)}`}</span>;
}

function ViewSettings({ projectId, current, properties, canManage, blocked, onSaved, onClose, onReload, onDenied }: { projectId: string; current: WorkspaceView; properties: ScheduleProperty[]; canManage: boolean; blocked: boolean; onSaved: (view: WorkspaceView) => void; onClose: () => void; onReload: () => void; onDenied: () => void }) {
    const [name, setName] = useState(current.name);
    const [scope, setScope] = useState<"PERSONAL" | "SHARED">(current.scope === "BUILTIN" ? "PERSONAL" : current.scope);
    const [baseVersion] = useState(current.rowVersion);
    const [config, setConfig] = useState<WorkspaceConfig>(() => structuredClone(current.config));
    const [error, setError] = useState<string | null>(null);
    const [conflict, setConflict] = useState(false);
    const [discardOpen, setDiscardOpen] = useState(false);
    const save = useMutation({ mutationFn: (body: ViewWrite) => { if (blocked) throw new Error("접근 상태를 다시 확인해야 합니다."); if (current.scope === "BUILTIN") return api.workspaceViewCreate(projectId, body); if (current.scope === "SHARED" && !canManage) return api.workspaceViewCreate(projectId, { ...body, scope: "PERSONAL" }); return api.workspaceViewEdit(projectId, current.id, { ...body, scope: current.scope }); }, onSuccess: onSaved, onError: errorValue => { if (isAccessError(errorValue)) onDenied(); const nextConflict = errorValue instanceof ApiError && errorValue.status === 409; setConflict(nextConflict); setError(nextConflict ? "다른 사용자가 이 보기를 변경했습니다. 최신 내용을 다시 불러오거나 초안으로 복제하세요." : "보기를 저장하지 못했습니다."); } });
    const duplicateDraft = useMutation({ mutationFn: () => { if (blocked) throw new Error("접근 상태를 다시 확인해야 합니다."); return api.workspaceViewCreate(projectId, { name: `${name.trim() || current.name} 복사본`, scope: "PERSONAL", config }); }, onSuccess: onSaved, onError: errorValue => { if (isAccessError(errorValue)) onDenied(); setError("초안을 복제하지 못했습니다."); } });
    const fields = properties.filter(property => !property.archived).map(property => `property:${property.id}` as WorkspaceField);
    const addFilter = () => { if (config.filters.length >= 10) return; setConfig(value => ({ ...value, filters: [...value.filters, { field: "title", operator: "CONTAINS", value: "" }] })); };
    const updateFilter = (index: number, next: Partial<WorkspaceFilter>) => setConfig(value => ({ ...value, filters: value.filters.map((filter, position) => position === index ? { ...filter, ...next } : filter) }));
    const removeFilter = (index: number) => setConfig(value => ({ ...value, filters: value.filters.filter((_, position) => position !== index) }));
    const updateSort = (index: number, next: Partial<WorkspaceConfig["sorts"][number]>) => setConfig(value => ({ ...value, sorts: value.sorts.map((sort, position) => position === index ? { ...sort, ...next } : sort) }));
    const moveSort = (index: number, direction: -1 | 1) => setConfig(value => { const next = [...value.sorts]; const target = index + direction; if (target < 0 || target >= next.length) return value; [next[index], next[target]] = [next[target], next[index]]; return { ...value, sorts: next }; });
    const addSort = () => { if (config.sorts.length >= 3) return; setConfig(value => ({ ...value, sorts: [...value.sorts, { field: "startsAt", direction: "ASC" }] })); };
    const filterProperty = (field: WorkspaceField) => field.startsWith("property:") ? properties.find(property => property.id === field.slice(9)) : undefined;
    const filterInputValue = (filter: WorkspaceFilter) => filter.field === "startsAt" || filter.field === "endsAt" ? (filter.value ? utcToLocalDateTime(String(filter.value), "Asia/Seoul") : "") : String(filter.value ?? "");
    const updateFilterValue = (filter: WorkspaceFilter, index: number, raw: string) => { if (!raw) { updateFilter(index, { value: null }); return; } if (filter.field === "startsAt" || filter.field === "endsAt") { try { updateFilter(index, { value: localDateTimeToUtc(raw, "Asia/Seoul") }); } catch { updateFilter(index, { value: raw }); } return; } updateFilter(index, { value: raw }); };
    const filterType = (field: WorkspaceField) => filterProperty(field)?.type ?? (field === "title" ? "TEXT" : field === "status" ? "STATUS" : field === "createdBy" ? "CREATOR" : "DATE");
    const operatorOptions = (field: WorkspaceField) => { const type = filterType(field); return type === "TEXT" ? ["EQ", "NE", "CONTAINS", "IS_EMPTY", "IS_NOT_EMPTY"] : type === "CREATOR" || type === "STATUS" ? ["EQ", "NE", "IS_EMPTY", "IS_NOT_EMPTY"] : type === "CHECKBOX" || type === "SINGLE_SELECT" ? ["EQ", "NE", "IS_EMPTY", "IS_NOT_EMPTY"] : ["EQ", "NE", "GT", "GTE", "LT", "LTE", "IS_EMPTY", "IS_NOT_EMPTY"]; };
    const renderFilterValue = (filter: WorkspaceFilter, index: number) => { if (filter.operator.startsWith("IS_")) return null; const property = filterProperty(filter.field); if (property?.type === "CHECKBOX") return <label>값<select value={filter.value === true ? "true" : filter.value === false ? "false" : ""} onChange={event => updateFilter(index, { value: event.target.value === "" ? null : event.target.value === "true" })}><option value="">선택</option><option value="true">예</option><option value="false">아니오</option></select></label>; if (property?.type === "SINGLE_SELECT" || filter.field === "status") return <label>값<select value={String(filter.value ?? "")} onChange={event => updateFilter(index, { value: event.target.value || null })}><option value="">선택</option>{filter.field === "status" ? <><option value="DRAFT">초안</option><option value="CONFIRMED">확정</option><option value="CANCELLED">취소</option></> : property?.options.map(option => <option key={option.id} value={option.id}>{option.label}{option.archived ? " · 보관됨" : ""}</option>)}</select></label>; if (property?.type === "NUMBER") return <label>값<input type="number" step="any" value={filter.value == null ? "" : String(filter.value)} onChange={event => updateFilter(index, { value: event.target.value === "" ? null : Number(event.target.value) })} /></label>; if (property?.type === "DATE") return <label>값<input type="date" value={String(filter.value ?? "")} onChange={event => updateFilter(index, { value: event.target.value || null })} /></label>; if (filter.field === "startsAt" || filter.field === "endsAt") return <label>값<input type="datetime-local" value={filterInputValue(filter)} onChange={event => updateFilterValue(filter, index, event.target.value)} /></label>; return <label>값<input value={String(filter.value ?? "")} onChange={event => updateFilter(index, { value: event.target.value })} /></label>; };
    const initialScope = current.scope === "BUILTIN" ? "PERSONAL" : current.scope;
    const dirty = name !== current.name || scope !== initialScope || signature(config) !== signature(current.config);
    const close = () => { if (dirty) setDiscardOpen(true); else onClose(); };
    const submit = (event: React.FormEvent) => { event.preventDefault(); if (blocked) return; if (!name.trim()) { setError("보기 이름을 입력하세요."); return; } if (config.filters.some(filter => filter.value !== null && filter.value !== "" && typeof filter.value === "number" && !Number.isFinite(filter.value))) { setError("필터 숫자는 유효한 값이어야 합니다."); return; } save.mutate({ name: name.trim(), scope: current.scope === "SHARED" && !canManage ? "PERSONAL" : scope, config, ...(current.scope === "BUILTIN" ? {} : { rowVersion: baseVersion }) }); };
    return <><Dialog open={!discardOpen} title={current.scope === "SHARED" && !canManage ? "공유 보기 복사" : "보기 설정"} labelledBy="workspace-settings-title" className="modal-workspace-settings" onClose={close}><form className="workspace-settings" onSubmit={submit}>
        <label>이름<input value={name} maxLength={80} onChange={event => setName(event.target.value)} /></label>
        <label>공유 범위<select value={scope} disabled={current.scope !== "BUILTIN" || !canManage} onChange={event => setScope(event.target.value as "PERSONAL" | "SHARED")}><option value="PERSONAL">개인</option><option value="SHARED">공유</option></select></label>
        <fieldset><legend>필터 · AND</legend>{config.filters.map((filter, index) => <div className="workspace-filter-row" key={`${index}-${filter.field}`}><label>필드<select value={filter.field} onChange={event => updateFilter(index, { field: event.target.value as WorkspaceField, operator: operatorOptions(event.target.value as WorkspaceField)[0] as WorkspaceFilter["operator"], value: null })}>{["title", "startsAt", "endsAt", "status", "createdBy", ...fields].map(field => <option key={field} value={field}>{fieldName(field as WorkspaceField, properties)}</option>)}</select></label><label>연산자<select value={filter.operator} onChange={event => updateFilter(index, { operator: event.target.value as WorkspaceFilter["operator"] })}>{operatorOptions(filter.field).map(operator => <option key={operator} value={operator}>{operator}</option>)}</select></label>{renderFilterValue(filter, index)}<button type="button" onClick={() => removeFilter(index)}>필터 제거</button></div>)}<button type="button" onClick={addFilter} disabled={config.filters.length >= 10}>필터 추가</button></fieldset>
        <fieldset><legend>그룹과 범례</legend><label>그룹<select value={config.groupBy ?? ""} onChange={event => setConfig(value => ({ ...value, groupBy: event.target.value || null }))}><option value="">없음</option>{properties.filter(p => p.type === "SINGLE_SELECT").map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>범례<select value={config.legendBy ?? ""} onChange={event => setConfig(value => ({ ...value, legendBy: event.target.value || null }))}><option value="">없음</option>{properties.filter(p => p.type === "SINGLE_SELECT").map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></fieldset>
        <fieldset><legend>정렬 순서 · 최대 3개</legend>{config.sorts.map((sort, index) => <div className="workspace-filter-row" key={`${index}-${sort.field}`}><label>필드<select value={sort.field} onChange={event => updateSort(index, { field: event.target.value as WorkspaceField })}>{["title", "startsAt", "endsAt", "status", "createdBy", ...fields].map(field => <option key={field} value={field}>{fieldName(field as WorkspaceField, properties)}</option>)}</select></label><label>방향<select value={sort.direction} onChange={event => updateSort(index, { direction: event.target.value as "ASC" | "DESC" })}><option value="ASC">오름차순</option><option value="DESC">내림차순</option></select></label><button type="button" onClick={() => moveSort(index, -1)} disabled={!index}>위로</button><button type="button" onClick={() => moveSort(index, 1)} disabled={index === config.sorts.length - 1}>아래로</button><button type="button" onClick={() => setConfig(value => ({ ...value, sorts: value.sorts.filter((_, position) => position !== index) }))}>정렬 제거</button></div>)}<button type="button" disabled={config.sorts.length >= 3} onClick={addSort}>정렬 추가</button></fieldset>
        <fieldset><legend>표시 필드</legend>{["title", "startsAt", "endsAt", "status", "createdBy", ...fields].map(field => <label className="workspace-check" key={field}><input type="checkbox" checked={config.visibleFields.includes(field as WorkspaceField)} disabled={field === "title"} onChange={event => setConfig(value => ({ ...value, visibleFields: event.target.checked ? [...value.visibleFields, field as WorkspaceField] : value.visibleFields.filter(item => item !== field) }))} />{fieldName(field as WorkspaceField, properties)}</label>)}</fieldset>
        {error && <p role="alert" className="schedule-inline-alert">{error}</p>}{conflict && <div className="schedule-form-actions"><button type="button" disabled={blocked} onClick={onReload}>최신 보기 다시 불러오기</button><button type="button" disabled={blocked || duplicateDraft.isPending} onClick={() => duplicateDraft.mutate()}>초안으로 복제</button></div>}<div className="schedule-form-actions"><button type="button" onClick={close}>취소</button><button className="button-primary" type="submit" disabled={blocked || save.isPending}>보기 저장</button></div>
    </form></Dialog>{discardOpen && <Dialog open title="변경사항 버리기" labelledBy="workspace-discard-view-title" onClose={() => setDiscardOpen(false)}><p>저장하지 않은 보기 설정이 있습니다.</p><div className="schedule-form-actions"><button type="button" onClick={() => setDiscardOpen(false)}>계속 편집</button><button type="button" className="button-danger" onClick={onClose}>변경사항 버리기</button></div></Dialog>}</>;
}

function PropertiesDialog({ projectId, properties, canManage, onClose, onDenied }: { projectId: string; properties: ScheduleProperty[]; canManage: boolean; onClose: () => void; onDenied: () => void }) {
    const qc = useQueryClient();
    const [draft, setDraft] = useState<Record<string, { name: string; position: number; archived: boolean }>>(() => Object.fromEntries(properties.map(property => [property.id, { name: property.name, position: property.position, archived: property.archived }])));
    const [versions, setVersions] = useState<Record<string, number>>(() => Object.fromEntries(properties.map(property => [property.id, property.rowVersion])));
    const [newName, setNewName] = useState(""); const [newType, setNewType] = useState<ScheduleProperty["type"]>("TEXT"); const [error, setError] = useState<string | null>(null);
    const [optionDirty, setOptionDirty] = useState<Record<string, boolean>>({});
    const [discardOpen, setDiscardOpen] = useState(false);
    const create = useMutation({ mutationFn: () => api.workspacePropertyCreate(projectId, { name: newName.trim(), type: newType }), onSuccess: () => { setNewName(""); void qc.invalidateQueries({ queryKey: keys.workspace(projectId) }); }, onError: errorValue => { if (isAccessError(errorValue)) onDenied(); setError("속성을 만들지 못했습니다."); } });
    const patch = useMutation({ mutationFn: ({ property, value }: { property: ScheduleProperty; value: { name: string; position: number; archived: boolean } }) => api.workspacePropertyEdit(projectId, property.id, { ...value, rowVersion: versions[property.id] }), onSuccess: saved => { setDraft(current => ({ ...current, [saved.id]: { name: saved.name, position: saved.position, archived: saved.archived } })); setVersions(current => ({ ...current, [saved.id]: saved.rowVersion })); void qc.invalidateQueries({ queryKey: keys.workspace(projectId) }); }, onError: errorValue => { if (isAccessError(errorValue)) onDenied(); setError("속성 변경이 충돌했거나 거부되었습니다. 최신 상태를 확인한 뒤 다시 입력하세요."); } });
    const dirty = !!newName || Object.values(optionDirty).some(Boolean) || properties.some(property => { const value = draft[property.id]; return value && (value.name !== property.name || value.position !== property.position || value.archived !== property.archived); });
    const close = () => { if (dirty) setDiscardOpen(true); else onClose(); };
    return <><Dialog open={!discardOpen} title="프로젝트 속성" labelledBy="workspace-properties-title" className="modal-workspace-properties" onClose={close}><div className="workspace-properties"><p>속성 이름과 순서를 바꿀 수 있습니다. 보관은 되돌릴 수 있고 저장된 값은 유지됩니다.</p>{properties.map(property => <div key={property.id}><div className="workspace-property-row"><label>이름<input value={draft[property.id]?.name ?? property.name} disabled={!canManage} onChange={event => setDraft(value => ({ ...value, [property.id]: { ...value[property.id], name: event.target.value } }))} /></label><label>순서<input type="number" min="0" max="10000" value={draft[property.id]?.position ?? property.position} disabled={!canManage} onChange={event => setDraft(value => ({ ...value, [property.id]: { ...value[property.id], position: Number(event.target.value) } }))} /></label><label className="workspace-check"><input type="checkbox" checked={draft[property.id]?.archived ?? property.archived} disabled={!canManage} onChange={event => setDraft(value => ({ ...value, [property.id]: { ...value[property.id], archived: event.target.checked } }))} />보관됨</label><button type="button" disabled={!canManage || patch.isPending} onClick={() => patch.mutate({ property, value: draft[property.id] })}>저장</button></div><OptionEditor projectId={projectId} property={property} canManage={canManage} onDirtyChange={dirty => setOptionDirty(current => ({ ...current, [property.id]: dirty }))} onDenied={onDenied} /></div>)}{canManage && <form className="workspace-property-create" onSubmit={event => { event.preventDefault(); if (newName.trim()) create.mutate(); }}><input placeholder="새 속성 이름" value={newName} onChange={event => setNewName(event.target.value)} /><select value={newType} onChange={event => setNewType(event.target.value as ScheduleProperty["type"])}><option value="TEXT">텍스트</option><option value="NUMBER">숫자</option><option value="CHECKBOX">체크박스</option><option value="DATE">날짜</option><option value="SINGLE_SELECT">단일 선택</option></select><button type="submit" disabled={create.isPending || properties.length >= 50}>속성 추가</button></form>}{error && <p role="alert">{error}</p>}<button type="button" onClick={close}>닫기</button></div></Dialog>{discardOpen && <Dialog open title="변경사항 버리기" labelledBy="workspace-discard-property-title" onClose={() => setDiscardOpen(false)}><p>저장하지 않은 속성 또는 옵션 변경이 있습니다.</p><div className="schedule-form-actions"><button type="button" onClick={() => setDiscardOpen(false)}>계속 편집</button><button type="button" className="button-danger" onClick={onClose}>변경사항 버리기</button></div></Dialog>}</>;
}
function OptionEditor({ projectId, property, canManage, onDirtyChange, onDenied }: { projectId: string; property: ScheduleProperty; canManage: boolean; onDirtyChange: (dirty: boolean) => void; onDenied: () => void }) {
    const qc = useQueryClient();
    const [options, setOptions] = useState(property.options);
    const [savedOptions, setSavedOptions] = useState(property.options);
    const [baseVersion, setBaseVersion] = useState(property.rowVersion);
    const [error, setError] = useState<string | null>(null);
    const patch = useMutation({ mutationFn: () => api.workspacePropertyEdit(projectId, property.id, { name: property.name, rowVersion: baseVersion, options: options.map(option => ({ ...(option.id.startsWith("new-") ? {} : { id: option.id }), label: option.label, color: option.color, archived: option.archived })) }), onSuccess: saved => { setOptions(saved.options); setSavedOptions(saved.options); setBaseVersion(saved.rowVersion); onDirtyChange(false); void qc.invalidateQueries({ queryKey: keys.workspace(projectId) }); }, onError: errorValue => { if (isAccessError(errorValue)) onDenied(); setError("옵션 저장이 충돌했거나 거부되었습니다. 초안은 유지됩니다."); } });
    useEffect(() => { onDirtyChange(JSON.stringify(options) !== JSON.stringify(savedOptions)); }, [options, savedOptions]);
    const update = (id: string, next: Partial<PropertyOption>) => setOptions(current => current.map(option => option.id === id ? { ...option, ...next } : option));
    const move = (index: number, direction: -1 | 1) => setOptions(current => { const next = [...current]; const target = index + direction; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next; });
    if (property.type !== "SINGLE_SELECT") return null;
    return <fieldset className="workspace-option-editor"><legend>옵션 · {property.name}</legend>{options.map((option, index) => <div className="workspace-option-row" key={option.id}><label>레이블<input value={option.label} disabled={!canManage} onChange={event => update(option.id, { label: event.target.value })} /></label><label>색상<select value={option.color} disabled={!canManage} onChange={event => update(option.id, { color: event.target.value as PropertyOption["color"] })}><option value="gray">회색</option><option value="blue">파랑</option><option value="green">초록</option><option value="amber">황색</option><option value="red">빨강</option><option value="purple">보라</option><option value="pink">분홍</option><option value="teal">청록</option></select></label><label className="workspace-check"><input type="checkbox" checked={option.archived} disabled={!canManage} onChange={event => update(option.id, { archived: event.target.checked })} />보관됨</label><button type="button" disabled={!canManage || !index} onClick={() => move(index, -1)}>위로</button><button type="button" disabled={!canManage || index === options.length - 1} onClick={() => move(index, 1)}>아래로</button></div>)}{canManage && <button type="button" onClick={() => setOptions(current => [...current, { id: `new-${crypto.randomUUID()}`, label: "새 옵션", color: "gray", archived: false }])}>옵션 추가</button>}<button type="button" disabled={!canManage || patch.isPending} onClick={() => patch.mutate()}>옵션 저장</button>{error && <p role="alert">{error}</p>}</fieldset>;
}

function Records({ projectId, view, properties, page, setPage, calendarView, onCalendarViewChange, calendarAnchor, onCalendarAnchorChange, canEditRecord, onDenied, blocked }: { projectId: string; view: WorkspaceView; properties: ScheduleProperty[]; page: number; setPage: (page: number) => void; calendarView: "month" | "week"; onCalendarViewChange: (view: "month" | "week") => void; calendarAnchor: string; onCalendarAnchorChange: (date: string) => void; canEditRecord: (record: ScheduleWorkspaceRecord) => boolean; onDenied: () => void; blocked: boolean }) {
    const query = useQuery({ queryKey: keys.workspaceQuery(projectId, view.id, page, signature(view.config)), queryFn: () => accessRead(`workspace-query:${projectId}:${view.id}`, () => api.workspaceQuery(projectId, { config: view.config, page, size: 20 })), staleTime: 0, enabled: !blocked && view.config.type !== "CALENDAR" });
    useEffect(() => { if (query.isError && isAccessError(query.error)) onDenied(); }, [onDenied, query.error, query.isError]);
    if (blocked) return null;
    if (view.config.type === "CALENDAR") return <LegacySchedules id={projectId} workspaceConfig={view.config} workspaceProperties={properties} workspaceView={calendarView} onWorkspaceViewChange={onCalendarViewChange} workspaceAnchor={calendarAnchor} onWorkspaceAnchorChange={onCalendarAnchorChange} onWorkspaceDenied={onDenied} embedded />;
    if (query.isPending) return <p role="status">결과를 불러오는 중입니다…</p>;
    if (query.isError) return <div role="alert"><Notice error={query.error} /><p>이 보기의 결과를 불러오지 못했습니다.</p><button type="button" onClick={() => query.refetch()}>다시 시도</button></div>;
    const result = query.data;
    if (!result) return null;
    const fields = view.config.visibleFields.length ? view.config.visibleFields : ["title", "startsAt", "endsAt", "status"] as WorkspaceField[];
    const cards = result.records;
    const groupValue = (record: ScheduleWorkspaceRecord) => view.config.groupBy ? record.values[view.config.groupBy] ?? null : null;
    const groupLabel = (value: unknown) => { const property = properties.find(item => item.id === view.config.groupBy); return optionLabel(value, property); };
    const legendProperty = properties.find(item => item.id === view.config.legendBy);
    return <section className={`workspace-results workspace-results--${view.config.type.toLowerCase()}`} role={view.config.type === "LIST" ? "region" : undefined} aria-label={view.config.type === "LIST" ? "일정 목록" : undefined} aria-live="polite" aria-busy={query.isFetching}>
        {view.config.groupBy && <p className="workspace-group-summary">{result.groups.map(group => `${group.label} (${group.count})`).join(" · ")}</p>}
        {view.config.type === "CARDS" ? <div className="workspace-card-grid">{cards.map((record, index) => <div key={record.schedule.id} className="workspace-card-group">{view.config.groupBy && (index === 0 || groupValue(cards[index - 1]) !== groupValue(record)) && <h3>{groupLabel(groupValue(record))}</h3>}<article className="workspace-card"><Link to={`/projects/${projectId}/schedules/${record.schedule.id}${returnSuffix()}`}><Value field="title" record={record} properties={properties} /></Link>{legendProperty && <Legend value={record.values[legendProperty.id]} property={legendProperty} />}{fields.filter(field => field !== "title").map(field => <div className="workspace-value" key={field}><span>{fieldName(field, properties)}</span><Value field={field} record={record} properties={properties} /></div>)}{canEditRecord(record) && <Link className="button button-secondary" to={`/projects/${projectId}/schedules/${record.schedule.id}/edit${returnSuffix()}`}>수정</Link>}</article></div>)}</div> : <div className="workspace-list-table-wrap"><table className="workspace-list-table"><thead><tr>{fields.map(field => <th key={field} scope="col">{fieldName(field, properties)}</th>)}{legendProperty && <th scope="col">범례</th>}<th scope="col">작업</th></tr></thead><tbody>{cards.map(record => <tr key={record.schedule.id}>{fields.map(field => <td key={field} data-label={fieldName(field, properties)}><Value field={field} record={record} properties={properties} /></td>)}{legendProperty && <td data-label="범례"><Legend value={record.values[legendProperty.id]} property={legendProperty} /></td>}<td data-label="작업"><Link to={`/projects/${projectId}/schedules/${record.schedule.id}${returnSuffix()}`}>열기</Link>{canEditRecord(record) && <> · <Link to={`/projects/${projectId}/schedules/${record.schedule.id}/edit${returnSuffix()}`}>일정 편집</Link><WorkspaceTimeAction projectId={projectId} record={record} onDenied={onDenied} /></>}</td></tr>)}</tbody></table></div>}
        {!cards.length && <p className="schedule-empty">조건에 맞는 일정이 없습니다.</p>}<nav className="schedule-pagination" aria-label="보기 페이지 이동"><span>{result.total}건 · {page + 1}페이지</span><button type="button" disabled={!page || query.isFetching} onClick={() => setPage(page - 1)}>이전</button><button type="button" disabled={!result.hasMore || query.isFetching} onClick={() => setPage(page + 1)}>다음</button></nav>
    </section>;
}

function WorkspaceTimeAction({ projectId, record, onDenied }: { projectId: string; record: ScheduleWorkspaceRecord; onDenied: () => void }) {
    const qc = useQueryClient();
    const project = useProject(projectId);
    const [open, setOpen] = useState(false);
    const [base, setBase] = useState(record.schedule);
    const [start, setStart] = useState(() => utcToLocalDateTime(record.schedule.startsAt, "Asia/Seoul"));
    const [end, setEnd] = useState(() => utcToLocalDateTime(record.schedule.endsAt, "Asia/Seoul"));
    const [error, setError] = useState<string | null>(null);
    const dirty = open && (start !== utcToLocalDateTime(base.startsAt, "Asia/Seoul") || end !== utcToLocalDateTime(base.endsAt, "Asia/Seoul"));
    const guard = useUnsavedChanges(dirty);
    const save = useMutation({ mutationFn: () => api.edit(projectId, base.id, { title: base.title, description: base.description, startsAt: localDateTimeToUtc(start, "Asia/Seoul"), endsAt: localDateTimeToUtc(end, "Asia/Seoul"), rowVersion: base.rowVersion }), onSuccess: async updated => { guard.markSaved(); setBase(updated); setOpen(false); setError(null); await refreshSchedule(qc, projectId, updated.id); }, onError: async value => {
        if (isAccessError(value)) { onDenied(); setError("시간을 변경할 권한이 없어 보호된 작업을 잠갔습니다."); return; }
        if (value instanceof ApiError && value.status === 409) {
            const [latest, membership] = await Promise.allSettled([api.detail(projectId, base.id), project.refetch()]);
            if (latest.status === "fulfilled" && membership.status === "fulfilled" && membership.value.isSuccess && membership.value.data) {
                setBase(latest.value);
                await refreshSchedule(qc, projectId, base.id);
                setError("다른 사용자가 이 일정을 변경했습니다. 초안은 유지되며 다음 저장은 최신 버전을 사용합니다.");
            } else { onDenied(); setError("최신 일정과 역할을 확인하지 못해 보호된 작업을 잠갔습니다."); }
            return;
        }
        setError("시간을 변경하지 못했습니다. 접근 상태를 다시 확인하세요.");
    } });
    const close = () => { if (save.isPending || !guard.confirmDiscard()) return; guard.markSaved(); setStart(utcToLocalDateTime(base.startsAt, "Asia/Seoul")); setEnd(utcToLocalDateTime(base.endsAt, "Asia/Seoul")); setError(null); setOpen(false); };
    const show = () => { const latest = record.schedule; setBase(latest); setStart(utcToLocalDateTime(latest.startsAt, "Asia/Seoul")); setEnd(utcToLocalDateTime(latest.endsAt, "Asia/Seoul")); setError(null); guard.markSaved(); setOpen(true); };
    const submit = (event: React.FormEvent) => { event.preventDefault(); setError(null); try { if (new Date(localDateTimeToUtc(end, "Asia/Seoul")).getTime() <= new Date(localDateTimeToUtc(start, "Asia/Seoul")).getTime()) { setError("종료 시간은 시작 시간보다 뒤여야 합니다."); return; } save.mutate(); } catch (value) { setError(value instanceof Error ? value.message : "시간을 확인하세요."); } };
    return <><button type="button" aria-label={`시간 변경: ${record.schedule.title}`} disabled={save.isPending} onClick={show}>시간 변경</button>{open && <Dialog open title="시간 변경" labelledBy={`workspace-time-${record.schedule.id}`} onClose={close}><form onSubmit={submit}><p>표시 시간대: Asia/Seoul</p><label>시작<input type="datetime-local" value={start} onChange={event => setStart(event.target.value)} /></label><label>종료<input type="datetime-local" value={end} onChange={event => setEnd(event.target.value)} /></label>{error && <p role="alert">{error}</p>}<div className="schedule-form-actions"><button type="button" disabled={save.isPending} onClick={close}>취소</button><button type="submit" className="button-primary" disabled={save.isPending}>변경 저장</button></div></form></Dialog>}</>;
}

export function ScheduleWorkspace({ id }: { id: string }) {
    const project = useProject(id); const me = useMe(); const qc = useQueryClient();
    const workspace = useQuery({ queryKey: keys.workspace(id), queryFn: () => accessRead(`workspace:${id}`, () => api.workspace(id)), enabled: project.isSuccess && !!project.data });
    const initialContext = hashContext();
    const [selectedId, setSelectedId] = useState(initialContext.view); const [page, setPage] = useState(initialContext.page); const [settings, setSettings] = useState(false); const [propertiesOpen, setPropertiesOpen] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false); const [calendarDate, setCalendarDate] = useState(initialContext.date); const [calendarView, setCalendarView] = useState<"month" | "week">(initialContext.mode); const [message, setMessage] = useState<string | null>(null); const [optimisticViews, setOptimisticViews] = useState<WorkspaceView[]>([]);
    const [resultsDenied, setResultsDenied] = useState(false);
    useEffect(() => { normalizeLegacyHash(); }, []);
    const data = workspace.data; const views = useMemo(() => { const serverViews = data?.views.filter(view => !view.archived && view.scope !== "BUILTIN") ?? []; const ids = new Set(serverViews.map(view => view.id)); return [...builtinViews, ...serverViews, ...optimisticViews.filter(view => !ids.has(view.id) && !view.archived)]; }, [data, optimisticViews]);
    const selected = views.find(view => view.id === selectedId) ?? builtinViews[0];
    const role = project.data?.role; const canManage = role === "MANAGER"; const properties = data?.properties ?? [];
    const canCreate = project.data?.role !== "VIEWER" && !resultsDenied;
    const onSaved = (view: WorkspaceView) => { setOptimisticViews(current => [...current.filter(item => item.id !== view.id), view]); setSelectedId(view.id); setPage(0); setSettings(false); setMessage(`저장됨: ${view.name}`); void qc.invalidateQueries({ queryKey: keys.workspace(id) }); setContext(view.id, { page: 0 }); };
    const duplicate = useMutation({ mutationFn: () => api.workspaceViewCreate(id, { name: `${selected.name} 복사본`, scope: canManage && selected.scope === "SHARED" ? "SHARED" : "PERSONAL", config: selected.config }), onSuccess: onSaved, onError: errorValue => { if (isAccessError(errorValue)) setResultsDenied(true); setMessage("보기를 복제하지 못했습니다."); } });
    const archive = useMutation({ mutationFn: () => api.workspaceViewEdit(id, selected.id, { name: selected.name, scope: selected.scope === "SHARED" ? "SHARED" : "PERSONAL", config: selected.config, archived: true, rowVersion: selected.rowVersion }), onSuccess: () => { setOptimisticViews(current => current.filter(view => view.id !== selected.id)); setSelectedId("builtin-calendar"); setMessage("보기를 보관했습니다."); void qc.invalidateQueries({ queryKey: keys.workspace(id) }); }, onError: errorValue => { if (isAccessError(errorValue)) setResultsDenied(true); setMessage("보기를 보관하지 못했습니다."); } });
    useEffect(() => { const sync = () => { const next = hashContext(); setSelectedId(next.view); setPage(next.page); setCalendarDate(next.date); setCalendarView(next.mode); }; window.addEventListener("hashchange", sync); return () => window.removeEventListener("hashchange", sync); }, []);
    useEffect(() => { if (selected.config.type === "CALENDAR" && page !== 0) { setPage(0); setContext(selected.id, { page: 0, date: calendarDate, mode: calendarView }); } }, [calendarDate, calendarView, page, selected.config.type, selected.id]);
    useEffect(() => { if (!workspace.isSuccess) return; if (selectedId !== selected.id) { setSelectedId(selected.id); setPage(0); setMessage("선택한 보기를 사용할 수 없어 기본 캘린더로 이동했습니다."); setContext(selected.id, { page: 0 }); } }, [selected.id, selectedId, workspace.isSuccess]);
    const recheckAccess = async () => {
        const [projectRead, workspaceRead] = await Promise.all([project.refetch(), workspace.refetch()]);
        const range = viewWindow(calendarDate, calendarView, "Asia/Seoul");
        const targetData = projectRead.isSuccess && workspaceRead.isSuccess
            ? await (selected.config.type === "CALENDAR"
                ? readWorkspaceCalendar(id, selected.config, range.from, range.to, true)
                : api.workspaceQuery(id, { config: selected.config, page, size: 20 })).catch(() => null)
            : null;
        if (projectRead.isSuccess && projectRead.data && workspaceRead.isSuccess && workspaceRead.data && targetData) {
            const targetKey = selected.config.type === "CALENDAR"
                ? keys.workspaceQuery(id, "calendar", 0, workspaceCalendarIdentity(selected.config, range.from, range.to))
                : keys.workspaceQuery(id, selected.id, page, signature(selected.config));
            qc.setQueryData(targetKey, targetData);
            setResultsDenied(false);
            setMessage("접근 상태를 다시 확인했습니다.");
        } else {
            setResultsDenied(true);
            setMessage("접근 상태를 확인하지 못해 보호된 작업을 잠갔습니다.");
        }
    };
    if (!project.isSuccess) return <Shell><QueryState query={project} loadingMessage="프로젝트를 불러오는 중입니다." errorMessage="프로젝트를 불러오지 못했습니다." /></Shell>;
    if (!project.data) return <Shell><ProjectMissing onRetry={() => project.refetch()} isFetching={project.isFetching} /></Shell>;
    if (workspace.isError && isAccessError(workspace.error)) return <Shell project={project.data}><h1>일정 작업공간을 불러올 수 없습니다</h1><QueryState query={workspace} /><button type="button" onClick={() => void recheckAccess()}>접근 상태 다시 확인</button></Shell>;
    return <Shell project={project.data}><div className="schedule-screen schedule-workspace"><header className="schedule-heading"><div><p className="eyebrow">{project.data.name}</p><h1>프로젝트 일정</h1><p className="lead">캘린더, 카드, 목록이 같은 일정을 함께 보여줍니다.</p></div><div className="schedule-actions">{canCreate && <Link className="button button-primary" to={`/projects/${id}/schedules/new${returnSuffix()}`}>일정 만들기</Link>}</div></header>
        <nav className="workspace-view-bar" aria-label="일정 보기"><div className="workspace-view-tabs">{views.map(view => <button key={view.id} type="button" aria-label={`${view.name} 보기`} aria-pressed={selected.id === view.id} onClick={() => { setSelectedId(view.id); setPage(0); setContext(view.id, { page: 0 }); }}>{view.name}{view.scope === "PERSONAL" ? " · 개인" : view.scope === "SHARED" ? " · 공유" : ""}</button>)}</div><div className="workspace-view-actions"><button type="button" disabled={project.data.role === "VIEWER" || resultsDenied} onClick={() => setSettings(true)}>보기 설정</button>{selected.scope !== "BUILTIN" && <><button type="button" onClick={() => duplicate.mutate()} disabled={duplicate.isPending || project.data.role === "VIEWER" || resultsDenied}>복제</button>{(selected.scope === "PERSONAL" || canManage) && <button type="button" onClick={() => setArchiveOpen(true)} disabled={archive.isPending || resultsDenied}>보관</button>}</>}<button type="button" onClick={() => setPropertiesOpen(true)} disabled={!canManage || resultsDenied}>속성</button></div></nav>
        <div className="workspace-config-summary"><span>{selected.config.filters.length ? `필터 ${selected.config.filters.length}개` : "필터 없음"}</span><span>표시 필드 {selected.config.visibleFields.length}개</span><span>{selected.config.groupBy ? `그룹: ${fieldName(`property:${selected.config.groupBy}`, properties)}` : "그룹 없음"}</span></div>
        {message && <p role="status" className="schedule-success">{message}</p>}{workspace.isError && <div role="alert"><Notice error={workspace.error} /><p>작업공간 설정을 불러오지 못했습니다.</p><button type="button" onClick={() => void recheckAccess()}>다시 시도</button></div>}{workspace.isPending && <p role="status">작업공간 설정을 불러오는 중입니다…</p>}{resultsDenied && <div role="status"><p>일정 접근 권한을 다시 확인해야 합니다. 금지된 작업은 비활성화했습니다.</p><button type="button" onClick={() => void recheckAccess()}>접근 상태 다시 확인</button></div>}{data && <Records projectId={id} view={selected} properties={properties} page={page} setPage={next => { setPage(next); setContext(selected.id, { page: next }); }} calendarView={calendarView} onCalendarViewChange={next => { setCalendarView(next); setPage(0); setContext(selected.id, { page: 0, mode: next }); }} calendarAnchor={calendarDate} onCalendarAnchorChange={next => { setCalendarDate(next); setPage(0); setContext(selected.id, { page: 0, date: next }); }} canEditRecord={record => !resultsDenied && record.schedule.status !== "CANCELLED" && (canManage || (role === "MEMBER" && record.schedule.createdBy === me.data?.id))} onDenied={() => setResultsDenied(true)} blocked={resultsDenied} />}
         {settings && <ViewSettings projectId={id} current={selected} properties={properties} canManage={canManage} blocked={resultsDenied} onSaved={onSaved} onClose={() => setSettings(false)} onReload={() => { setSettings(false); void workspace.refetch(); }} onDenied={() => setResultsDenied(true)} />}{propertiesOpen && <PropertiesDialog projectId={id} properties={properties} canManage={canManage && !resultsDenied} onClose={() => setPropertiesOpen(false)} onDenied={() => setResultsDenied(true)} />}{archiveOpen && <Dialog open title="보기 보관" labelledBy="workspace-archive-title" onClose={() => setArchiveOpen(false)}><p>이 보기를 보관하시겠습니까?</p><div className="schedule-form-actions"><button type="button" onClick={() => setArchiveOpen(false)}>취소</button><button type="button" className="button-danger" disabled={archive.isPending || resultsDenied} onClick={() => { setArchiveOpen(false); archive.mutate(); }}>보기 보관</button></div></Dialog>}</div></Shell>;
}

function DashboardCard({ projectId, record, properties, fields, legendProperty, canEdit, onDenied }: { projectId: string; record: ScheduleWorkspaceRecord; properties: ScheduleProperty[]; fields: WorkspaceField[]; legendProperty?: ScheduleProperty; canEdit: boolean; onDenied: () => void }) {
    const qc = useQueryClient();
    const [editing, setEditing] = useState(false);
    const [draft, setDraft] = useState(record.values);
    const [baselineValues, setBaselineValues] = useState(record.values);
    const [baseVersion, setBaseVersion] = useState(record.schedule.rowVersion);
    const [message, setMessage] = useState<string | null>(null);
    const [conflict, setConflict] = useState(false);
    const dirty = JSON.stringify(draft) !== JSON.stringify(baselineValues);
    useEffect(() => { if (!dirty) { setDraft(record.values); setBaselineValues(record.values); setBaseVersion(record.schedule.rowVersion); } }, [dirty, record.schedule.rowVersion, record.values]);
    const save = useMutation({ mutationFn: () => { if (!canEdit) throw new Error("접근 상태를 다시 확인해야 합니다."); return api.workspaceValuesEdit(projectId, record.schedule.id, { rowVersion: baseVersion, values: draft }); }, onSuccess: saved => { setDraft(saved.values); setBaselineValues(saved.values); setBaseVersion(saved.schedule.rowVersion); setConflict(false); setEditing(false); setMessage("속성을 저장했습니다."); void qc.invalidateQueries({ queryKey: ["schedule-workspace-query", projectId] }); }, onError: error => { if (isAccessError(error)) { onDenied(); setMessage("속성을 저장할 권한이 없어 보호된 작업을 잠갔습니다."); } else if (error instanceof ApiError && error.status === 409) { setConflict(true); void qc.invalidateQueries({ queryKey: ["schedule-workspace-query", projectId] }); setMessage("다른 변경과 충돌했습니다. 입력한 초안을 유지했습니다. 최신 값으로 다시 불러오거나 취소하세요."); } else setMessage("속성을 저장하지 못했습니다."); } });
    const editableProperties = properties.filter(property => !property.archived && fields.includes(`property:${property.id}`));
    return <article className="workspace-card"><Link to={`/projects/${projectId}/schedules/${record.schedule.id}`}><strong>{record.schedule.title}</strong></Link>{legendProperty && <Legend value={record.values[legendProperty.id]} property={legendProperty} />}{fields.filter(field => field !== "title").map(field => <div className="workspace-value" key={field}><span>{fieldName(field, properties)}</span><Value field={field} record={{ ...record, values: draft }} properties={properties} /></div>)}{editing && editableProperties.map(property => <PropertyInputForDashboard key={property.id} property={property} value={draft[property.id]} onChange={value => setDraft(current => ({ ...current, [property.id]: value }))} />)}{message && <p role={message.includes("못") || message.includes("충돌") ? "alert" : "status"}>{message}</p>}{conflict && editing && <button type="button" disabled={!canEdit} onClick={() => { setDraft(record.values); setBaselineValues(record.values); setBaseVersion(record.schedule.rowVersion); setConflict(false); setMessage("최신 값을 불러왔습니다."); }}>최신 값 다시 불러오기</button>}<div className="schedule-form-actions">{canEdit && !editing && <button type="button" onClick={() => { setMessage(null); setEditing(true); }}>속성 바로 수정</button>}{editing && <><button type="button" onClick={() => { setDraft(record.values); setBaselineValues(record.values); setBaseVersion(record.schedule.rowVersion); setConflict(false); setEditing(false); setMessage(null); }}>취소</button><button type="button" disabled={!canEdit || save.isPending} onClick={() => save.mutate()}>속성 저장</button></>} {canEdit && <Link className="button button-secondary" to={`/projects/${projectId}/schedules/${record.schedule.id}/edit`}>전체 수정</Link>}</div></article>;
}

function PropertyInputForDashboard({ property, value, onChange }: { property: ScheduleProperty; value: string | number | boolean | null | undefined; onChange: (value: string | number | boolean | null) => void }) {
    if (property.type === "CHECKBOX") return <label>{property.name}<select value={value == null ? "" : value ? "true" : "false"} onChange={event => onChange(event.target.value === "" ? null : event.target.value === "true")}><option value="">설정 안 함</option><option value="true">예</option><option value="false">아니오</option></select></label>;
    if (property.type === "SINGLE_SELECT") return <label>{property.name}<select value={value == null ? "" : String(value)} onChange={event => onChange(event.target.value || null)}><option value="">설정 안 함</option>{property.options.filter(option => !option.archived || option.id === value).map(option => <option key={option.id} value={option.id}>{option.label}{option.archived ? " · 보관됨" : ""}</option>)}</select></label>;
    return <label>{property.name}<input type={property.type === "NUMBER" ? "number" : property.type === "DATE" ? "date" : "text"} step={property.type === "NUMBER" ? "any" : undefined} value={value == null ? "" : String(value)} onChange={event => onChange(event.target.value === "" ? null : property.type === "NUMBER" ? Number(event.target.value) : event.target.value)} /></label>;
}

export function ScheduleDashboardSection({ id }: { id: string }) {
    const project = useProject(id); const me = useMe(); const qc = useQueryClient(); const workspace = useQuery({ queryKey: keys.workspace(id), queryFn: () => accessRead(`workspace:${id}`, () => api.workspace(id)), enabled: project.isSuccess && !!project.data }); const [selection, setSelection] = useState<string | null>(null); const [page, setPage] = useState(0); const [message, setMessage] = useState<string | null>(null); const [denied, setDenied] = useState(false);
    useEffect(() => { if (workspace.isError && isAccessError(workspace.error)) setDenied(true); }, [workspace.error, workspace.isError]);
    const requestedId = selection ?? workspace.data?.dashboardViewId ?? "builtin-cards";
    const selected = [...builtinViews, ...(workspace.data?.views ?? []).filter(view => view.scope === "SHARED" && !view.archived)].find(view => view.id === requestedId);
    const dashboard = useMutation({ mutationFn: (viewId: string | null) => api.workspaceDashboard(id, { viewId, rowVersion: workspace.data?.dashboardRowVersion ?? 0 }), onSuccess: result => { setSelection(result.dashboardViewId); setMessage("대시보드 보기를 저장했습니다."); void qc.invalidateQueries({ queryKey: keys.workspace(id) }); }, onError: error => { if (isAccessError(error)) setDenied(true); setSelection(null); setMessage("대시보드 보기를 저장하지 못했습니다."); } });
    const query = useQuery({ queryKey: keys.workspaceQuery(id, selected?.id ?? "unavailable", page, selected ? `${signature(selected.config)}|size:20|dashboard` : ""), queryFn: () => accessRead(`workspace-query:${id}:${selected!.id}:${page}:dashboard`, () => api.workspaceQuery(id, { config: { ...selected!.config, type: "CARDS" }, page, size: 20 })), enabled: workspace.isSuccess && !!selected });
    useEffect(() => { if (query.isError && isAccessError(query.error)) setDenied(true); }, [query.error, query.isError]);
    if (!workspace.isSuccess) return null;
    if (!selected) return <section className="schedule-section workspace-dashboard-section"><p role="alert">선택한 공유 보기를 더 이상 사용할 수 없습니다.</p>{project.data?.role === "MANAGER" && <button type="button" disabled={denied} onClick={() => dashboard.mutate(null)}>기본 카드로 재설정</button>}</section>;
    const fields = selected.config.visibleFields.length ? selected.config.visibleFields : ["title", "startsAt", "endsAt", "status"] as WorkspaceField[];
    const legendProperty = workspace.data.properties.find(property => property.id === selected.config.legendBy);
    const retryDashboardAccess = async () => { const [projectRead, workspaceRead, targetRead] = await Promise.all([project.refetch(), workspace.refetch(), query.refetch()]); if (projectRead.isSuccess && projectRead.data && workspaceRead.isSuccess && workspaceRead.data && targetRead.isSuccess && targetRead.data) { setDenied(false); setMessage("접근 상태를 다시 확인했습니다."); } else { setDenied(true); setMessage("접근 상태를 확인하지 못해 보호된 대시보드 작업을 잠갔습니다."); } };
    return <section className="schedule-section workspace-dashboard-section" aria-labelledby="workspace-dashboard-title"><div className="section-heading"><div><p className="eyebrow">일정 보기</p><h2 id="workspace-dashboard-title">선택한 일정 카드</h2></div>{project.data?.role === "MANAGER" && <><select aria-label="대시보드 일정 보기" value={requestedId} disabled={dashboard.isPending || denied} onChange={event => { setPage(0); dashboard.mutate(event.target.value); }}>{[...builtinViews.filter(view => view.id !== "builtin-calendar"), ...workspace.data.views.filter(view => view.scope === "SHARED" && !view.archived)].map(view => <option key={view.id} value={view.id}>{view.name}</option>)}</select><button type="button" disabled={dashboard.isPending || denied} onClick={() => dashboard.mutate(null)}>재설정</button></>}</div>{denied && <p role="alert">대시보드 접근 권한을 다시 확인해야 합니다. <button type="button" onClick={() => void retryDashboardAccess()}>접근 상태 다시 확인</button></p>}{message && <p role="status">{message}</p>}{!denied && query.data && selected.config.groupBy && <p className="workspace-group-summary">{query.data.groups.map(group => `${group.label} (${group.count})`).join(" · ")}</p>}{query.isError && <p role="alert">카드를 불러오지 못했습니다. <button type="button" onClick={() => query.refetch()}>다시 시도</button></p>}{!denied && query.data?.records.length ? <div className="workspace-dashboard-cards">{query.data.records.map(record => <DashboardCard key={record.schedule.id} projectId={id} record={record} properties={workspace.data.properties} fields={fields} legendProperty={legendProperty} canEdit={record.schedule.status !== "CANCELLED" && (project.data?.role === "MANAGER" || (project.data?.role === "MEMBER" && record.schedule.createdBy === me.data?.id))} onDenied={() => setDenied(true)} />)}</div> : !denied && query.isSuccess && <p className="schedule-empty">표시할 일정이 없습니다.</p>}{!denied && query.data && <nav className="schedule-pagination" aria-label="대시보드 카드 페이지"><span>{query.data.total}건</span><button type="button" disabled={!page} onClick={() => setPage(page - 1)}>이전</button><button type="button" disabled={!query.data.hasMore} onClick={() => setPage(page + 1)}>다음</button></nav>}</section>;
}
