import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, test, vi } from "vitest";
import App from "./App";

const project = { id: "p1", groupId: "g1", name: "Planning", role: "MANAGER" };
const schedule = { id: "s1", projectId: "p1", title: "Design review", status: "CONFIRMED", rowVersion: 3, businessRevision: 4, startsAt: "2026-09-10T01:00:00Z", endsAt: "2026-09-10T02:00:00Z", createdBy: "u1", participants: [{ memberUserId: "u1", acknowledged: false }], changes: [{ businessRevision: 4, type: "CONFIRMED", changedBy: "u1", createdAt: "2026-09-09T00:00:00Z" }] };
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
function api(overrides: { configuration?: Record<string, unknown>; unauthenticated?: boolean } = {}) {
  const fetch = vi.fn(async (input: RequestInfo | URL) => { const path = String(input);
    if (path === "/api/v1/system/configuration") return response({ login: "READY", calendar: "READY", loginUrl: "/oauth2/authorization/google", ...overrides.configuration });
    if (path === "/api/v1/me") return overrides.unauthenticated ? response({ code: "UNAUTHENTICATED" }, 401) : response({ id: "u1", authorities: ["ROLE_USER"] }); if (path.startsWith("/api/v1/csrf")) return response({ headerName: "X-CSRF-TOKEN", token: "csrf" });
    if (path.startsWith("/api/v1/projects/p1/dashboard")) return response({ projectId: "p1", memberCount: 2, scheduleCount: 1, pendingAcknowledgementCount: 1, calendarRiskCount: 1, upcomingSchedules: [schedule], actionQueue: [schedule] });
    if (path.startsWith("/api/v1/projects/p1/schedules/s1/calendar")) return response({ scheduleId: "s1", status: "SYNCED", businessRevision: 4 }); if (path.startsWith("/api/v1/projects/p1/schedules/s1")) return response(schedule); if (path.startsWith("/api/v1/projects/p1/schedules")) return response([schedule]);
    if (path.startsWith("/api/v1/projects/p1/members")) return response([{ userId: "u1", role: "MANAGER" }, { userId: "u2", role: "MEMBER" }]); if (path.startsWith("/api/v1/projects")) return response([project]);
    if (path.startsWith("/api/v1/notifications")) return response([{ id: "n1", type: "SCHEDULE_CONFIRMED", link: "#/projects/p1/schedules/s1", readAt: null, createdAt: "2026-09-09T00:00:00Z" }]);
    if (path.startsWith("/api/v1/calendar/connection")) return response({ status: "NOT_CONNECTED", configurationRequired: false }); if (path.startsWith("/api/v1/calendar/reconnect")) return response({ status: "PENDING", configurationRequired: false });
    if (path.startsWith("/api/v1/invitations/t1")) return response({ id: "i1", projectId: "p1", email: "member@example.test", token: "t1", status: "PENDING", expiresAt: "2026-10-01T00:00:00Z" }); return response({ code: "NOT_FOUND", traceId: "trace" }, 404); });
  vi.stubGlobal("fetch", fetch); return fetch;
}
afterEach(() => { vi.unstubAllGlobals(); window.location.hash = ""; });
test("shows configuration required instead of a fake login", async () => { api({ configuration: { login: "CONFIGURATION_REQUIRED", calendar: "CONFIGURATION_REQUIRED", loginUrl: null } }); render(<App />); expect(await screen.findByText("Google 로그인이 구성되지 않았습니다.")).toBeInTheDocument(); expect(screen.queryByRole("link", { name: /Google/ })).not.toBeInTheDocument(); });
test("shows Google login when configuration is ready", async () => { api({ unauthenticated: true }); render(<App />); expect(await screen.findByRole("link", { name: "Google로 로그인" })).toHaveAttribute("href", "/oauth2/authorization/google"); });
test("shows invitation mismatch and posts accept or reject with CSRF", async () => { window.location.hash = "#/invitations/t1"; const fetch = api(); const user = userEvent.setup(); render(<App />); await screen.findByText("member@example.test"); expect(screen.getByText("현재 로그인 계정의 이메일과 초대 이메일이 일치하는지 확인하세요.")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "초대 수락" })); await waitFor(() => expect(fetch).toHaveBeenCalledWith("/api/v1/invitations/t1/accept", expect.objectContaining({ method: "POST", headers: expect.objectContaining({ "X-CSRF-TOKEN": "csrf" }) }))); await user.click(screen.getByRole("button", { name: "초대 거절" })); await waitFor(() => expect(fetch).toHaveBeenCalledWith("/api/v1/invitations/t1/reject", expect.objectContaining({ method: "POST" }))); });
test("renders dashboard radar and action queue", async () => { api(); render(<App />); await userEvent.setup().click(await screen.findByRole("link", { name: "Planning" })); expect(await screen.findByText("일정 1")).toBeInTheDocument(); expect(screen.getByText("확인 대기 1")).toBeInTheDocument(); expect(screen.getByText("Calendar 위험 1")).toBeInTheDocument(); });
test("switches between compressed month and event week views", async () => { api(); window.location.hash = "#/projects/p1/schedules"; render(<App />); const user = userEvent.setup(); expect(await screen.findByText("월간 신호 보기")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "주간 보기" })); expect(screen.getByText("주간 실제 일정")).toBeInTheDocument(); expect(screen.getByText("Design review")).toBeInTheDocument(); });
test("filters schedules across text, lifecycle, and acknowledgement independently", async () => { api(); window.location.hash = "#/projects/p1/schedules"; render(<App />); const user = userEvent.setup(); await screen.findByText("Design review"); await user.type(screen.getByLabelText("검색"), "other"); expect(screen.queryByText("Design review")).not.toBeInTheDocument(); await user.clear(screen.getByLabelText("검색")); await user.selectOptions(screen.getByLabelText("상태"), "CANCELLED"); expect(screen.queryByText("Design review")).not.toBeInTheDocument(); await user.selectOptions(screen.getByLabelText("상태"), "ALL"); await user.selectOptions(screen.getByLabelText("확인"), "PENDING"); expect(screen.getByText("Design review")).toBeInTheDocument(); });
test("creates and edits with UTC timestamps, rowVersion, and distinct attendee values", async () => { window.location.hash = "#/projects/p1/schedules/new"; const fetch = api(); render(<App />); const user = userEvent.setup(); await screen.findByLabelText("제목"); await user.type(screen.getByLabelText("제목"), "Planning"); await user.type(screen.getByLabelText("외부 참석자 이메일"), "outside@example.test"); await user.click(screen.getByRole("button", { name: "일정 저장" })); await waitFor(() => expect(fetch).toHaveBeenCalledWith("/api/v1/projects/p1/schedules", expect.objectContaining({ method: "POST", body: expect.stringContaining("outside@example.test") }))); });
test("shows history and sends acknowledgement for the current business revision", async () => { window.location.hash = "#/projects/p1/schedules/s1"; const fetch = api(); render(<App />); const user = userEvent.setup(); await screen.findAllByText((text) => text.includes("CONFIRMED")); expect(screen.getByText("변경 이력")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "변경 확인" })); await waitFor(() => expect(fetch).toHaveBeenCalledWith("/api/v1/projects/p1/schedules/s1/acknowledge", expect.objectContaining({ method: "POST", body: "{\"expectedBusinessRevision\":4}" }))); });
test("marks notifications read with a CSRF mutation", async () => { window.location.hash = "#/notifications"; const fetch = api(); render(<App />); const user = userEvent.setup(); await screen.findByText("SCHEDULE_CONFIRMED"); await user.click(screen.getByRole("button", { name: "읽음 처리" })); await waitFor(() => expect(fetch).toHaveBeenCalledWith("/api/v1/notifications/n1/read", expect.objectContaining({ method: "POST" }))); });
test("allows Manager role changes", async () => { window.location.hash = "#/projects/p1/members"; const fetch = api(); render(<App />); const user = userEvent.setup(); await screen.findByText("u2"); await user.selectOptions(screen.getByLabelText("u2 역할"), "VIEWER"); await waitFor(() => expect(fetch).toHaveBeenCalledWith("/api/v1/projects/p1/members/u2", expect.objectContaining({ method: "PATCH", body: "{\"role\":\"VIEWER\"}" }))); });
test("renders Calendar state and asks reconnect with CSRF", async () => { window.location.hash = "#/calendar"; const fetch = api(); render(<App />); const user = userEvent.setup(); await screen.findByText("NOT_CONNECTED"); await user.click(screen.getByRole("button", { name: "Calendar 다시 연결" })); await waitFor(() => expect(fetch).toHaveBeenCalledWith("/api/v1/calendar/reconnect", expect.objectContaining({ method: "POST" }))); });
