import { render, screen, waitFor, within, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, test, vi } from "vitest";
import App from "./App";
import { http, json, project, schedule, invitation } from "./test/http";
afterEach(() => { vi.unstubAllGlobals(); window.location.hash = ""; sessionStorage.clear(); });
const calendarLabels: Record<string, string> = { REAUTH_REQUIRED: "연결 확인 필요", FAILED: "동기화 실패", PENDING: "동기화 중", SYNCED: "동기화 완료", NOT_CONNECTED: "연결되지 않음" };
const calendarLabel = (status: string) => calendarLabels[status] ?? "Calendar 확인 필요";
const detailCalendarLabel = (status: string) => status === "FAILED" || status === "REAUTH_REQUIRED" ? "연결 확인 필요" : calendarLabel(status);
const mount = (path = "/") => { window.location.hash = `#${path}`; render(<App />); return userEvent.setup(); };
const fill = async (user: ReturnType<typeof userEvent.setup>, zone = "Asia/Seoul", start = "2090-09-10T10:00", end = "2090-09-10T11:00") => {
  await user.type(await screen.findByLabelText("제목"), "Planning");
  fireEvent.change(screen.getByLabelText("시간대"), { target: { value: zone } });
  fireEvent.change(screen.getByLabelText("시작"), { target: { value: start } });
  fireEvent.change(screen.getByLabelText("종료"), { target: { value: end } });
};
test("P04 exact create body converts IANA time and separates internal IDs from external emails", async () => {
  const server = http(); server.on("POST", "/api/v1/projects/p1/schedules", body => { expect(body).toEqual({ title: "Planning", description: "Agenda", startsAt: "2090-09-10T01:00:00.000Z", endsAt: "2090-09-10T02:00:00.000Z", memberParticipantIds: ["u2"], externalAttendeeEmails: ["outside@example.test"] }); return json(schedule); });
  const user = mount("/projects/p1/schedules/new"); await fill(user); await user.type(screen.getByLabelText("설명"), "Agenda"); await user.click(screen.getAllByRole("checkbox")[1]); await user.type(screen.getByLabelText("외부 참석자 이메일"), "outside@example.test"); await user.click(screen.getByRole("button", { name: "일정 저장" })); await screen.findByRole("heading", { name: "Design review" }); expect(server.calls.filter(c => c.method === "POST" && c.url.endsWith("/schedules"))).toHaveLength(1);
});
test.each([
  ["America/", "2090-09-10T10:00", "2090-09-10T11:00", "지원하지 않는"],
  ["America/New_York", "2026-03-08T02:30", "2026-03-08T04:00", "존재하지 않는"],
  ["America/New_York", "2026-11-01T01:30", "2026-11-01T03:00", "모호한"],
  ["Europe/Berlin", "2026-10-25T02:30", "2026-10-25T04:00", "모호한"],
  ["Asia/Seoul", "2090-09-10T11:00", "2090-09-10T10:00", "종료 시간"],
])("P04 rejects invalid zone/gap/overlap/end: %s %s", async (zone, start, end, error) => {
  const server = http(); const user = mount("/projects/p1/schedules/new"); await fill(user, zone, start, end); await user.click(screen.getByRole("button", { name: "일정 저장" })); expect(await screen.findByRole("alert")).toHaveTextContent(error); expect(server.calls.some(c => c.method === "POST")).toBe(false);
});
test("P04 untouched edit preserves seconds and milliseconds", async () => {
  const server = http(); server.on("GET", "/api/v1/projects/p1/schedules/s1", () => json({ ...schedule, startsAt: "2090-09-10T01:00:32.123Z", endsAt: "2090-09-10T02:00:45.567Z" }));
  server.on("PATCH", "/api/v1/projects/p1/schedules/s1", body => { expect(body.startsAt).toBe("2090-09-10T01:00:32.123Z"); expect(body.endsAt).toBe("2090-09-10T02:00:45.567Z"); return json(schedule); });
  const user = mount("/projects/p1/schedules/s1/edit"); await user.click(await screen.findByRole("button", { name: "일정 저장" })); await waitFor(() => expect(server.calls.some(c => c.method === "PATCH")).toBe(true)); expect(screen.queryByRole("alert")).not.toBeInTheDocument();
});
test.each([
  ["MANAGER", "u2", "CONFIRMED", true, true],
  ["MEMBER", "u1", "CONFIRMED", true, true],
  ["MEMBER", "u2", "CONFIRMED", false, true],
  ["VIEWER", "u1", "CONFIRMED", false, false],
  ["MANAGER", "u1", "CANCELLED", false, true],
])("P05 capability role %s creator %s lifecycle %s", async (role, creator, status, edit, ack) => {
  const server = http(); server.on("GET", "/api/v1/projects", () => json([{ ...project, role }])); server.on("GET", "/api/v1/projects/p1/schedules/s1", () => json({ ...schedule, createdBy: creator, status }));
  mount("/projects/p1/schedules/s1"); await screen.findByRole("heading", { name: "Design review" }); expect(!!screen.queryByRole("link", { name: "일정 수정" })).toBe(edit); expect(!!screen.queryByRole("button", { name: "변경 확인" })).toBe(ack);
});
test.each([
  { revision: 0, participants: [{ memberUserId: "u1", acknowledged: false }] },
  { revision: 4, participants: [{ memberUserId: "u1", acknowledged: true }] },
  { revision: 4, participants: [{ externalEmail: "guest@example.test", acknowledged: false }] },
  { revision: 4, participants: [{ memberUserId: "u2", acknowledged: false }] }
])("P05 does not expose ACK for draft/nonparticipant/already acknowledged: $revision $participants", async value => {
  const server = http(); server.on("GET", "/api/v1/projects/p1/schedules/s1", () => json({ ...schedule, businessRevision: value.revision, participants: value.participants })); mount("/projects/p1/schedules/s1"); await screen.findByRole("heading", { name: "Design review" }); expect(screen.queryByRole("button", { name: "변경 확인" })).not.toBeInTheDocument();
});
test.each([
  ["cancel", "일정 취소", { rowVersion: 3 }],
  ["acknowledge", "변경 확인", { expectedBusinessRevision: 4 }]
])("P05 %s exact body and authoritative refetch", async (action, label, expected) => {
  const server = http(); let done = false; server.on("GET", "/api/v1/projects/p1/schedules/s1", () => json({ ...schedule, status: done && action === "cancel" ? "CANCELLED" : "CONFIRMED", participants: done ? [{ memberUserId: "u1", acknowledged: true }] : schedule.participants }));
  server.on("POST", `/api/v1/projects/p1/schedules/s1/${action}`, body => { expect(body).toEqual(expected); done = true; return json(schedule); }); const user = mount("/projects/p1/schedules/s1"); await user.click(await screen.findByRole("button", { name: label as string })); await screen.findByText("요청을 처리했습니다."); expect(server.calls.filter(c => c.method === "GET" && c.url.includes("s1?historyLimit")).length).toBeGreaterThan(1); expect(screen.queryByRole("button", { name: label as string })).not.toBeInTheDocument();
});
test("P05 failed transient Manager projection retries without body and invalidates projection/connection", async () => {
  const server = http(); let done = false; server.on("GET", "/api/v1/projects/p1/schedules/s1/calendar", () => json({ scheduleId: "s1", status: done ? "SYNCED" : "FAILED", retryClassification: done ? null : "TRANSIENT", businessRevision: 4 })); server.on("POST", "/api/v1/projects/p1/schedules/s1/calendar/retry", body => { expect(body).toBeUndefined(); done = true; return json({ scheduleId: "s1", status: "SYNCED", businessRevision: 4 }); }); const user = mount("/projects/p1/schedules/s1"); await user.click(await screen.findByRole("button", { name: "Calendar 동기화 다시 시도" })); await screen.findByText("동기화 완료"); expect(server.calls.filter(c => c.method === "GET" && c.url === "/api/v1/calendar/connection").length).toBeGreaterThan(1); expect(screen.queryByRole("button", { name: "Calendar 동기화 다시 시도" })).not.toBeInTheDocument();
});
test.each([["MEMBER", "FAILED", "TRANSIENT"], ["MANAGER", "FAILED", "PERMANENT"], ["MANAGER", "PENDING", "TRANSIENT"]])("P05 retry gate %s %s %s", async (role, status, classification) => { const server = http(); server.on("GET", "/api/v1/projects", () => json([{ ...project, role }])); server.on("GET", "/api/v1/projects/p1/schedules/s1/calendar", () => json({ scheduleId: "s1", status, retryClassification: classification, businessRevision: 4 })); mount("/projects/p1/schedules/s1"); await screen.findByText(detailCalendarLabel(status)); expect(screen.queryByRole("button", { name: "Calendar 동기화 다시 시도" })).not.toBeInTheDocument(); });
test("P03 schedule listing has no Calendar connection or projection dependency", async () => { const server = http(); mount("/projects/p1/schedules"); expect(await screen.findByRole("grid", { name: "월간 일정" })).toBeInTheDocument(); expect(screen.queryByLabelText("Calendar 상태")).not.toBeInTheDocument(); expect(screen.queryByText("동기화 완료")).not.toBeInTheDocument(); expect(server.calls.some(c => c.url.includes("/calendar"))).toBe(false); });
test("P03 independent text/date/lifecycle/mine filters and draft NOT_REQUIRED", async () => {
  const server = http(); server.on("GET", "/api/v1/projects/p1/schedules", () => json([{ ...schedule, businessRevision: 0, status: "DRAFT", createdBy: "u2" }])); const user = mount("/projects/p1/schedules"); await screen.findByText("확인 대상 아님"); await user.click(screen.getByText("상세 필터")); await user.type(screen.getByLabelText("검색"), "missing"); expect(screen.queryByRole("link", { name: /Design review/ })).not.toBeInTheDocument(); await user.clear(screen.getByLabelText("검색"));
  await user.selectOptions(screen.getByLabelText("상태"), "CONFIRMED"); expect(screen.queryAllByRole("link", { name: /Design review/ })).toHaveLength(0); await user.selectOptions(screen.getByLabelText("상태"), "ALL");
  await user.click(screen.getByLabelText("내가 만든 일정")); expect(screen.queryAllByRole("link", { name: /Design review/ })).toHaveLength(0); await user.click(screen.getByLabelText("내가 만든 일정"));
  fireEvent.change(screen.getByLabelText("날짜 이후"), { target: { value: "2090-09-11" } }); expect(screen.queryAllByRole("link", { name: /Design review/ })).toHaveLength(0); fireEvent.change(screen.getByLabelText("날짜 이후"), { target: { value: "" } });
  fireEvent.change(screen.getByLabelText("날짜 이전"), { target: { value: "2090-09-09" } }); expect(screen.queryAllByRole("link", { name: /Design review/ })).toHaveLength(0); fireEvent.change(screen.getByLabelText("날짜 이전"), { target: { value: "" } }); expect((await screen.findAllByRole("link", { name: /Design review/ })).length).toBeGreaterThan(0);
});
test("P03 bounded 20-schedule page has no projection fanout and keeps next-page URL", async () => {
  const server = http(); server.on("GET", "/api/v1/projects/p1/schedules", (_, url) => json(url.searchParams.get("page") === "0" ? Array.from({ length: 20 }, (_, i) => ({ ...schedule, id: "s" + i })) : [])); const user = mount("/projects/p1/schedules"); await screen.findByRole("grid", { name: "월간 일정" }); expect(server.calls.some(c => c.url.includes("/calendar"))).toBe(false); await user.click(screen.getByRole("button", { name: "다음 일정 페이지" })); await screen.findAllByText("조건에 맞는 일정이 없습니다."); expect(server.calls.some(c => c.url.includes("schedules?page=1&limit=20&from="))).toBe(true);
});
test.each([
  ["/", "/api/v1/projects", "아직 프로젝트가 없습니다"],
  ["/notifications", "/api/v1/notifications", "새 알림이 없습니다"],
  ["/projects/p1/members", "/api/v1/projects/p1/members", "구성원"],
  ["/projects/p1/schedules", "/api/v1/projects/p1/schedules", "조건에 맞는 일정이 없습니다."]
])("manual retry plus empty state %s", async (route, endpoint, empty) => { const server = http(); let failed = true; server.on("GET", endpoint, () => failed ? json({ code: "TEMPORARY" }, 500) : json([])); const user = mount(route); await screen.findByText("TEMPORARY"); failed = false; await user.click(screen.getByRole("button", { name: "다시 시도" })); expect((await screen.findAllByText(empty)).length).toBeGreaterThan(0); });
test.each([
  ["/", "/api/v1/system/configuration"], ["/", "/api/v1/me"], ["/projects/p1", "/api/v1/projects"],
  ["/projects/p1", "/api/v1/projects/p1/dashboard"], ["/projects/p1/schedules/s1", "/api/v1/projects/p1/schedules/s1"],
  ["/invitations/t1", "/api/v1/invitations/t1"], ["/calendar", "/api/v1/calendar/connection"]
])("required dependency retry succeeds %s %s", async (route, endpoint) => { const server = http(); server.on("GET", endpoint, () => json({ code: "TEMPORARY" }, 500)); const user = mount(route); await screen.findByText("TEMPORARY"); const prior = server.calls.length; await user.click(screen.getByRole("button", { name: "다시 시도" })); await waitFor(() => expect(server.calls.length).toBeGreaterThan(prior)); });
test("P01 empty project offers onboarding actions", async () => { const server = http(); server.on("GET", "/api/v1/projects/p1/dashboard", () => json({ projectId: "p1", memberCount: 0, scheduleCount: 0, pendingAcknowledgementCount: 0, calendarRiskCount: 0, upcomingSchedules: [], actionQueue: [] })); mount("/projects/p1"); await screen.findByText("구성원을 초대하고 첫 일정을 만들어보세요."); expect(screen.getByRole("link", { name: "구성원 초대" })).toBeInTheDocument(); expect(screen.getByRole("link", { name: "일정 만들기" })).toBeInTheDocument(); });
test("restores valid saved login continuation", async () => { http(); sessionStorage.setItem("ai-erp.invitation", "#/invitations/t1"); mount(); expect(await screen.findByRole("heading", { name: "프로젝트 초대" })).toBeInTheDocument(); expect(sessionStorage.getItem("ai-erp.invitation")).toBeNull(); });
test("ignores untrusted saved login continuation", async () => { http(); sessionStorage.setItem("ai-erp.invitation", "#/invitations/t1?redirect=evil"); mount(); await screen.findByRole("heading", { name: "프로젝트 선택" }); expect(window.location.hash).toBe("#/"); });
test("G02 VIEWER stays on members without invitation controls", async () => { const server = http(); server.on("GET", "/api/v1/projects", () => json([{ ...project, role: "VIEWER" }])); mount("/projects/p1/invitations/new"); expect(await screen.findByRole("heading", { name: "구성원" })).toBeInTheDocument(); expect(screen.queryByRole("dialog", { name: "구성원 초대" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "구성원 초대" })).not.toBeInTheDocument(); expect(server.calls.some(call => call.url.includes("share-invitation"))).toBe(false); });
test("G03 resolution pending guards both actions", async () => { const server = http(); let finish!: (response: Response) => void; server.on("POST", "/api/v1/invitations/t1/accept", () => new Promise(resolve => { finish = resolve; })); const user = mount("/invitations/t1"); const accept = (await screen.findAllByRole("button", { name: "초대 수락" })).find(button => !button.hasAttribute("disabled"))!; await user.click(accept); expect(accept).toBeDisabled(); const rejects = screen.getAllByRole("button", { name: "초대 거절" }); expect(rejects.some(button => (button as HTMLButtonElement).disabled)).toBe(true); finish(json({ ...invitation, status: "ACCEPTED" })); await screen.findByText("초대 상태를 갱신했습니다."); });
test("P06 read success refresh removes read action", async () => { const server = http(); let read = false; server.on("GET", "/api/v1/notifications", () => json([{ id: "n1", type: "SCHEDULE_CONFIRMED", link: "/projects/p1/schedules/s1", createdAt: "2090-01-01T00:00:00Z", readAt: read ? "2090-01-02T00:00:00Z" : null }])); server.on("POST", "/api/v1/notifications/n1/read", () => { read = true; return json({ id: "n1", type: "SCHEDULE_CONFIRMED", createdAt: "2090-01-01T00:00:00Z", readAt: "2090-01-02T00:00:00Z" }); }); const user = mount("/notifications"); await user.click(await screen.findByRole("button", { name: "읽음 처리" })); await screen.findByText("읽음"); expect(screen.queryByRole("button", { name: "읽음 처리" })).not.toBeInTheDocument(); });
test("P07 successful role change invalidates members and projects", async () => { const server = http(); let changed = false; server.on("GET", "/api/v1/projects/p1/members", () => json([{ userId: "u2", role: changed ? "VIEWER" : "MEMBER" }])); server.on("PATCH", "/api/v1/projects/p1/members/u2", () => { changed = true; return json({ userId: "u2", role: "VIEWER" }); }); const user = mount("/projects/p1/members"); const role = (await screen.findAllByRole("combobox"))[0]; await user.selectOptions(role, "VIEWER"); await user.click(screen.getByRole("button", { name: "저장" })); await waitFor(() => expect(role).toHaveValue("VIEWER")); expect(server.calls.filter(c => c.url.startsWith("/api/v1/projects?")).length).toBeGreaterThan(1); });
test.each(["MEMBER", "VIEWER"])("P07 %s cannot change roles", async role => { const server = http(); server.on("GET", "/api/v1/projects", () => json([{ ...project, role }])); mount("/projects/p1/members"); const selector = (await screen.findAllByRole("combobox"))[0]; expect(selector).toBeDisabled(); });
test("P08 configuration required prevents reconnect", async () => { const server = http(); server.on("GET", "/api/v1/calendar/connection", () => json({ status: "NOT_CONNECTED", configurationRequired: true })); mount("/calendar"); await screen.findByText("Calendar 연동이 구성되지 않았습니다."); expect(screen.getByRole("button", { name: "연결 상태 새로고침" })).toBeDisabled(); });
test("P08 reconnect error and pending duplicate guard", async () => { const server = http(); let finish!: (response: Response) => void; server.on("POST", "/api/v1/calendar/reconnect", () => new Promise(resolve => { finish = resolve; })); const user = mount("/calendar"); await user.click(await screen.findByRole("button", { name: "연결 상태 새로고침" })); expect(screen.getByRole("button", { name: "확인하는 중…" })).toBeDisabled(); finish(json({ code: "RECONNECT_FAILED" }, 500)); expect(await screen.findByRole("alert")).toHaveTextContent("RECONNECT_FAILED"); });
test("protected project beyond first membership page remains reachable", async () => { const server = http(); server.on("GET", "/api/v1/projects", (_, url) => json(url.searchParams.get("page") === "0" ? Array.from({ length: 100 }, (_, i) => ({ ...project, id: "other" + i })) : [project])); mount("/projects/p1"); expect((await screen.findAllByText("Design review")).length).toBeGreaterThan(0); expect(server.calls.some(c => c.url === "/api/v1/projects?page=1&limit=100")).toBe(true); });
test("P02 weekly event uses local clock for vertical placement", async () => { http(); const user = mount("/projects/p1/schedules"); await screen.findByLabelText("기준 날짜"); fireEvent.change(screen.getByLabelText("기준 날짜"), { target: { value: "2090-09-10" } }); await user.click(screen.getByRole("button", { name: "주간 보기" })); const grid = await screen.findByRole("grid", { name: "주간 일정" }); const event = within(grid).getByRole("link", { name: /Design review/ }).closest("[data-start-minute]"); expect(event).toHaveAttribute("data-start-minute", "600"); expect(event).toHaveAttribute("data-duration-minute", "60"); });
test("P02 month range changes consistently with non-UTC zone", async () => { const server = http(); const user = mount("/projects/p1/schedules"); await screen.findByLabelText("기준 날짜"); await user.click(screen.getByText("상세 필터")); fireEvent.change(screen.getByLabelText("기준 날짜"), { target: { value: "2090-01-31" } }); fireEvent.change(screen.getByLabelText("표시 시간대"), { target: { value: "America/New_York" } }); await waitFor(() => expect(server.calls.some(c => c.url.includes("from=2089-12-26T05%3A00%3A00.000Z") && c.url.includes("to=2090-02-06T05%3A00%3A00.000Z"))).toBe(true)); });
test("P04 keeps nullable description unchanged during title edit", async () => { const server = http(); server.on("GET", "/api/v1/projects/p1/schedules/s1", () => json({ ...schedule, description: null })); server.on("PATCH", "/api/v1/projects/p1/schedules/s1", body => { expect(body.description).toBeNull(); return json(schedule); }); const user = mount("/projects/p1/schedules/s1/edit"); await user.type(await screen.findByLabelText("제목"), " changed"); await user.click(screen.getByRole("button", { name: "일정 저장" })); await screen.findByRole("heading", { name: "Design review" }); });
test("P04 member dependency error keeps save disabled and manually recovers", async () => { const server = http(); let failed = true; server.on("GET", "/api/v1/projects/p1/members", () => failed ? json({ code: "MEMBERS_FAILED" }, 500) : json([])); const user = mount("/projects/p1/schedules/new"); await screen.findByText("MEMBERS_FAILED"); expect(screen.getByRole("button", { name: "일정 저장" })).toBeDisabled(); failed = false; await user.click(screen.getByRole("button", { name: "구성원 다시 시도" })); await screen.findByText("선택할 구성원이 없습니다."); expect(screen.getByRole("button", { name: "일정 저장" })).toBeEnabled(); });
test("P05 projection retry failure visible and cannot submit twice", async () => { const server = http(); server.on("GET", "/api/v1/projects/p1/schedules/s1/calendar", () => json({ scheduleId: "s1", status: "FAILED", retryClassification: "TRANSIENT", businessRevision: 4 })); let finish!: (response: Response) => void; server.on("POST", "/api/v1/projects/p1/schedules/s1/calendar/retry", () => new Promise(resolve => { finish = resolve; })); const user = mount("/projects/p1/schedules/s1"); await user.click(await screen.findByRole("button", { name: "Calendar 동기화 다시 시도" })); expect(screen.getByRole("button", { name: "Calendar 동기화 다시 시도" })).toBeDisabled(); finish(json({ code: "RETRY_FAILED" }, 500)); expect(await screen.findByRole("alert")).toHaveTextContent("RETRY_FAILED"); });
test("P06 pending read disables duplicate read action", async () => { const server = http(); let finish!: (response: Response) => void; server.on("POST", "/api/v1/notifications/n1/read", () => new Promise(resolve => { finish = resolve; })); const user = mount("/notifications"); await user.click(await screen.findByRole("button", { name: "읽음 처리" })); expect(screen.getByRole("button", { name: "읽음 처리" })).toBeDisabled(); finish(json({ code: "READ_FAILED" }, 500)); await screen.findByText("READ_FAILED"); });
test("P07 pending role mutation disables all selectors", async () => { const server = http(); let finish!: (response: Response) => void; server.on("PATCH", "/api/v1/projects/p1/members/u2", () => new Promise(resolve => { finish = resolve; })); const user = mount("/projects/p1/members"); const roles = await screen.findAllByRole("combobox"); await user.selectOptions(roles[1], "VIEWER"); await user.click(screen.getByRole("button", { name: "저장" })); expect(roles[0]).toBeDisabled(); expect(roles[1]).toBeDisabled(); finish(json({ code: "ROLE_FAILED" }, 500)); await screen.findByText("ROLE_FAILED"); });
