package com.aierp;
import com.aierp.project.ProjectRole;
import com.aierp.project.api.ManagementMutationAccess;
import com.aierp.project.api.ProjectAccess;
import com.aierp.project.api.ProjectManagementDefinitionAccess;
import com.aierp.project.api.ManagementRequestCanonicalizer;
import com.aierp.project.ManagementAuditEntity;
import com.aierp.project.ManagementAuditRepository;
import com.aierp.project.ProjectManagementDefinitionEntity;
import com.aierp.project.ProjectManagementDefinitionRepository;
import com.aierp.projectplan.*;
import com.aierp.projectplan.api.ProjectManagementController.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.SliceImpl;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ProjectManagementFoundationTest {
    @Mock TaskExecutionRepository executions; @Mock ManagementMutationAccess mutations; @Mock ProjectManagementDefinitionRepository definitionRows; @Mock PlanItemRepository items; @Mock ManagementAuditRepository auditRows;
    @Mock PlanItemDependencyRepository dependencies; @Mock ProjectAccess access;
    final UUID project=UUID.randomUUID(), actor=UUID.randomUUID(), itemId=UUID.randomUUID(), requestId=UUID.randomUUID();
    ProjectManagementService service;
    @BeforeEach void setUp(){service=new ProjectManagementService(executions,mutations,items,dependencies,access,true);lenient().when(mutations.lock(any(),any(),any())).thenReturn(Optional.empty());lenient().when(access.readableProject(project,actor)).thenReturn(new ProjectAccess.ReadableProject(project,"ERP",ProjectRole.MANAGER));lenient().when(dependencies.findByItemIdIn(anyCollection(),any())).thenReturn(new SliceImpl<>(List.of()));lenient().when(dependencies.findByPredecessorIdIn(anyCollection(),any())).thenReturn(new SliceImpl<>(List.of()));}
    @Test void definitionWriteTrimsAndAuditsWithoutTouchingLegacyPlan(){var definition=new ProjectManagementDefinitionAccess(definitionRows,access,mutations,true);when(definitionRows.lockByProjectId(project)).thenReturn(Optional.empty());var result=definition.update(project,new ProjectManagementDefinitionAccess.DefinitionWrite("  Purpose  ","Criteria",actor,"WATCH","Reason",java.time.LocalDate.of(2026,10,3),0L,requestId),actor);var row=ArgumentCaptor.forClass(ProjectManagementDefinitionEntity.class);verify(definitionRows).saveAndFlush(row.capture());assertThat(row.getValue().purpose).isEqualTo("Purpose");assertThat(row.getValue().rowVersion).isEqualTo(1);assertThat(result.health()).isEqualTo("WATCH");verify(mutations).audit(eq(project),eq(actor),eq("DEFINITION"),eq(project),eq(1L),eq("DEFINITION_UPDATE"),any(),any());verify(mutations).saveReceipt(eq(project),eq(actor),eq(requestId),any(),eq("DEFINITION"),eq(project),eq(1L),eq("DEFINITION_UPDATE"));}
    @Test void taskMetadataIsSeparateFromLegacyItemAndVersioned(){var task=new PlanItemEntity();task.id=itemId;task.projectId=project;task.kind=PlanItemKind.TASK;when(items.lockByIdAndProjectId(itemId,project)).thenReturn(Optional.of(task));when(executions.lockByItemIdAndProjectId(itemId,project)).thenReturn(Optional.empty());var result=service.updateTaskExecution(project,itemId,new TaskExecutionWrite(TaskPriority.HIGH,"  Done when deployed  ",0L,requestId),actor);var execution=ArgumentCaptor.forClass(TaskExecutionEntity.class);verify(executions).saveAndFlush(execution.capture());assertThat(execution.getValue().priority).isEqualTo(TaskExecutionPriority.HIGH);assertThat(execution.getValue().completionCriterion).isEqualTo("Done when deployed");assertThat(result.rowVersion()).isEqualTo(1);assertThat(task.title).isNull();verify(mutations).audit(eq(project),eq(actor),eq("TASK_EXECUTION"),eq(itemId),eq(1L),eq("TASK_EXECUTION_UPDATE"),any(),any());verify(mutations).saveReceipt(eq(project),eq(actor),eq(requestId),any(),eq("TASK_EXECUTION"),eq(itemId),eq(1L),eq("TASK_EXECUTION_UPDATE"));}
    @Test void taskBulkReadReturnsNullVersionZeroForLegacyMetadata(){var task=new PlanItemEntity();task.id=itemId;task.projectId=project;task.kind=PlanItemKind.TASK;when(items.findAllById(anyCollection())).thenReturn(List.of(task));when(executions.findByItemIdIn(anyCollection())).thenReturn(List.of());var result=service.taskExecutions(project,List.of(itemId),actor);assertThat(result.complete()).isTrue();assertThat(result.items()).singleElement().satisfies(t->{assertThat(t.priority()).isNull();assertThat(t.rowVersion()).isZero();});}
    @Test void replayWithDifferentPayloadCannotApplyAgain(){var prior=new ManagementMutationAccess.MutationReceipt("different","TASK_EXECUTION",itemId,1,"APPLIED");when(mutations.lock(project,actor,requestId)).thenReturn(Optional.of(prior));var task=new PlanItemEntity();task.id=itemId;task.projectId=project;task.kind=PlanItemKind.TASK;when(items.lockByIdAndProjectId(itemId,project)).thenReturn(Optional.of(task));assertThatThrownBy(()->service.updateTaskExecution(project,itemId,new TaskExecutionWrite(TaskPriority.HIGH,"changed",0L,requestId),actor)).isInstanceOf(IllegalStateException.class).hasMessage("REQUEST_PAYLOAD_MISMATCH");verify(executions,never()).saveAndFlush(any());}
    @Test void disabledFeatureBlocksWritesBeforePersistence(){service=new ProjectManagementService(executions,mutations,items,dependencies,access,false);assertThatThrownBy(()->service.updateTaskExecution(project,itemId,new TaskExecutionWrite(TaskPriority.HIGH,"Done",0L,requestId),actor)).isInstanceOf(IllegalStateException.class).hasMessage("PROJECT_MANAGEMENT_DISABLED");verify(executions,never()).saveAndFlush(any());}
    @Test void canonicalRequestSeparatesCommaAndFieldBoundaryValues(){var left=ManagementRequestCanonicalizer.definition("DEFINITION_UPDATE",project,"a, successCriteria=b","c",null,null,null,null,0L);var right=ManagementRequestCanonicalizer.definition("DEFINITION_UPDATE",project,"a","b, successCriteria=c",null,null,null,null,0L);assertThat(left).isNotEqualTo(right);}
    @Test void canonicalRequestNormalizesBlankAndSurroundingWhitespace(){var blank=ManagementRequestCanonicalizer.definition("DEFINITION_UPDATE",project,"   "," Criteria ",null,null,"\t",null,0L);var cleared=ManagementRequestCanonicalizer.definition("DEFINITION_UPDATE",project,null,"Criteria",null,null,null,null,0L);assertThat(blank).isEqualTo(cleared);var task=ManagementRequestCanonicalizer.taskExecution("TASK_EXECUTION_UPDATE",itemId,"HIGH","  Done  ",0L);var trimmed=ManagementRequestCanonicalizer.taskExecution("TASK_EXECUTION_UPDATE",itemId," HIGH ","Done",0L);assertThat(task).isEqualTo(trimmed);}
    @Test void disabledFeatureRemovesEditCapabilityFromReads(){service=new ProjectManagementService(executions,mutations,items,dependencies,access,false);var task=new PlanItemEntity();task.id=itemId;task.projectId=project;task.kind=PlanItemKind.TASK;when(items.findAllById(anyCollection())).thenReturn(List.of(task));when(executions.findByItemIdIn(anyCollection())).thenReturn(List.of());assertThat(service.taskExecutions(project,List.of(itemId),actor).items()).singleElement().extracting(TaskExecution::canEdit).isEqualTo(false);}
    @Test void auditPortDeepCopiesInputsAndReturnsUnmodifiableSnapshots(){var port=new ManagementMutationAccess(null,auditRows);var labels=new ArrayList<Object>(List.of("before"));var before=new LinkedHashMap<String,Object>();before.put("nested",labels);var after=new LinkedHashMap<String,Object>();after.put("value","after");port.audit(project,actor,"DEFINITION",project,1,"UPDATE",before,after);labels.set(0,"mutated");var saved=ArgumentCaptor.forClass(ManagementAuditEntity.class);verify(auditRows).save(saved.capture());assertThat(((List<?>)saved.getValue().beforeValues.get("nested")).get(0)).isEqualTo("before");when(auditRows.findByProjectIdAndResourceTypeAndResourceIdOrderByOccurredAtDescIdDesc(eq(project),eq("DEFINITION"),eq(project),any())).thenReturn(new PageImpl<>(List.of(saved.getValue())));var entry=port.history(project,"DEFINITION",project,0,10).entries().get(0);assertThatThrownBy(()->entry.before().put("new","value")).isInstanceOf(UnsupportedOperationException.class);assertThatThrownBy(()->((List<Object>)entry.before().get("nested")).add("x")).isInstanceOf(UnsupportedOperationException.class);}
    @Test void allWorkCarriesObservedCountAndActualPredecessorAttention(){var predecessor=new PlanItemEntity();predecessor.id=UUID.randomUUID();predecessor.projectId=project;predecessor.kind=PlanItemKind.TASK;predecessor.state=PlanItemState.IN_PROGRESS;var task=new PlanItemEntity();task.id=itemId;task.projectId=project;task.kind=PlanItemKind.TASK;task.state=PlanItemState.READY;task.title="Overdue task";task.deadline=java.time.LocalDate.now(java.time.ZoneOffset.UTC).minusDays(1);when(access.readableProjects(actor)).thenReturn(List.of(new ProjectAccess.ReadableProject(project,"ERP",ProjectRole.MANAGER)));when(items.findWorkAll(anyCollection(),eq(actor),eq(false),isNull(),any(),any())).thenReturn(List.of(task));when(items.countWorkAll(anyCollection(),eq(actor),eq(false),isNull())).thenReturn(1L);when(executions.findByItemIdIn(anyCollection())).thenReturn(List.of());when(dependencies.findByItemIdIn(anyCollection(),any())).thenReturn(new SliceImpl<>(List.of(new PlanItemDependencyEntity(itemId,predecessor.id))));when(dependencies.findByPredecessorIdIn(anyCollection(),any())).thenReturn(new SliceImpl<>(List.of()));when(items.findByProjectIdAndIdIn(eq(project),anyCollection())).thenReturn(List.of(predecessor));var result=service.work(WorkRange.ALL,java.time.ZoneId.of("UTC"),null,WorkAssignee.MINE,0,50,null,actor);assertThat(result.observedCount()).isEqualTo(1);assertThat(result.items()).singleElement().satisfies(row->{assertThat(row.blockingReason()).isEqualTo("Blocked by an incomplete predecessor");assertThat(row.nextSchedule()).isNull();});verify(items,never()).findByProjectIdOrderBySortOrderAscIdAsc(any());verify(items).findByProjectIdAndIdIn(eq(project),argThat(ids->ids.contains(predecessor.id)));}
}
