package com.aierp;

import static com.epages.restdocs.apispec.MockMvcRestDocumentationWrapper.document;
import static com.epages.restdocs.apispec.ResourceDocumentation.resource;
import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.when;
import static org.springframework.restdocs.mockmvc.RestDocumentationRequestBuilders.*;
import static org.springframework.restdocs.payload.JsonFieldType.*; import static org.springframework.restdocs.payload.PayloadDocumentation.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import com.aierp.identity.api.ApplicationPrincipal; import com.aierp.platform.web.*; import com.aierp.schedule.*; import com.aierp.schedule.api.*; import com.aierp.schedule.api.ScheduleWorkspaceController.*; import com.epages.restdocs.apispec.ResourceSnippetParameters;
import java.time.Instant; import java.util.*; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.restdocs.test.autoconfigure.AutoConfigureRestDocs; import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest; import org.springframework.context.annotation.Import; import org.springframework.http.MediaType; import org.springframework.restdocs.payload.*; import org.springframework.security.authentication.UsernamePasswordAuthenticationToken; import org.springframework.test.context.bean.override.mockito.MockitoBean; import org.springframework.test.web.servlet.MockMvc; import tools.jackson.databind.json.JsonMapper;

@WebMvcTest(ScheduleWorkspaceController.class) @AutoConfigureRestDocs @Import({SecurityConfiguration.class,ApiExceptionHandler.class})
class ScheduleWorkspaceApiDocumentationTest {
    @Autowired MockMvc mvc; @MockitoBean ScheduleWorkspaceService service; final JsonMapper mapper=JsonMapper.builder().build();
    @Test void documentsAllElevenWorkspaceRoutesWithPopulatedTypedShapes() throws Exception {
        var project=UUID.randomUUID();var user=UUID.randomUUID();var id=UUID.randomUUID();var propertyId=UUID.randomUUID();var optionId=UUID.randomUUID();var auth=new UsernamePasswordAuthenticationToken(new ApplicationPrincipal(user,"user@example.test",true),null,List.of());
        var numberId=UUID.randomUUID();var checkboxId=UUID.randomUUID();var nullableId=UUID.randomUUID();var property=new Property(propertyId,"Priority",SchedulePropertyEntity.PropertyType.SINGLE_SELECT,0,false,1,List.of(new Option(optionId,"Open","blue",false)));var filters=List.of(new Filter("property:"+propertyId,Operator.EQ,mapper.getNodeFactory().textNode(optionId.toString())),new Filter("property:"+numberId,Operator.GTE,mapper.getNodeFactory().numberNode(12.5)),new Filter("property:"+checkboxId,Operator.EQ,mapper.getNodeFactory().booleanNode(true)));var config=new ViewConfig(ViewType.LIST,filters,List.of(new SortSpec("startsAt",Direction.ASC)),propertyId,propertyId,List.of("title","property:"+propertyId));var view=new View(id.toString(),"My list",Scope.PERSONAL,user,1,false,config);var ws=new Workspace(List.of(property),List.of(view),null,1);
        var schedule=new ScheduleController.ScheduleResponse(id,project,"Planning",ScheduleEntity.Status.CONFIRMED,2,1,Instant.parse("2099-01-01T09:00:00Z"),Instant.parse("2099-01-01T10:00:00Z"),"Plan",user,List.of(new ScheduleController.Participant(user,null,true,"User","user@example.test")),List.of(new ScheduleController.Change(1,"SCHEDULE_CONFIRMED",user,Instant.parse("2099-01-01T08:00:00Z"))));var typedValues=new LinkedHashMap<UUID,tools.jackson.databind.JsonNode>();typedValues.put(propertyId,mapper.getNodeFactory().textNode(optionId.toString()));typedValues.put(numberId,mapper.getNodeFactory().numberNode(12.5));typedValues.put(checkboxId,mapper.getNodeFactory().booleanNode(true));typedValues.put(nullableId,mapper.getNodeFactory().nullNode());var record=new ScheduleWorkspaceController.Record(schedule,typedValues);var qr=new QueryResult(List.of(record),120,false,0,50,List.of(new Group(optionId,"Open","blue",1),new Group(null,"Unassigned",null,119)),Instant.parse("2099-01-01T08:30:00Z"));
        when(service.workspace(project,user)).thenReturn(ws);when(service.createProperty(eq(project),any(),eq(user))).thenReturn(property);when(service.updateProperty(eq(project),eq(propertyId),any(),eq(user))).thenReturn(property);when(service.createView(eq(project),any(),eq(user))).thenReturn(view);when(service.updateView(eq(project),eq(id),any(),eq(user))).thenReturn(view);when(service.dashboard(eq(project),any(),eq(user))).thenReturn(new Dashboard(null,2));when(service.query(eq(project),any(),eq(user))).thenReturn(qr);when(service.record(project,id,user)).thenReturn(record);when(service.createRecord(eq(project),any(),eq(user))).thenReturn(record);when(service.updateRecord(eq(project),eq(id),any(),eq(user))).thenReturn(record);when(service.updateValues(eq(project),eq(id),any(),eq(user))).thenReturn(record);
        mvc.perform(get("/api/v1/projects/{projectId}/schedule-workspace",project).with(authentication(auth))).andExpect(status().isOk()).andDo(document("schedule-workspace-read",spec("Workspace metadata",null,workspaceFields())));
        String pc="{\"name\":\"Priority\",\"type\":\"SINGLE_SELECT\",\"position\":0,\"archived\":false,\"options\":[{\"label\":\"Open\",\"color\":\"blue\",\"archived\":false}]}";String pp="{\"name\":\"Priority\",\"type\":\"SINGLE_SELECT\",\"position\":0,\"archived\":false,\"rowVersion\":1,\"options\":[{\"id\":\""+optionId+"\",\"label\":\"Open\",\"color\":\"blue\",\"archived\":false}]}";
        mvc.perform(post("/api/v1/projects/{projectId}/schedule-workspace/properties",project).contentType(MediaType.APPLICATION_JSON).content(pc).with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-property-create",spec("Create property",propertyWrite(false),propertyFields(""))));mvc.perform(patch("/api/v1/projects/{projectId}/schedule-workspace/properties/{id}",project,propertyId).contentType(MediaType.APPLICATION_JSON).content(pp).with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-property-update",spec("Update property",propertyWrite(true),propertyFields(""))));
        String cj="{\"type\":\"LIST\",\"filters\":[{\"field\":\"property:"+propertyId+"\",\"operator\":\"EQ\",\"value\":\""+optionId+"\"},{\"field\":\"property:"+numberId+"\",\"operator\":\"GTE\",\"value\":12.5},{\"field\":\"property:"+checkboxId+"\",\"operator\":\"EQ\",\"value\":true}],\"sorts\":[{\"field\":\"startsAt\",\"direction\":\"ASC\"}],\"groupBy\":\""+propertyId+"\",\"legendBy\":\""+propertyId+"\",\"visibleFields\":[\"title\",\"property:"+propertyId+"\"]}";String vc="{\"name\":\"My list\",\"scope\":\"PERSONAL\",\"archived\":false,\"config\":"+cj+"}";String vp="{\"name\":\"My list\",\"scope\":\"PERSONAL\",\"rowVersion\":1,\"archived\":false,\"config\":"+cj+"}";
        mvc.perform(post("/api/v1/projects/{projectId}/schedule-workspace/views",project).contentType(MediaType.APPLICATION_JSON).content(vc).with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-view-create",spec("Create saved view",viewWrite(false),viewFields(""))));mvc.perform(patch("/api/v1/projects/{projectId}/schedule-workspace/views/{id}",project,id).contentType(MediaType.APPLICATION_JSON).content(vp).with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-view-update",spec("Update saved view",viewWrite(true),viewFields(""))));
        mvc.perform(patch("/api/v1/projects/{projectId}/schedule-workspace/dashboard",project).contentType(MediaType.APPLICATION_JSON).content("{\"viewId\":null,\"rowVersion\":1}").with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-dashboard",spec("Select dashboard view",List.of(opt("viewId",STRING),fd("rowVersion",NUMBER)),List.of(opt("dashboardViewId",STRING),fd("dashboardRowVersion",NUMBER)))));
        mvc.perform(post("/api/v1/projects/{projectId}/schedule-workspace/query",project).contentType(MediaType.APPLICATION_JSON).content("{\"config\":"+cj+",\"from\":\"2099-01-01T00:00:00Z\",\"to\":\"2099-02-01T00:00:00Z\",\"page\":0,\"size\":50}").with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-query",spec("Complete-scope query",queryFields(),queryResultFields())));
        String values="{\""+propertyId+"\":\""+optionId+"\",\""+numberId+"\":12.5,\""+checkboxId+"\":true,\""+nullableId+"\":null}";String createSchedule="{\"title\":\"Planning\",\"startsAt\":\"2099-01-01T09:00:00Z\",\"endsAt\":\"2099-01-01T10:00:00Z\",\"description\":\"Plan\",\"memberParticipantIds\":[\""+user+"\"],\"externalAttendeeEmails\":[\"guest@example.test\"]}";String updateSchedule="{\"title\":\"Planning\",\"startsAt\":\"2099-01-01T09:00:00Z\",\"endsAt\":\"2099-01-01T10:00:00Z\",\"rowVersion\":2,\"description\":\"Plan\",\"memberParticipantIds\":[\""+user+"\"],\"externalAttendeeEmails\":[\"guest@example.test\"]}";
        mvc.perform(get("/api/v1/projects/{projectId}/schedule-workspace/records/{id}",project,id).with(authentication(auth))).andExpect(status().isOk()).andDo(document("schedule-workspace-record-read",spec("Read record",null,recordFields(""))));mvc.perform(post("/api/v1/projects/{projectId}/schedule-workspace/records",project).contentType(MediaType.APPLICATION_JSON).content("{\"schedule\":"+createSchedule+",\"values\":"+values+"}").with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-record-create",spec("Atomic record create",recordWrite(false),recordFields(""))));mvc.perform(patch("/api/v1/projects/{projectId}/schedule-workspace/records/{id}",project,id).contentType(MediaType.APPLICATION_JSON).content("{\"schedule\":"+updateSchedule+",\"values\":"+values+"}").with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-record-update",spec("Atomic record update",recordWrite(true),recordFields(""))));mvc.perform(patch("/api/v1/projects/{projectId}/schedule-workspace/records/{id}/values",project,id).contentType(MediaType.APPLICATION_JSON).content("{\"rowVersion\":2,\"values\":"+values+"}").with(authentication(auth)).with(csrf())).andExpect(status().isOk()).andDo(document("schedule-workspace-record-values-update",spec("Versioned custom values",List.of(fd("rowVersion",NUMBER),fd("values",OBJECT),varies("values.*","Typed scalar; null clears")),recordFields(""))));
    }
    private org.springframework.restdocs.snippet.Snippet spec(String d,List<FieldDescriptor> req,List<FieldDescriptor> res){var b=ResourceSnippetParameters.builder().description(d+". Errors: 400 validation, 403 access, 404 missing, 409 stale version.");if(req!=null)b.requestFields(req);if(res!=null)b.responseFields(res);return resource(b.build());}
    private FieldDescriptor fd(String p,JsonFieldType t){return fieldWithPath(p).type(t).description(p);}private FieldDescriptor opt(String p,JsonFieldType t){return fieldWithPath(p).optional().type(t).description(p);}
    private List<FieldDescriptor> propertyWrite(boolean patch){var f=new ArrayList<FieldDescriptor>();f.add(patch?opt("name",STRING):fd("name",STRING));f.add(patch?opt("type",STRING):fd("type",STRING));f.add(opt("position",NUMBER));f.add(opt("archived",BOOLEAN));f.add(opt("options",ARRAY));f.add(opt("options[].id",STRING));f.add(fd("options[].label",STRING));f.add(fd("options[].color",STRING));f.add(opt("options[].archived",BOOLEAN));if(patch)f.add(fd("rowVersion",NUMBER));return f;}
    private List<FieldDescriptor> propertyFields(String p){return List.of(fd(p+"id",STRING),fd(p+"name",STRING),fd(p+"type",STRING),fd(p+"position",NUMBER),fd(p+"archived",BOOLEAN),fd(p+"rowVersion",NUMBER),fd(p+"options",ARRAY),fd(p+"options[].id",STRING),fd(p+"options[].label",STRING),fd(p+"options[].color",STRING),fd(p+"options[].archived",BOOLEAN));}
    private List<FieldDescriptor> config(String p){return List.of(fd(p+"type",STRING),fd(p+"filters",ARRAY),fd(p+"filters[].field",STRING),fd(p+"filters[].operator",STRING),fieldWithPath(p+"filters[].value").optional().type(VARIES).description("String, number, boolean, or null according to field/operator"),fd(p+"sorts",ARRAY),fd(p+"sorts[].field",STRING),fd(p+"sorts[].direction",STRING),opt(p+"groupBy",STRING),opt(p+"legendBy",STRING),fd(p+"visibleFields",ARRAY));}
    private List<FieldDescriptor> viewWrite(boolean patch){var f=new ArrayList<FieldDescriptor>(List.of(patch?opt("name",STRING):fd("name",STRING),patch?opt("scope",STRING):fd("scope",STRING),opt("archived",BOOLEAN),patch?opt("config",OBJECT):fd("config",OBJECT)));f.addAll(config("config."));if(patch)f.add(fd("rowVersion",NUMBER));return f;}private List<FieldDescriptor> viewFields(String p){var f=new ArrayList<FieldDescriptor>(List.of(fd(p+"id",STRING),fd(p+"name",STRING),fd(p+"scope",STRING),opt(p+"ownerId",STRING),fd(p+"rowVersion",NUMBER),fd(p+"archived",BOOLEAN),fd(p+"config",OBJECT)));f.addAll(config(p+"config."));return f;}
    private List<FieldDescriptor> workspaceFields(){var f=new ArrayList<FieldDescriptor>(List.of(fd("properties",ARRAY)));f.addAll(propertyFields("properties[]."));f.add(fd("views",ARRAY));f.addAll(viewFields("views[]."));f.add(opt("dashboardViewId",STRING));f.add(fd("dashboardRowVersion",NUMBER));return f;}
    private List<FieldDescriptor> queryFields(){var f=new ArrayList<FieldDescriptor>(List.of(fd("config",OBJECT)));f.addAll(config("config."));f.addAll(List.of(opt("from",STRING),opt("to",STRING),opt("page",NUMBER),opt("size",NUMBER)));return f;}private List<FieldDescriptor> queryResultFields(){var f=new ArrayList<FieldDescriptor>(List.of(fd("records",ARRAY)));f.addAll(recordFields("records[]."));f.addAll(List.of(fd("total",NUMBER),fd("hasMore",BOOLEAN),fd("page",NUMBER),fd("size",NUMBER),fd("groups",ARRAY),opt("groups[].optionId",STRING),fd("groups[].label",STRING),opt("groups[].color",STRING),fd("groups[].count",NUMBER),fd("queriedAt",STRING)));return f;}
    private List<FieldDescriptor> recordWrite(boolean update){var f=new ArrayList<FieldDescriptor>(List.of(fd("schedule",OBJECT),fd("schedule.title",STRING),fd("schedule.startsAt",STRING),fd("schedule.endsAt",STRING)));f.add(update?fd("schedule.rowVersion",NUMBER):opt("schedule.rowVersion",NUMBER));f.addAll(List.of(opt("schedule.description",STRING),opt("schedule.memberParticipantIds",ARRAY),opt("schedule.externalAttendeeEmails",ARRAY),opt("values",OBJECT),varies("values.*","Typed scalar; null clears")));return f;}
    private List<FieldDescriptor> recordFields(String p){return List.of(fd(p+"schedule.id",STRING),fd(p+"schedule.projectId",STRING),fd(p+"schedule.title",STRING),fd(p+"schedule.status",STRING),fd(p+"schedule.rowVersion",NUMBER),fd(p+"schedule.businessRevision",NUMBER),fd(p+"schedule.startsAt",STRING),fd(p+"schedule.endsAt",STRING),opt(p+"schedule.description",STRING),fd(p+"schedule.createdBy",STRING),fd(p+"schedule.participants",ARRAY),opt(p+"schedule.participants[].memberUserId",STRING),opt(p+"schedule.participants[].externalEmail",STRING),fd(p+"schedule.participants[].acknowledged",BOOLEAN),fd(p+"schedule.participants[].displayName",STRING),fd(p+"schedule.participants[].email",STRING),fd(p+"schedule.changes",ARRAY),fd(p+"schedule.changes[].businessRevision",NUMBER),fd(p+"schedule.changes[].type",STRING),fd(p+"schedule.changes[].changedBy",STRING),fd(p+"schedule.changes[].createdAt",STRING),fd(p+"values",OBJECT),varies(p+"values.*","Typed scalar or null"));}
    private FieldDescriptor varies(String path,String description){return fieldWithPath(path).optional().type(VARIES).description(description);}
}
