package com.aierp;

import static org.assertj.core.api.Assertions.assertThat; import static org.assertj.core.api.Assertions.assertThatThrownBy; import static org.mockito.Mockito.*;
import java.time.Instant; import java.util.*;
import com.aierp.platform.events.EventJournal; import com.aierp.project.api.ProjectAccess; import com.aierp.schedule.*; import com.aierp.schedule.api.*; import com.aierp.schedule.api.ScheduleWorkspaceController.*;
import tools.jackson.databind.json.JsonMapper; import org.junit.jupiter.api.Test; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.Mock; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.jdbc.core.JdbcTemplate;

@ExtendWith(MockitoExtension.class)
class ScheduleWorkspaceServiceTest {
    @Mock SchedulePropertyRepository properties; @Mock SchedulePropertyOptionRepository options; @Mock SchedulePropertyValueRepository values; @Mock ScheduleSavedViewRepository views; @Mock ScheduleDashboardViewRepository dashboards; @Mock ScheduleRepository schedules; @Mock ProjectAccess access; @Mock ScheduleService legacy; @Mock JdbcTemplate jdbc; @Mock EventJournal events;
    final JsonMapper mapper=JsonMapper.builder().build(); final UUID project=UUID.randomUUID(), owner=UUID.randomUUID(), other=UUID.randomUUID();
    ScheduleWorkspaceService service(){return new ScheduleWorkspaceService(properties,options,values,views,dashboards,schedules,access,legacy,jdbc,mapper,events);}
    @Test void workspaceReturnsVirtualPeersAndOnlyActorPersonalViews(){var p=new SchedulePropertyEntity();p.id=UUID.randomUUID();p.projectId=project;p.name="Priority";p.propertyType=SchedulePropertyEntity.PropertyType.TEXT;p.position=0;when(properties.findByProjectIdOrderByPositionAscIdAsc(project)).thenReturn(List.of(p));when(options.findByPropertyIdOrderByPositionAscIdAsc(p.id)).thenReturn(List.of());var mine=new ScheduleSavedViewEntity();mine.id=UUID.randomUUID();mine.projectId=project;mine.ownerId=owner;mine.scope=ScheduleSavedViewEntity.Scope.PERSONAL;mine.name="Mine";mine.config=mapper.convertValue(new ViewConfig(ViewType.LIST,List.of(),List.of(),null,null,List.of("title")),Map.class);var otherView=new ScheduleSavedViewEntity();otherView.id=UUID.randomUUID();otherView.projectId=project;otherView.ownerId=other;otherView.scope=ScheduleSavedViewEntity.Scope.PERSONAL;otherView.name="Other";otherView.config=mine.config;when(views.findByProjectId(project)).thenReturn(List.of(mine,otherView));when(dashboards.findByProjectId(project)).thenReturn(Optional.empty());var workspace=service().workspace(project,owner);assertThat(workspace.views()).extracting(View::id).contains("builtin-calendar","builtin-cards","builtin-list",mine.id.toString()).doesNotContain(otherView.id.toString());assertThat(workspace.dashboardViewId()).isNull();}
    @Test void valuePatchWithSameTypedValueDoesNotAdvanceScheduleVersion(){var id=UUID.randomUUID();var p=new SchedulePropertyEntity();p.id=UUID.randomUUID();p.projectId=project;p.name="Title";p.propertyType=SchedulePropertyEntity.PropertyType.TEXT;var s=new ScheduleEntity();s.id=id;s.projectId=project;s.createdBy=owner;s.status=ScheduleEntity.Status.DRAFT;s.rowVersion=4;var v=new SchedulePropertyValueEntity();v.id=UUID.randomUUID();v.projectId=project;v.scheduleId=id;v.propertyId=p.id;v.valueType=p.propertyType;v.textValue="same";var response=new ScheduleController.ScheduleResponse(id,project,"S",ScheduleEntity.Status.DRAFT,4,0,Instant.now(),Instant.now().plusSeconds(60),null,owner,List.of(),List.of());when(schedules.lockByIdAndProjectId(id,project)).thenReturn(Optional.of(s));when(properties.findByProjectIdOrderByPositionAscIdAsc(project)).thenReturn(List.of(p));when(values.findByProjectIdAndScheduleIdAndPropertyId(project,id,p.id)).thenReturn(Optional.of(v));when(values.findByProjectIdAndScheduleId(project,id)).thenReturn(List.of(v));when(legacy.detail(project,id,owner)).thenReturn(response);var result=service().updateValues(project,id,new ValuesWrite(4L,Map.of(p.id,mapper.getNodeFactory().textNode("same"))),owner);assertThat(result.schedule().rowVersion()).isEqualTo(4);verify(schedules,never()).saveAndFlush(any());verify(events,never()).record(anyString(),any(UUID.class),any(UUID.class),any(UUID.class),anyList(),anyLong());}
    @Test void httpParsedEquivalentNumbersRemainNoopEvenAfterPropertyArchive() throws Exception {
        var id=UUID.randomUUID();var p=new SchedulePropertyEntity();p.id=UUID.randomUUID();p.projectId=project;p.name="Amount";p.propertyType=SchedulePropertyEntity.PropertyType.NUMBER;
        var s=new ScheduleEntity();s.id=id;s.projectId=project;s.createdBy=owner;s.status=ScheduleEntity.Status.DRAFT;s.rowVersion=4;
        var v=new SchedulePropertyValueEntity();v.id=UUID.randomUUID();v.projectId=project;v.scheduleId=id;v.propertyId=p.id;v.valueType=p.propertyType;v.numberValue=new java.math.BigDecimal("12.50");
        var response=new ScheduleController.ScheduleResponse(id,project,"S",ScheduleEntity.Status.DRAFT,4,0,Instant.now(),Instant.now().plusSeconds(60),null,owner,List.of(),List.of());when(schedules.lockByIdAndProjectId(id,project)).thenReturn(Optional.of(s));when(properties.findByProjectIdOrderByPositionAscIdAsc(project)).thenReturn(List.of(p));when(values.findByProjectIdAndScheduleIdAndPropertyId(project,id,p.id)).thenReturn(Optional.of(v));when(values.findByProjectIdAndScheduleId(project,id)).thenReturn(List.of(v));when(legacy.detail(project,id,owner)).thenReturn(response);
        var api=service();var cases=Map.of("12","12.00","12.5","12.50","12.50","12.500");for(var entry:cases.entrySet()){v.numberValue=new java.math.BigDecimal(entry.getValue());var result=api.updateValues(project,id,new ValuesWrite(4L,Map.of(p.id,mapper.readTree(entry.getKey()))),owner);assertThat(result.schedule().rowVersion()).isEqualTo(4);}verify(values,never()).save(any());
        v.numberValue=new java.math.BigDecimal("12.50");p.archived=true;var archived=api.updateValues(project,id,new ValuesWrite(4L,Map.of(p.id,mapper.readTree("12.5"))),owner);assertThat(archived.schedule().rowVersion()).isEqualTo(4);verify(values,never()).save(any());verify(schedules,never()).saveAndFlush(any());verify(events,never()).record(anyString(),any(UUID.class),any(UUID.class),any(UUID.class),anyList(),anyLong());
    }
    @Test void workspaceRoundTripsPersistedBuiltinDashboard(){var d=new ScheduleDashboardViewEntity();d.builtinView="builtin-calendar";d.rowVersion=3;when(properties.findByProjectIdOrderByPositionAscIdAsc(project)).thenReturn(List.of());when(views.findByProjectId(project)).thenReturn(List.of());when(dashboards.findByProjectId(project)).thenReturn(Optional.of(d));assertThat(service().workspace(project,owner).dashboardViewId()).isEqualTo("builtin-calendar");assertThat(service().workspace(project,owner).dashboardRowVersion()).isEqualTo(3);}
    @Test void personalViewRejectsViewerAndOwnerCheckPrecedesVersion(){var v=new ScheduleSavedViewEntity();v.id=UUID.randomUUID();v.projectId=project;v.ownerId=owner;v.scope=ScheduleSavedViewEntity.Scope.PERSONAL;v.rowVersion=8;when(views.lockByIdAndProjectId(v.id,project)).thenReturn(Optional.of(v));doThrow(new org.springframework.security.access.AccessDeniedException("SCHEDULE_WRITE_DENIED")).when(access).requireWriter(project,owner,null);assertThatThrownBy(()->service().updateView(project,v.id,new ViewWrite(null,null,null,7L,null),other)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class).hasMessageContaining("VIEW_OWNER_REQUIRED");assertThatThrownBy(()->service().updateView(project,v.id,new ViewWrite(null,null,null,8L,null),owner)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class).hasMessageContaining("SCHEDULE_WRITE_DENIED");}
    @Test void strictFiltersRejectWrongScalarAndEmptyOperand(){when(properties.findByProjectIdOrderByPositionAscIdAsc(project)).thenReturn(List.of());var badBoolean=new ViewConfig(ViewType.LIST,List.of(new Filter("createdBy",Operator.EQ,mapper.getNodeFactory().booleanNode(true))),List.of(),null,null,List.of("title"));assertThatThrownBy(()->service().query(project,new Query(badBoolean,null,null,0,10),owner)).isInstanceOf(RuntimeException.class);var emptyOperand=new ViewConfig(ViewType.LIST,List.of(new Filter("title",Operator.IS_EMPTY,mapper.getNodeFactory().textNode("no"))),List.of(),null,null,List.of("title"));assertThatThrownBy(()->service().query(project,new Query(emptyOperand,null,null,0,10),owner)).isInstanceOf(RuntimeException.class);}
}
