package com.aierp;

import static org.assertj.core.api.Assertions.assertThat; import static org.assertj.core.api.Assertions.assertThatThrownBy;
import java.sql.Timestamp; import java.time.*; import java.util.*;
import com.aierp.schedule.*; import com.aierp.schedule.api.ScheduleWorkspaceController.*; import tools.jackson.databind.json.JsonMapper;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.orm.ObjectOptimisticLockingFailureException; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.testcontainers.containers.GenericContainer; import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.Container; import org.testcontainers.junit.jupiter.Testcontainers; import org.testcontainers.utility.DockerImageName;

/** PostgreSQL proof for complete-scope SQL and private-view isolation. */
@SpringBootTest @Testcontainers(disabledWithoutDocker=false)
class ScheduleWorkspacePostgresIntegrationTest {
    @Container static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:18.6");
    @Container static final GenericContainer<?> REDIS=new GenericContainer<>(DockerImageName.parse("redis:8.2.9")).withExposedPorts(6379);
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",POSTGRES::getJdbcUrl);r.add("spring.datasource.username",POSTGRES::getUsername);r.add("spring.datasource.password",POSTGRES::getPassword);r.add("spring.data.redis.url",()->"redis://%s:%d".formatted(REDIS.getHost(),REDIS.getMappedPort(6379)));}
    @Autowired JdbcTemplate jdbc; @Autowired ScheduleWorkspaceService workspace; final JsonMapper mapper=JsonMapper.builder().build(); UUID project,user,other,property,selectProperty,option,group;
    @BeforeEach void setup(){project=UUID.randomUUID();user=UUID.randomUUID();other=UUID.randomUUID();property=UUID.randomUUID();selectProperty=UUID.randomUUID();option=UUID.randomUUID();group=UUID.randomUUID();jdbc.update("insert into identity.user_account(id,email,display_name) values (?,?,?)",user,user+"@test","User");jdbc.update("insert into identity.user_account(id,email,display_name) values (?,?,?)",other,other+"@test","Other");jdbc.update("insert into \"group\".erp_group(id,name) values (?,?)",group,"G");jdbc.update("insert into project.project(id,group_id,name) values (?,?,?)",project,group,"P");jdbc.update("insert into project.project_member(project_id,user_account_id,role) values (?,?,'MANAGER'),(?,?, 'MEMBER')",project,user,project,other);jdbc.update("insert into schedule.schedule_property(id,project_id,name,property_type,position) values (?,?,'Title', 'TEXT',0),(?,?,'State','SINGLE_SELECT',1)",property,project,selectProperty,project);jdbc.update("insert into schedule.schedule_property_option(id,property_id,label,color,position) values (?,?,'Open','blue',0)",option,selectProperty);for(int i=0;i<120;i++){var id=UUID.randomUUID();jdbc.update("insert into schedule.project_schedule(id,project_id,created_by,title,starts_at,ends_at,status) values (?,?,?, ?,?,?, 'CONFIRMED')",id,project,user,"Target "+i,Timestamp.from(Instant.parse("2099-01-01T00:00:00Z").plusSeconds(i*3600L)),Timestamp.from(Instant.parse("2099-01-01T01:00:00Z").plusSeconds(i*3600L)));jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,text_value) values (?,?,?,?, 'TEXT',?)",UUID.randomUUID(),project,id,property,"Target "+i);jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,option_id) values (?,?,?,?, 'SINGLE_SELECT',?)",UUID.randomUUID(),project,id,selectProperty,option);}}
    @AfterEach void cleanup(){jdbc.update("delete from schedule.schedule_property_value where project_id=?",project);jdbc.update("delete from schedule.schedule_saved_view where project_id=?",project);jdbc.update("delete from schedule.project_schedule where project_id=?",project);jdbc.update("delete from schedule.schedule_property_option where property_id=?",selectProperty);jdbc.update("delete from schedule.schedule_property where project_id=?",project);jdbc.update("delete from project.project_member where project_id=?",project);jdbc.update("delete from project.project where id=?",project);jdbc.update("delete from \"group\".erp_group where id=?",group);jdbc.update("delete from identity.user_account where id in (?,?)",user,other);}
    @Test void queryFiltersSortsCountsAndPagesCompleteScopeBeyondTwenty(){var config=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+property,Operator.CONTAINS,mapper.getNodeFactory().textNode("Target"))),List.of(new SortSpec("title",Direction.DESC)),selectProperty,null,List.of("title"));var result=workspace.query(project,new Query(config,Instant.parse("2098-12-31T00:00:00Z"),Instant.parse("2099-01-06T00:00:00Z"),2,20),user);assertThat(result.total()).isEqualTo(120);assertThat(result.records()).hasSize(20);assertThat(result.hasMore()).isTrue();assertThat(result.groups()).singleElement().satisfies(g->assertThat(g.count()).isEqualTo(120));assertThat(result.records().getFirst().schedule().title()).isGreaterThan(result.records().getLast().schedule().title());}
    @Test void workspacePersonalViewsArePrivateToOwner(){var id=UUID.randomUUID();var cfg=mapper.convertValue(new ViewConfig(ViewType.LIST,List.of(),List.of(),null,null,List.of("title")),Map.class);jdbc.update("insert into schedule.schedule_saved_view(id,project_id,name,scope,owner_id,config) values (?,?,?,'PERSONAL',?,?::jsonb)",id,project,"Private",user,mapper.writeValueAsString(cfg));assertThat(workspace.workspace(project,user).views()).extracting(View::id).contains(id.toString());assertThat(workspace.workspace(project,other).views()).extracting(View::id).doesNotContain(id.toString());}
    @Test void staleValuePatchIsRejectedBeforeMutation(){var id=UUID.randomUUID();jdbc.update("insert into schedule.project_schedule(id,project_id,created_by,title,starts_at,ends_at,status,row_version) values (?,?,?,'One',?,?, 'DRAFT',3)",id,project,user,Timestamp.from(Instant.now()),Timestamp.from(Instant.now().plusSeconds(60)));assertThatThrownBy(()->workspace.updateValues(project,id,new ValuesWrite(2L,Map.of()),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);assertThat(jdbc.queryForObject("select row_version from schedule.project_schedule where id=?",Long.class,id)).isEqualTo(3L);}
}
