package com.aierp;

import static org.assertj.core.api.Assertions.assertThat; import static org.assertj.core.api.Assertions.assertThatThrownBy;
import java.sql.Timestamp; import java.time.*; import java.util.*; import java.util.concurrent.*;
import com.aierp.schedule.*; import com.aierp.schedule.api.ScheduleController; import com.aierp.schedule.api.ScheduleWorkspaceController.*; import com.aierp.platform.web.ValidationFailure; import tools.jackson.databind.json.JsonMapper;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.orm.ObjectOptimisticLockingFailureException; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.testcontainers.containers.GenericContainer; import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.Container; import org.testcontainers.junit.jupiter.Testcontainers; import org.testcontainers.utility.DockerImageName;

/** PostgreSQL proof for complete-scope SQL and private-view isolation. */
@SpringBootTest @Testcontainers(disabledWithoutDocker=false)
class ScheduleWorkspacePostgresIntegrationTest {
    @Container static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:18.6");
    @Container static final GenericContainer<?> REDIS=new GenericContainer<>(DockerImageName.parse("redis:8.2.9")).withExposedPorts(6379);
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",POSTGRES::getJdbcUrl);r.add("spring.datasource.username",POSTGRES::getUsername);r.add("spring.datasource.password",POSTGRES::getPassword);r.add("spring.data.redis.url",()->"redis://%s:%d".formatted(REDIS.getHost(),REDIS.getMappedPort(6379)));r.add("spring.flyway.locations",()->"classpath:db/migration,classpath:db/integration-migration");}
    @Autowired JdbcTemplate jdbc; @Autowired ScheduleWorkspaceService workspace; final JsonMapper mapper=JsonMapper.builder().build(); UUID project,user,other,property,selectProperty,option,group; List<UUID> scheduleIds=new ArrayList<>();
    @BeforeEach void setup(){project=UUID.randomUUID();user=UUID.randomUUID();other=UUID.randomUUID();property=UUID.randomUUID();selectProperty=UUID.randomUUID();option=UUID.randomUUID();group=UUID.randomUUID();jdbc.update("insert into identity.user_account(id,email,display_name) values (?,?,?)",user,user+"@test","User");jdbc.update("insert into identity.user_account(id,email,display_name) values (?,?,?)",other,other+"@test","Other");jdbc.update("insert into \"group\".erp_group(id,name) values (?,?)",group,"G");jdbc.update("insert into project.project(id,group_id,name) values (?,?,?)",project,group,"P");jdbc.update("insert into project.project_member(project_id,user_account_id,role) values (?,?,'MANAGER'),(?,?, 'MEMBER')",project,user,project,other);jdbc.update("insert into schedule.schedule_property(id,project_id,name,property_type,position) values (?,?,'Title', 'TEXT',0),(?,?,'State','SINGLE_SELECT',1)",property,project,selectProperty,project);jdbc.update("insert into schedule.schedule_property_option(id,property_id,label,color,position) values (?,?,'Open','blue',0)",option,selectProperty);for(int i=0;i<120;i++){var id=UUID.randomUUID();scheduleIds.add(id);jdbc.update("insert into schedule.project_schedule(id,project_id,created_by,title,starts_at,ends_at,status) values (?,?,?, ?,?,?, 'CONFIRMED')",id,project,user,"Target "+i,Timestamp.from(Instant.parse("2099-01-01T00:00:00Z").plusSeconds(i*3600L)),Timestamp.from(Instant.parse("2099-01-01T01:00:00Z").plusSeconds(i*3600L)));jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,text_value) values (?,?,?,?, 'TEXT',?)",UUID.randomUUID(),project,id,property,"Target "+i);jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,option_id) values (?,?,?,?, 'SINGLE_SELECT',?)",UUID.randomUUID(),project,id,selectProperty,option);}}
    @AfterEach void cleanup(){jdbc.update("delete from schedule.schedule_dashboard_view where project_id=?",project);jdbc.update("delete from schedule.schedule_property_value where project_id=?",project);jdbc.update("delete from schedule.schedule_saved_view where project_id=?",project);jdbc.update("delete from schedule.schedule_acknowledgement where schedule_id in (select id from schedule.project_schedule where project_id=?)",project);jdbc.update("delete from schedule.schedule_participant where schedule_id in (select id from schedule.project_schedule where project_id=?)",project);jdbc.update("delete from schedule.schedule_change where schedule_id in (select id from schedule.project_schedule where project_id=?)",project);jdbc.update("delete from schedule.project_schedule where project_id=?",project);jdbc.update("delete from schedule.schedule_property_option where property_id in (select id from schedule.schedule_property where project_id=?)",project);jdbc.update("delete from schedule.schedule_property where project_id=?",project);jdbc.update("delete from project.project_member where project_id=?",project);jdbc.update("delete from project.project where id=?",project);jdbc.update("delete from \"group\".erp_group where id=?",group);jdbc.update("delete from identity.user_account where id in (?,?)",user,other);}
    @Test void queryFiltersSortsCountsAndPagesCompleteScopeBeyondTwenty(){var config=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+property,Operator.CONTAINS,mapper.getNodeFactory().textNode("Target"))),List.of(new SortSpec("title",Direction.DESC)),selectProperty,null,List.of("title"));var result=workspace.query(project,new Query(config,Instant.parse("2098-12-31T00:00:00Z"),Instant.parse("2099-01-06T00:00:00Z"),2,20),user);assertThat(result.total()).isEqualTo(120);assertThat(result.records()).hasSize(20);assertThat(result.hasMore()).isTrue();assertThat(result.groups()).singleElement().satisfies(g->assertThat(g.count()).isEqualTo(120));assertThat(result.records().getFirst().schedule().title()).isGreaterThan(result.records().getLast().schedule().title());}
    @Test void workspacePersonalViewsArePrivateToOwner(){var id=UUID.randomUUID();var cfg=mapper.convertValue(new ViewConfig(ViewType.LIST,List.of(),List.of(),null,null,List.of("title")),Map.class);jdbc.update("insert into schedule.schedule_saved_view(id,project_id,name,scope,owner_id,config) values (?,?,?,'PERSONAL',?,?::jsonb)",id,project,"Private",user,mapper.writeValueAsString(cfg));assertThat(workspace.workspace(project,user).views()).extracting(View::id).contains(id.toString());assertThat(workspace.workspace(project,other).views()).extracting(View::id).doesNotContain(id.toString());}
    @Test void staleValuePatchIsRejectedBeforeMutation(){var id=UUID.randomUUID();jdbc.update("insert into schedule.project_schedule(id,project_id,created_by,title,starts_at,ends_at,status,row_version) values (?,?,?,'One',?,?, 'DRAFT',3)",id,project,user,Timestamp.from(Instant.now()),Timestamp.from(Instant.now().plusSeconds(60)));assertThatThrownBy(()->workspace.updateValues(project,id,new ValuesWrite(2L,Map.of()),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);assertThat(jdbc.queryForObject("select row_version from schedule.project_schedule where id=?",Long.class,id)).isEqualTo(3L);}

    @Test void fiveTypedValuesRoundTripNoopNullArchiveAndForeignInputsAreEnforced(){
        var number=property("Number","NUMBER",2);var checkbox=property("Done","CHECKBOX",3);var date=property("Due","DATE",4);var archivedOption=UUID.randomUUID();jdbc.update("insert into schedule.schedule_property_option(id,property_id,label,color,position,archived) values (?,?,'Old','gray',1,true)",archivedOption,selectProperty);var schedule=scheduleIds.getFirst();
        var input=new LinkedHashMap<UUID,tools.jackson.databind.JsonNode>();input.put(property,mapper.getNodeFactory().textNode("updated"));input.put(number,mapper.getNodeFactory().numberNode(new java.math.BigDecimal("12.50")));input.put(checkbox,mapper.getNodeFactory().booleanNode(true));input.put(date,mapper.getNodeFactory().textNode("2099-02-03"));input.put(selectProperty,mapper.getNodeFactory().textNode(option.toString()));
        var first=workspace.updateValues(project,schedule,new ValuesWrite(0L,input),user);assertThat(first.values()).containsKeys(property,number,checkbox,date,selectProperty);assertThat(first.values().get(date).textValue()).isEqualTo("2099-02-03");long version=first.schedule().rowVersion();
        var noop=workspace.updateValues(project,schedule,new ValuesWrite(version,input),user);assertThat(noop.schedule().rowVersion()).isEqualTo(version);var clear=workspace.updateValues(project,schedule,new ValuesWrite(version,Map.of(number,mapper.getNodeFactory().nullNode())),user);assertThat(clear.values()).doesNotContainKey(number).containsKey(date);
        jdbc.update("update schedule.schedule_property set archived=true where id=?",selectProperty);var unchanged=workspace.updateValues(project,schedule,new ValuesWrite(clear.schedule().rowVersion(),Map.of(selectProperty,mapper.getNodeFactory().textNode(option.toString()))),user);assertThat(unchanged.values().get(selectProperty).textValue()).isEqualTo(option.toString());assertThatThrownBy(()->workspace.updateValues(project,schedule,new ValuesWrite(unchanged.schedule().rowVersion(),Map.of(selectProperty,mapper.getNodeFactory().textNode(archivedOption.toString()))),user)).isInstanceOf(ValidationFailure.class);
        assertThatThrownBy(()->workspace.updateValues(project,schedule,new ValuesWrite(unchanged.schedule().rowVersion(),Map.of(date,mapper.getNodeFactory().textNode("2099-2-3"))),user)).isInstanceOf(ValidationFailure.class);
    }

    @Test void atomicRecordRollbackAndCustomOnlyUpdatePreserveBusinessSemantics(){
        long schedulesBefore=jdbc.queryForObject("select count(*) from schedule.project_schedule where project_id=?",Long.class,project);long eventsBefore=jdbc.queryForObject("select count(*) from platform.event_publication",Long.class);var write=new ScheduleController.Write("Atomic",Instant.parse("2099-07-01T10:00:00Z"),Instant.parse("2099-07-01T11:00:00Z"),null,"Description",List.of(),List.of());
        assertThatThrownBy(()->workspace.createRecord(project,new RecordWrite(write,Map.of(UUID.randomUUID(),mapper.getNodeFactory().textNode("bad"))),user)).isInstanceOf(ValidationFailure.class);assertThat(jdbc.queryForObject("select count(*) from schedule.project_schedule where project_id=?",Long.class,project)).isEqualTo(schedulesBefore);assertThat(jdbc.queryForObject("select count(*) from platform.event_publication",Long.class)).isEqualTo(eventsBefore);
        var created=workspace.createRecord(project,new RecordWrite(write,Map.of(property,mapper.getNodeFactory().textNode("custom"))),user);assertThat(created.schedule().businessRevision()).isZero();var changed=workspace.updateValues(project,created.schedule().id(),new ValuesWrite(created.schedule().rowVersion(),Map.of(property,mapper.getNodeFactory().textNode("custom-2"))),user);assertThat(changed.schedule().businessRevision()).isZero();assertThat(changed.schedule().rowVersion()).isGreaterThan(created.schedule().rowVersion());assertThat(jdbc.queryForObject("select count(*) from schedule.schedule_change where schedule_id=?",Long.class,created.schedule().id())).isEqualTo(1L);
    }

    @Test void propertyViewMembershipAndDashboardVersionsRejectStaleOrUnauthorizedWrites() throws Exception {
        var current=workspace.workspace(project,user).properties().stream().filter(p->p.id().equals(selectProperty)).findFirst().orElseThrow();var writes=List.of(new PropertyWrite("State",SchedulePropertyEntity.PropertyType.SINGLE_SELECT,1,false,current.rowVersion(),List.of(new OptionWrite(option,"A","blue",false))),new PropertyWrite("State",SchedulePropertyEntity.PropertyType.SINGLE_SELECT,1,false,current.rowVersion(),List.of(new OptionWrite(option,"B","blue",false))));var pool=Executors.newFixedThreadPool(2);try{var start=new CountDownLatch(1);var futures=writes.stream().map(w->pool.submit(()->{start.await();try{workspace.updateProperty(project,selectProperty,w,user);return "ok";}catch(ObjectOptimisticLockingFailureException e){return "stale";}})).toList();start.countDown();assertThat(futures).extracting(f->f.get()).containsExactlyInAnyOrder("ok","stale");}finally{pool.shutdownNow();}
        var persisted=workspace.workspace(project,user).properties().stream().filter(p->p.id().equals(selectProperty)).findFirst().orElseThrow();assertThat(persisted.rowVersion()).isEqualTo(current.rowVersion()+1);assertThatThrownBy(()->workspace.updateProperty(project,selectProperty,writes.getFirst(),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);
        jdbc.update("update project.project_member set role='VIEWER' where project_id=? and user_account_id=?",project,other);var invalid=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+UUID.randomUUID(),Operator.EQ,mapper.getNodeFactory().textNode("x"))),List.of(),null,null,List.of("title"));assertThatThrownBy(()->workspace.createView(project,new ViewWrite("Private",Scope.PERSONAL,invalid,null,false),other)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);
        var first=workspace.dashboard(project,new DashboardWrite("builtin-calendar",0L),user);assertThat(first.dashboardRowVersion()).isEqualTo(1);assertThat(workspace.workspace(project,user).dashboardViewId()).isEqualTo("builtin-calendar");var second=workspace.dashboard(project,new DashboardWrite(null,1L),user);assertThat(second.dashboardRowVersion()).isEqualTo(2);assertThat(workspace.workspace(project,user).dashboardViewId()).isEqualTo("builtin-cards");assertThatThrownBy(()->workspace.dashboard(project,new DashboardWrite("builtin-list",1L),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);
    }

    @Test void literalContainsTypedFiltersGroupsExplainAndWorkspaceEventsUseCompleteScope(){
        var special=scheduleIds.getFirst();jdbc.update("update schedule.schedule_property_value set text_value=? where schedule_id=? and property_id=?","100%_! x' OR 1=1",special,property);for(String literal:List.of("%","_","!","x' OR 1=1")){var cfg=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+property,Operator.CONTAINS,mapper.getNodeFactory().textNode(literal))),List.of(new SortSpec("property:"+property,Direction.ASC)),selectProperty,null,List.of("title"));var result=workspace.query(project,new Query(cfg,null,null,0,100),user);assertThat(result.total()).isEqualTo(1);assertThat(result.records()).extracting(r->r.schedule().id()).containsExactly(special);assertThat(result.groups()).singleElement().satisfies(g->assertThat(g.count()).isEqualTo(1));}
        for(String bad:List.of("2099-2-03","2099-02-30")){var cfg=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+property("Temp","DATE",8),Operator.EQ,mapper.getNodeFactory().textNode(bad))),List.of(),null,null,List.of("title"));assertThatThrownBy(()->workspace.query(project,new Query(cfg,null,null,0,10),user)).isInstanceOf(ValidationFailure.class);}var statusCfg=new ViewConfig(ViewType.LIST,List.of(new Filter("status",Operator.EQ,mapper.getNodeFactory().textNode("NOT_A_STATUS"))),List.of(),null,null,List.of("title"));assertThatThrownBy(()->workspace.query(project,new Query(statusCfg,null,null,0,10),user)).isInstanceOf(ValidationFailure.class);
        assertThat(jdbc.queryForList("explain select s.id from schedule.project_schedule s where s.project_id=? order by s.starts_at nulls last,s.id limit 100",String.class,project)).isNotEmpty();long notifications=jdbc.queryForObject("select count(*) from notification.notification",Long.class);long projections=jdbc.queryForObject("select count(*) from calendar_integration.calendar_projection",Long.class);var made=workspace.createProperty(project,new PropertyWrite("Event",SchedulePropertyEntity.PropertyType.TEXT,9,false,null,List.of()),user);assertThat(jdbc.queryForObject("select count(*) from platform.event_publication where event_type='WORKSPACE_PROPERTY_CREATED' and aggregate_id=?",Long.class,made.id())).isEqualTo(1);assertThat(jdbc.queryForObject("select count(*) from audit.audit_log where aggregate_type='WORKSPACE' and aggregate_id=?",Long.class,made.id())).isEqualTo(1);assertThat(jdbc.queryForObject("select count(*) from notification.notification",Long.class)).isEqualTo(notifications);assertThat(jdbc.queryForObject("select count(*) from calendar_integration.calendar_projection",Long.class)).isEqualTo(projections);
    }

    private UUID property(String name,String type,int position){var id=UUID.randomUUID();jdbc.update("insert into schedule.schedule_property(id,project_id,name,property_type,position) values (?,?,?,?,?)",id,project,name,type,position);return id;}
}
