package com.aierp;

import static org.assertj.core.api.Assertions.assertThat; import static org.assertj.core.api.Assertions.assertThatThrownBy; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.doAnswer;
import java.sql.*; import java.time.*; import java.util.*; import java.util.concurrent.*; import javax.sql.DataSource;
import com.aierp.schedule.*; import com.aierp.schedule.api.ScheduleController; import com.aierp.schedule.api.ScheduleWorkspaceController.*; import com.aierp.platform.web.ValidationFailure; import tools.jackson.databind.json.JsonMapper;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.TestExecutionListeners; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.orm.ObjectOptimisticLockingFailureException; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;

/** PostgreSQL proof for complete-scope SQL and private-view isolation. */
@SpringBootTest
@org.springframework.context.annotation.Import(H2SessionConfiguration.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@TestExecutionListeners(listeners = NativeIntegrationRuntimeCleanupListener.class,
        mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS)
class ScheduleWorkspacePostgresIntegrationTest {
    private static final NativeIntegrationRuntime RUNTIME = NativeIntegrationRuntime.start();


    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",RUNTIME::postgresUrl);r.add("spring.datasource.username",RUNTIME::postgresUsername);r.add("spring.datasource.password",RUNTIME::postgresPassword);r.add("spring.flyway.locations",()->"classpath:db/migration,classpath:db/integration-migration");}
    @MockitoSpyBean JdbcTemplate jdbc; @Autowired DataSource dataSource; @Autowired ScheduleWorkspaceService workspace; @Autowired ScheduleService legacy; final JsonMapper mapper=JsonMapper.builder().build(); UUID project,user,other,property,selectProperty,option,group; List<UUID> scheduleIds=new ArrayList<>();
    @BeforeEach void setup(){project=UUID.randomUUID();user=UUID.randomUUID();other=UUID.randomUUID();property=UUID.randomUUID();selectProperty=UUID.randomUUID();option=UUID.randomUUID();group=UUID.randomUUID();jdbc.update("insert into identity.user_account(id,email,display_name) values (?,?,?)",user,user+"@test","User");jdbc.update("insert into identity.user_account(id,email,display_name) values (?,?,?)",other,other+"@test","Other");jdbc.update("insert into \"group\".erp_group(id,name) values (?,?)",group,"G");jdbc.update("insert into project.project(id,group_id,name) values (?,?,?)",project,group,"P");jdbc.update("insert into project.project_member(project_id,user_account_id,role) values (?,?,'MANAGER'),(?,?, 'MEMBER')",project,user,project,other);jdbc.update("insert into schedule.schedule_property(id,project_id,name,property_type,position) values (?,?,'Title', 'TEXT',0),(?,?,'State','SINGLE_SELECT',1)",property,project,selectProperty,project);jdbc.update("insert into schedule.schedule_property_option(id,property_id,label,color,position) values (?,?,'Open','blue',0)",option,selectProperty);for(int i=0;i<120;i++){var id=UUID.randomUUID();scheduleIds.add(id);jdbc.update("insert into schedule.project_schedule(id,project_id,created_by,title,starts_at,ends_at,status) values (?,?,?, ?,?,?, 'CONFIRMED')",id,project,user,"Target "+i,Timestamp.from(Instant.parse("2099-01-01T00:00:00Z").plusSeconds(i*3600L)),Timestamp.from(Instant.parse("2099-01-01T01:00:00Z").plusSeconds(i*3600L)));jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,text_value) values (?,?,?,?, 'TEXT',?)",UUID.randomUUID(),project,id,property,"Target "+i);jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,option_id) values (?,?,?,?, 'SINGLE_SELECT',?)",UUID.randomUUID(),project,id,selectProperty,option);}}
    @AfterEach void cleanup(){jdbc.update("delete from schedule.schedule_dashboard_view where project_id=?",project);jdbc.update("delete from schedule.schedule_property_value where project_id=?",project);jdbc.update("delete from schedule.schedule_saved_view where project_id=?",project);jdbc.update("delete from schedule.schedule_acknowledgement where schedule_id in (select id from schedule.project_schedule where project_id=?)",project);jdbc.update("delete from schedule.schedule_participant where schedule_id in (select id from schedule.project_schedule where project_id=?)",project);jdbc.update("delete from schedule.schedule_change where schedule_id in (select id from schedule.project_schedule where project_id=?)",project);jdbc.update("delete from schedule.project_schedule where project_id=?",project);jdbc.update("delete from schedule.schedule_property_option where property_id in (select id from schedule.schedule_property where project_id=?)",project);jdbc.update("delete from schedule.schedule_property where project_id=?",project);jdbc.update("delete from project.project_member where project_id=?",project);jdbc.update("delete from project.project where id=?",project);jdbc.update("delete from \"group\".erp_group where id=?",group);jdbc.update("delete from identity.user_account where id in (?,?)",user,other);}
    @Test void queryFiltersSortsCountsAndPagesCompleteScopeBeyondTwenty(){var config=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+property,Operator.CONTAINS,mapper.getNodeFactory().textNode("Target"))),List.of(new SortSpec("title",Direction.DESC)),selectProperty,null,List.of("title"));var result=workspace.query(project,new Query(config,Instant.parse("2098-12-31T00:00:00Z"),Instant.parse("2099-01-06T00:00:00Z"),2,20),user);assertThat(result.total()).isEqualTo(120);assertThat(result.records()).hasSize(20);assertThat(result.hasMore()).isTrue();assertThat(result.groups()).singleElement().satisfies(g->assertThat(g.count()).isEqualTo(120));assertThat(result.records().getFirst().schedule().title()).isGreaterThan(result.records().getLast().schedule().title());}
    @Test void workspacePersonalViewsArePrivateToOwner(){var id=UUID.randomUUID();var cfg=mapper.convertValue(new ViewConfig(ViewType.LIST,List.of(),List.of(),null,null,List.of("title")),Map.class);jdbc.update("insert into schedule.schedule_saved_view(id,project_id,name,scope,owner_id,config) values (?,?,?,'PERSONAL',?,?::jsonb)",id,project,"Private",user,mapper.writeValueAsString(cfg));assertThat(workspace.workspace(project,user).views()).extracting(View::id).contains(id.toString());assertThat(workspace.workspace(project,other).views()).extracting(View::id).doesNotContain(id.toString());}
    @Test void staleValuePatchIsRejectedBeforeMutation(){var id=UUID.randomUUID();jdbc.update("insert into schedule.project_schedule(id,project_id,created_by,title,starts_at,ends_at,status,row_version) values (?,?,?,'One',?,?, 'DRAFT',3)",id,project,user,Timestamp.from(Instant.now()),Timestamp.from(Instant.now().plusSeconds(60)));assertThatThrownBy(()->workspace.updateValues(project,id,new ValuesWrite(2L,Map.of()),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);assertThat(jdbc.queryForObject("select row_version from schedule.project_schedule where id=?",Long.class,id)).isEqualTo(3L);}

    @Test void fiveTypedValuesRoundTripNoopNullArchiveAndForeignInputsAreEnforced(){
        var number=property("Number","NUMBER",2);var checkbox=property("Done","CHECKBOX",3);var date=property("Due","DATE",4);var archivedOption=UUID.randomUUID();jdbc.update("insert into schedule.schedule_property_option(id,property_id,label,color,position,archived) values (?,?,'Old','gray',1,true)",archivedOption,selectProperty);var schedule=scheduleIds.getFirst();
        var input=new LinkedHashMap<UUID,tools.jackson.databind.JsonNode>();input.put(property,mapper.getNodeFactory().textNode("updated"));input.put(number,mapper.getNodeFactory().numberNode(new java.math.BigDecimal("12.50")));input.put(checkbox,mapper.getNodeFactory().booleanNode(true));input.put(date,mapper.getNodeFactory().textNode("2099-02-03"));input.put(selectProperty,mapper.getNodeFactory().textNode(option.toString()));
        var first=workspace.updateValues(project,schedule,new ValuesWrite(0L,input),user);assertThat(first.values()).containsKeys(property,number,checkbox,date,selectProperty);assertThat(first.values().get(date).textValue()).isEqualTo("2099-02-03");long version=first.schedule().rowVersion();
        var noop=workspace.updateValues(project,schedule,new ValuesWrite(version,input),user);assertThat(noop.schedule().rowVersion()).isEqualTo(version);long numericEvents=jdbc.queryForObject("select count(*) from platform.event_publication where event_type='WORKSPACE_CUSTOM_VALUE_UPDATED' and aggregate_id=?",Long.class,schedule);for(var json:List.of("12.5","12.50")){var equivalent=workspace.updateValues(project,schedule,new ValuesWrite(version,Map.of(number,read(json))),user);assertThat(equivalent.schedule().rowVersion()).isEqualTo(version);}jdbc.update("update schedule.schedule_property_value set number_value=12 where schedule_id=? and property_id=?",schedule,number);var integerNode=workspace.updateValues(project,schedule,new ValuesWrite(version,Map.of(number,read("12"))),user);assertThat(integerNode.schedule().rowVersion()).isEqualTo(version);jdbc.update("update schedule.schedule_property set archived=true where id=?",number);var archivedNumber=workspace.updateValues(project,schedule,new ValuesWrite(version,Map.of(number,read("12.0"))),user);assertThat(archivedNumber.schedule().rowVersion()).isEqualTo(version);assertThat(jdbc.queryForObject("select count(*) from platform.event_publication where event_type='WORKSPACE_CUSTOM_VALUE_UPDATED' and aggregate_id=?",Long.class,schedule)).isEqualTo(numericEvents);jdbc.update("update schedule.schedule_property set archived=false where id=?",number);var clear=workspace.updateValues(project,schedule,new ValuesWrite(version,Map.of(number,mapper.getNodeFactory().nullNode())),user);assertThat(clear.values()).doesNotContainKey(number).containsKey(date);
        jdbc.update("update schedule.schedule_property set archived=true where id=?",selectProperty);var unchanged=workspace.updateValues(project,schedule,new ValuesWrite(clear.schedule().rowVersion(),Map.of(selectProperty,mapper.getNodeFactory().textNode(option.toString()))),user);assertThat(unchanged.values().get(selectProperty).textValue()).isEqualTo(option.toString());assertThatThrownBy(()->workspace.updateValues(project,schedule,new ValuesWrite(unchanged.schedule().rowVersion(),Map.of(selectProperty,mapper.getNodeFactory().textNode(archivedOption.toString()))),user)).isInstanceOf(ValidationFailure.class);
        assertThatThrownBy(()->workspace.updateValues(project,schedule,new ValuesWrite(unchanged.schedule().rowVersion(),Map.of(date,mapper.getNodeFactory().textNode("2099-2-3"))),user)).isInstanceOf(ValidationFailure.class);
    }

    @Test void atomicRecordRollbackAndCustomOnlyUpdatePreserveBusinessSemantics(){
        long schedulesBefore=jdbc.queryForObject("select count(*) from schedule.project_schedule where project_id=?",Long.class,project);long eventsBefore=jdbc.queryForObject("select count(*) from platform.event_publication",Long.class);var write=new ScheduleController.Write("Atomic",Instant.parse("2099-07-01T10:00:00Z"),Instant.parse("2099-07-01T11:00:00Z"),null,"Description",List.of(),List.of());
        assertThatThrownBy(()->workspace.createRecord(project,new RecordWrite(write,Map.of(UUID.randomUUID(),mapper.getNodeFactory().textNode("bad"))),user)).isInstanceOf(ValidationFailure.class);assertThat(jdbc.queryForObject("select count(*) from schedule.project_schedule where project_id=?",Long.class,project)).isEqualTo(schedulesBefore);assertThat(jdbc.queryForObject("select count(*) from platform.event_publication",Long.class)).isEqualTo(eventsBefore);
        var created=workspace.createRecord(project,new RecordWrite(write,Map.of(property,mapper.getNodeFactory().textNode("custom"))),user);assertThat(created.schedule().businessRevision()).isZero();var changed=workspace.updateValues(project,created.schedule().id(),new ValuesWrite(created.schedule().rowVersion(),Map.of(property,mapper.getNodeFactory().textNode("custom-2"))),user);assertThat(changed.schedule().businessRevision()).isZero();assertThat(changed.schedule().rowVersion()).isGreaterThan(created.schedule().rowVersion());assertThat(jdbc.queryForObject("select count(*) from schedule.schedule_change where schedule_id=?",Long.class,created.schedule().id())).isEqualTo(1L);
    }

    @Test void propertyViewMembershipAndDashboardVersionsRejectStaleOrUnauthorizedWrites() throws Exception {
        var current=workspace.workspace(project,user).properties().stream().filter(p->p.id().equals(selectProperty)).findFirst().orElseThrow();var writes=List.of(new PropertyWrite("State",SchedulePropertyEntity.PropertyType.SINGLE_SELECT,1,false,current.rowVersion(),List.of(new OptionWrite(option,"A","blue",false))),new PropertyWrite("State",SchedulePropertyEntity.PropertyType.SINGLE_SELECT,1,false,current.rowVersion(),List.of(new OptionWrite(option,"B","blue",false))));var pool=Executors.newFixedThreadPool(2);try{var start=new CountDownLatch(1);var futures=writes.stream().map(w->pool.submit(()->{start.await();try{workspace.updateProperty(project,selectProperty,w,user);return "ok";}catch(ObjectOptimisticLockingFailureException e){return "stale";}})).toList();start.countDown();assertThat(futures).extracting(f->f.get()).containsExactlyInAnyOrder("ok","stale");}finally{pool.shutdownNow();}
        var persisted=workspace.workspace(project,user).properties().stream().filter(p->p.id().equals(selectProperty)).findFirst().orElseThrow();assertThat(persisted.rowVersion()).isEqualTo(current.rowVersion()+1);assertThatThrownBy(()->workspace.updateProperty(project,selectProperty,writes.getFirst(),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);
        jdbc.update("update project.project_member set role='VIEWER' where project_id=? and user_account_id=?",project,other);var invalid=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+UUID.randomUUID(),Operator.EQ,mapper.getNodeFactory().textNode("x"))),List.of(),null,null,List.of("title"));assertThatThrownBy(()->workspace.createView(project,new ViewWrite("Private",Scope.PERSONAL,invalid,null,false),other)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);
        var first=workspace.dashboard(project,new DashboardWrite("builtin-calendar",0L),user);assertThat(first.dashboardRowVersion()).isEqualTo(1);assertThat(workspace.workspace(project,user).dashboardViewId()).isEqualTo("builtin-calendar");var second=workspace.dashboard(project,new DashboardWrite(null,1L),user);assertThat(second.dashboardRowVersion()).isEqualTo(2);assertThat(workspace.workspace(project,user).dashboardViewId()).isEqualTo("builtin-cards");assertThatThrownBy(()->workspace.dashboard(project,new DashboardWrite("builtin-list",1L),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);
    }

    @Test void literalContainsTypedFiltersGroupsExplainAndWorkspaceEventsUseCompleteScope(){
        var special=scheduleIds.getFirst();jdbc.update("update schedule.schedule_property_value set text_value=? where schedule_id=? and property_id=?","100%_! x' OR 1=1",special,property);for(String literal:List.of("%","_","!","x' OR 1=1")){var cfg=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+property,Operator.CONTAINS,mapper.getNodeFactory().textNode(literal))),List.of(new SortSpec("property:"+property,Direction.ASC)),selectProperty,null,List.of("title"));var result=workspace.query(project,new Query(cfg,null,null,0,100),user);assertThat(result.total()).isEqualTo(1);assertThat(result.records()).extracting(r->r.schedule().id()).containsExactly(special);assertThat(result.groups()).singleElement().satisfies(g->assertThat(g.count()).isEqualTo(1));}
        for(String bad:List.of("2099-2-03","2099-02-30")){var cfg=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+property("Temp","DATE",8),Operator.EQ,mapper.getNodeFactory().textNode(bad))),List.of(),null,null,List.of("title"));assertThatThrownBy(()->workspace.query(project,new Query(cfg,null,null,0,10),user)).isInstanceOf(ValidationFailure.class);}var statusCfg=new ViewConfig(ViewType.LIST,List.of(new Filter("status",Operator.EQ,mapper.getNodeFactory().textNode("NOT_A_STATUS"))),List.of(),null,null,List.of("title"));assertThatThrownBy(()->workspace.query(project,new Query(statusCfg,null,null,0,10),user)).isInstanceOf(ValidationFailure.class);
        long notifications=jdbc.queryForObject("select count(*) from notification.notification",Long.class);long projections=jdbc.queryForObject("select count(*) from calendar_integration.calendar_projection",Long.class);var made=workspace.createProperty(project,new PropertyWrite("Event",SchedulePropertyEntity.PropertyType.TEXT,9,false,null,null),user);assertThat(jdbc.queryForObject("select count(*) from platform.event_publication where event_type='WORKSPACE_PROPERTY_CREATED' and aggregate_id=?",Long.class,made.id())).isEqualTo(1);assertThat(jdbc.queryForObject("select count(*) from audit.audit_log where aggregate_type='WORKSPACE' and aggregate_id=?",Long.class,made.id())).isEqualTo(1);assertThat(jdbc.queryForObject("select count(*) from notification.notification",Long.class)).isEqualTo(notifications);assertThat(jdbc.queryForObject("select count(*) from calendar_integration.calendar_projection",Long.class)).isEqualTo(projections);
    }

    @Test void successfulTypedFixedFiltersNullsLastUuidTiesAndSelectOrderUsePostgres(){
        var number=property("Order","NUMBER",5);var checkbox=property("Flag","CHECKBOX",6);var date=property("Day","DATE",7);var later=UUID.randomUUID();jdbc.update("insert into schedule.schedule_property_option(id,property_id,label,color,position) values (?,?,'Later','green',1)",later,selectProperty);var first=scheduleIds.get(0);var second=scheduleIds.get(1);jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,number_value) values (?,?,?,?, 'NUMBER',10)",UUID.randomUUID(),project,first,number);jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,checkbox_value) values (?,?,?,?, 'CHECKBOX',true)",UUID.randomUUID(),project,first,checkbox);jdbc.update("insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,date_value) values (?,?,?,?, 'DATE',DATE '2099-02-03')",UUID.randomUUID(),project,first,date);jdbc.update("update schedule.schedule_property_value set option_id=? where schedule_id=? and property_id=?",later,second,selectProperty);
        var filters=List.of(new Filter("property:"+property,Operator.EQ,mapper.getNodeFactory().textNode("Target 0")),new Filter("property:"+number,Operator.GTE,mapper.getNodeFactory().numberNode(10)),new Filter("property:"+checkbox,Operator.EQ,mapper.getNodeFactory().booleanNode(true)),new Filter("property:"+date,Operator.EQ,mapper.getNodeFactory().textNode("2099-02-03")),new Filter("property:"+selectProperty,Operator.EQ,mapper.getNodeFactory().textNode(option.toString())),new Filter("startsAt",Operator.GTE,mapper.getNodeFactory().textNode("2099-01-01T00:00:00Z")),new Filter("endsAt",Operator.LTE,mapper.getNodeFactory().textNode("2099-01-01T01:00:00Z")),new Filter("status",Operator.EQ,mapper.getNodeFactory().textNode("CONFIRMED")),new Filter("createdBy",Operator.EQ,mapper.getNodeFactory().textNode(user.toString())));var typed=workspace.query(project,new Query(new ViewConfig(ViewType.LIST,filters,List.of(),null,null,List.of("title")),null,null,0,10),user);assertThat(typed.records()).extracting(r->r.schedule().id()).containsExactly(first);
        var sorted=workspace.query(project,new Query(new ViewConfig(ViewType.LIST,List.of(),List.of(new SortSpec("property:"+number,Direction.ASC)),null,null,List.of("title")),null,null,0,100),user);assertThat(sorted.records().getFirst().schedule().id()).isEqualTo(first);assertThat(sorted.records().subList(1,sorted.records().size())).extracting(r->r.schedule().id().toString()).isSorted();jdbc.update("delete from schedule.schedule_property_value where property_id=? and schedule_id not in (?,?)",selectProperty,first,second);var selectSorted=workspace.query(project,new Query(new ViewConfig(ViewType.LIST,List.of(),List.of(new SortSpec("property:"+selectProperty,Direction.ASC)),null,null,List.of("title")),null,null,0,100),user);assertThat(selectSorted.records().indexOf(selectSorted.records().stream().filter(r->r.schedule().id().equals(first)).findFirst().orElseThrow())).isLessThan(selectSorted.records().indexOf(selectSorted.records().stream().filter(r->r.schedule().id().equals(second)).findFirst().orElseThrow()));
    }

    @Test void repeatableReadCountPageAndGroupsRemainOneServiceSnapshotDuringConcurrentInsert() throws Exception {
        var counted=new CountDownLatch(1);var release=new CountDownLatch(1);doAnswer(call->{var result=call.callRealMethod();if(((String)call.getArgument(0)).startsWith("select count(*) from (select s.id")){counted.countDown();assertThat(release.await(10,TimeUnit.SECONDS)).isTrue();}return result;}).when(jdbc).queryForObject(startsWith("select count(*) from (select s.id"),eq(Long.class),any(Object[].class));
        var inserted=UUID.randomUUID();var config=new ViewConfig(ViewType.LIST,List.of(),List.of(new SortSpec("title",Direction.ASC)),selectProperty,null,List.of("title"));try(var pool=Executors.newFixedThreadPool(2)){var reader=pool.submit(()->workspace.query(project,new Query(config,null,null,0,100),user));assertThat(counted.await(10,TimeUnit.SECONDS)).isTrue();try(var writer=dataSource.getConnection()){writer.setAutoCommit(false);execute(writer,"insert into schedule.project_schedule(id,project_id,created_by,title,starts_at,ends_at,status) values (?,?,?,'Concurrent',?,?,'CONFIRMED')",inserted,project,user,Timestamp.from(Instant.parse("2099-01-02T00:00:00Z")),Timestamp.from(Instant.parse("2099-01-02T01:00:00Z")));execute(writer,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,option_id) values (?,?,?,?, 'SINGLE_SELECT',?)",UUID.randomUUID(),project,inserted,selectProperty,option);writer.commit();}release.countDown();var result=reader.get(10,TimeUnit.SECONDS);assertThat(result.total()).isEqualTo(120);assertThat(result.records()).hasSize(100).extracting(r->r.schedule().id()).doesNotContain(inserted);assertThat(result.groups()).singleElement().satisfies(g->assertThat(g.count()).isEqualTo(120));}assertThat(jdbc.queryForObject("select count(*) from schedule.project_schedule where project_id=?",Long.class,project)).isEqualTo(121L);
    }

    @Test void actualTypedPageAndGroupSqlPlansStayWithinRepresentativeWorkBound(){
        var pageSql=new java.util.concurrent.atomic.AtomicReference<String>();var pageArgs=new java.util.concurrent.atomic.AtomicReference<Object[]>();var groupSql=new java.util.concurrent.atomic.AtomicReference<String>();var groupArgs=new java.util.concurrent.atomic.AtomicReference<Object[]>();doAnswer(call->{var sql=(String)call.getArgument(0);if(sql.startsWith("select s.id")){pageSql.set(sql);pageArgs.set((Object[])call.getRawArguments()[2]);}return call.callRealMethod();}).when(jdbc).queryForList(anyString(),eq(UUID.class),any(Object[].class));doAnswer(call->{var sql=(String)call.getArgument(0);if(sql.startsWith("select g.id")){groupSql.set(sql);groupArgs.set((Object[])call.getRawArguments()[1]);}return call.callRealMethod();}).when(jdbc).queryForList(anyString(),any(Object[].class));
        var config=new ViewConfig(ViewType.LIST,List.of(new Filter("property:"+property,Operator.CONTAINS,mapper.getNodeFactory().textNode("Target"))),List.of(new SortSpec("property:"+property,Direction.ASC)),selectProperty,null,List.of("title"));var result=workspace.query(project,new Query(config,null,null,0,100),user);assertThat(result.total()).isEqualTo(120);explain("typed-page-before-analyze",pageSql.get(),pageArgs.get());explain("typed-group-before-analyze",groupSql.get(),groupArgs.get());jdbc.execute("analyze schedule.project_schedule, schedule.schedule_property, schedule.schedule_property_option, schedule.schedule_property_value");var pagePlan=explain("typed-page",pageSql.get(),pageArgs.get());var groupPlan=explain("typed-group",groupSql.get(),groupArgs.get());assertPlanBound(pagePlan,100,5000);assertPlanBound(groupPlan,10,5000);
    }

    @Test void invalidAtomicUpdateRollsBackFixedParticipantsAcknowledgementProjectionAndLegacyStaleWrite(){
        var draft=legacy.create(project,new ScheduleController.Write("Before",Instant.parse("2099-08-01T10:00:00Z"),Instant.parse("2099-08-01T11:00:00Z"),null,"D",List.of(other),List.of()),user);var confirmed=legacy.confirm(project,draft.id(),new ScheduleController.Revision(draft.rowVersion()),user);legacy.acknowledge(project,draft.id(),new ScheduleController.Acknowledge(confirmed.businessRevision()),other);var calendar=jdbc.queryForObject("select id from calendar_integration.project_calendar where project_id=?",UUID.class,project);var projection=jdbc.queryForObject("select id from calendar_integration.calendar_projection where schedule_id=? and project_calendar_id=?",UUID.class,draft.id(),calendar);jdbc.update("update calendar_integration.calendar_projection set status='SYNCED',business_revision=? where id=?",confirmed.businessRevision(),projection);long ackBefore=jdbc.queryForObject("select count(*) from schedule.schedule_acknowledgement where schedule_id=?",Long.class,draft.id());
        var invalid=new ScheduleController.Write("After",confirmed.startsAt(),confirmed.endsAt(),confirmed.rowVersion(),"Changed",List.of(),List.of());assertThatThrownBy(()->workspace.updateRecord(project,draft.id(),new RecordWrite(invalid,Map.of(UUID.randomUUID(),mapper.getNodeFactory().textNode("bad"))),user)).isInstanceOf(ValidationFailure.class);var unchanged=legacy.detail(project,draft.id(),user);assertThat(unchanged.title()).isEqualTo("Before");assertThat(unchanged.participants()).extracting(ScheduleController.Participant::memberUserId).contains(other);assertThat(jdbc.queryForObject("select count(*) from schedule.schedule_acknowledgement where schedule_id=?",Long.class,draft.id())).isEqualTo(ackBefore);assertThat(jdbc.queryForMap("select status,business_revision from calendar_integration.calendar_projection where id=?",projection)).containsEntry("status","SYNCED").containsEntry("business_revision",confirmed.businessRevision());
        var custom=workspace.updateValues(project,draft.id(),new ValuesWrite(unchanged.rowVersion(),Map.of(property,mapper.getNodeFactory().textNode("changed"))),user);assertThat(custom.schedule().businessRevision()).isEqualTo(confirmed.businessRevision());assertThat(jdbc.queryForObject("select count(*) from schedule.schedule_acknowledgement where schedule_id=?",Long.class,draft.id())).isEqualTo(ackBefore);assertThat(jdbc.queryForMap("select status,business_revision from calendar_integration.calendar_projection where id=?",projection)).containsEntry("status","SYNCED").containsEntry("business_revision",confirmed.businessRevision());assertThatThrownBy(()->legacy.update(project,draft.id(),new ScheduleController.Write("Stale",confirmed.startsAt(),confirmed.endsAt(),unchanged.rowVersion(),"D",List.of(other),List.of()),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);
    }

    @Test void viewOwnershipRevocationStaleWritesAndDashboardReferenceRulesAreEnforced(){
        var cfg=new ViewConfig(ViewType.CARDS,List.of(),List.of(new SortSpec("startsAt",Direction.ASC)),null,null,List.of("title"));var personal=workspace.createView(project,new ViewWrite("Mine",Scope.PERSONAL,cfg,null,false),other);assertThatThrownBy(()->workspace.updateView(project,UUID.fromString(personal.id()),new ViewWrite("Wrong",Scope.PERSONAL,cfg,personal.rowVersion(),false),user)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);assertThatThrownBy(()->workspace.updateView(project,UUID.fromString(personal.id()),new ViewWrite("Stale",Scope.PERSONAL,cfg,personal.rowVersion()-1,false),other)).isInstanceOf(ObjectOptimisticLockingFailureException.class);jdbc.update("update project.project_member set role='VIEWER' where project_id=? and user_account_id=?",project,other);assertThatThrownBy(()->workspace.updateView(project,UUID.fromString(personal.id()),new ViewWrite("Demoted",Scope.PERSONAL,cfg,personal.rowVersion(),false),other)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);jdbc.update("delete from project.project_member where project_id=? and user_account_id=?",project,other);assertThatThrownBy(()->workspace.updateView(project,UUID.fromString(personal.id()),new ViewWrite("Revoked",Scope.PERSONAL,cfg,personal.rowVersion(),false),other)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);
        var shared=workspace.createView(project,new ViewWrite("Shared",Scope.SHARED,cfg,null,false),user);var archived=workspace.createView(project,new ViewWrite("Archived",Scope.SHARED,cfg,null,true),user);assertThatThrownBy(()->workspace.updateView(project,UUID.fromString(shared.id()),new ViewWrite("Stale",Scope.SHARED,cfg,shared.rowVersion()-1,false),user)).isInstanceOf(ObjectOptimisticLockingFailureException.class);jdbc.update("insert into project.project_member(project_id,user_account_id,role) values (?,?,'MEMBER')",project,other);assertThatThrownBy(()->workspace.updateView(project,UUID.fromString(shared.id()),new ViewWrite("Member",Scope.SHARED,cfg,shared.rowVersion(),false),other)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);jdbc.update("delete from project.project_member where project_id=? and user_account_id=?",project,other);var foreignProject=UUID.randomUUID();var foreignView=UUID.randomUUID();jdbc.update("insert into project.project(id,group_id,name) values (?,?,'Foreign')",foreignProject,group);jdbc.update("insert into schedule.schedule_saved_view(id,project_id,name,scope,owner_id,config) values (?,?,'Foreign','SHARED',?,?::jsonb)",foreignView,foreignProject,user,mapper.writeValueAsString(mapper.convertValue(cfg,Map.class)));assertThatThrownBy(()->workspace.dashboard(project,new DashboardWrite(foreignView.toString(),0L),user)).isInstanceOf(ValidationFailure.class);jdbc.update("delete from schedule.schedule_saved_view where project_id=?",foreignProject);jdbc.update("delete from project.project where id=?",foreignProject);assertThatThrownBy(()->workspace.dashboard(project,new DashboardWrite(personal.id(),0L),user)).isInstanceOf(ValidationFailure.class);assertThatThrownBy(()->workspace.dashboard(project,new DashboardWrite(archived.id(),0L),user)).isInstanceOf(ValidationFailure.class);var selected=workspace.dashboard(project,new DashboardWrite(shared.id(),0L),user);assertThat(selected.dashboardRowVersion()).isEqualTo(1);workspace.updateView(project,UUID.fromString(shared.id()),new ViewWrite("Shared",Scope.SHARED,cfg,shared.rowVersion(),true),user);var reload=workspace.workspace(project,user);assertThat(reload.dashboardViewId()).isEqualTo(shared.id());assertThat(reload.views()).extracting(View::id).doesNotContain(shared.id());
        var current=workspace.workspace(project,user).properties().stream().filter(p->p.id().equals(selectProperty)).findFirst().orElseThrow();var optionState=current.options().getFirst();var noop=workspace.updateProperty(project,selectProperty,new PropertyWrite(current.name(),current.type(),current.position(),current.archived(),current.rowVersion(),List.of(new OptionWrite(optionState.id(),optionState.label(),optionState.color(),optionState.archived()))),user);assertThat(noop.rowVersion()).isEqualTo(current.rowVersion());assertThat(jdbc.queryForObject("select row_version from schedule.schedule_property where id=?",Long.class,selectProperty)).isEqualTo(current.rowVersion());
    }

    private tools.jackson.databind.JsonNode read(String json){try{return mapper.readTree(json);}catch(Exception e){throw new IllegalArgumentException(e);}}
    private static void execute(Connection db,String sql,Object... values)throws SQLException{try(var statement=db.prepareStatement(sql)){for(int i=0;i<values.length;i++)statement.setObject(i+1,values[i]);statement.executeUpdate();}}
    private PlanEvidence explain(String label,String sql,Object[] args){assertThat(sql).isNotBlank();var raw=jdbc.queryForObject("explain (analyze, buffers, format json) "+sql,String.class,args);var root=read(raw).get(0);var plan=root.path("Plan");var evidence=new PlanEvidence(label,sql,Arrays.toString(args),raw,root.path("Execution Time").doubleValue(),plan.path("Actual Rows").longValue(),plan.path("Shared Hit Blocks").longValue()+plan.path("Shared Read Blocks").longValue());System.out.println("WORKSPACE_PLAN "+label+" SQL="+sql+" ARGS="+evidence.args+" METRICS={executionMs="+evidence.executionMs+",actualRows="+evidence.actualRows+",rootSharedBlocks="+evidence.rootSharedBlocks+"} JSON="+raw);return evidence;}
    private void assertPlanBound(PlanEvidence evidence,long maxRows,long maxBlocks){assertThat(evidence.executionMs).as(evidence.label+" execution ms").isLessThan(1000d);assertThat(evidence.actualRows).as(evidence.label+" root actual rows").isLessThanOrEqualTo(maxRows);assertThat(evidence.rootSharedBlocks).as(evidence.label+" root inclusive shared blocks").isLessThanOrEqualTo(maxBlocks);}
    private record PlanEvidence(String label,String sql,String args,String raw,double executionMs,long actualRows,long rootSharedBlocks){}
    private UUID property(String name,String type,int position){var id=UUID.randomUUID();jdbc.update("insert into schedule.schedule_property(id,project_id,name,property_type,position) values (?,?,?,?,?)",id,project,name,type,position);return id;}

}
