package com.aierp;

import static org.assertj.core.api.Assertions.assertThat;
import java.sql.*; import java.time.Instant; import java.util.UUID;
import org.flywaydb.core.Flyway; import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.Container; import org.testcontainers.junit.jupiter.Testcontainers;

/** Real PostgreSQL upgrade proof for the additive schedule workspace boundary. */
@Testcontainers
class V9ScheduleWorkspaceMigrationIntegrationTest {
    @Container static final PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:18.6");
    @Test void v8RowsSurviveAndWorkspaceTablesAreEmptyAndConstrained() throws Exception {
        var database="aierp_v8_to_v9_"+UUID.randomUUID().toString().replace("-","");
        var adminUrl="jdbc:postgresql://%s:%d/postgres".formatted(postgres.getHost(),postgres.getMappedPort(5432));
        var databaseUrl="jdbc:postgresql://%s:%d/%s".formatted(postgres.getHost(),postgres.getMappedPort(5432),database);
        try(var admin=DriverManager.getConnection(adminUrl,postgres.getUsername(),postgres.getPassword())){admin.createStatement().execute("CREATE DATABASE "+identifier(database));}
        var user=UUID.randomUUID();var group=UUID.randomUUID();var project=UUID.randomUUID();var schedule=UUID.randomUUID();var participant=UUID.randomUUID();var change=UUID.randomUUID();var calendar=UUID.randomUUID();var projection=UUID.randomUUID();
        try {
            Flyway.configure().dataSource(databaseUrl,postgres.getUsername(),postgres.getPassword()).locations("classpath:db/migration").target("8").load().migrate();
            try(var db=DriverManager.getConnection(databaseUrl,postgres.getUsername(),postgres.getPassword())){execute(db,"INSERT INTO identity.user_account(id,email,display_name) VALUES (?,?,?)",user,"legacy@example.test","Legacy");execute(db,"INSERT INTO \"group\".erp_group(id,name) VALUES (?,?)",group,"Legacy");execute(db,"INSERT INTO project.project(id,group_id,name) VALUES (?,?,?)",project,group,"Legacy project");execute(db,"INSERT INTO project.project_member(project_id,user_account_id,role) VALUES (?,?,'MANAGER')",project,user);execute(db,"INSERT INTO schedule.project_schedule(id,project_id,created_by,title,starts_at,ends_at,status,business_revision) VALUES (?,?,?,'Legacy',?,?,'CONFIRMED',2)",schedule,project,user,Timestamp.from(Instant.parse("2099-01-01T10:00:00Z")),Timestamp.from(Instant.parse("2099-01-01T11:00:00Z")));execute(db,"INSERT INTO schedule.schedule_participant(schedule_id,id,member_user_account_id) VALUES (?,?,?)",schedule,participant,user);execute(db,"INSERT INTO schedule.schedule_acknowledgement(schedule_id,user_account_id,business_revision) VALUES (?,?,2)",schedule,user);execute(db,"INSERT INTO schedule.schedule_change(id,schedule_id,business_revision,change_type,changed_by) VALUES (?,?,2,'SCHEDULE_CHANGED',?)",change,schedule,user);execute(db,"INSERT INTO calendar_integration.project_calendar(id,project_id) VALUES (?,?)",calendar,project);execute(db,"INSERT INTO calendar_integration.calendar_projection(id,schedule_id,project_calendar_id,status,business_revision) VALUES (?,?,?,'SYNCED',2)",projection,schedule,calendar);}
            Flyway.configure().dataSource(databaseUrl,postgres.getUsername(),postgres.getPassword()).locations("classpath:db/migration").target("9").load().migrate();
            try(var db=DriverManager.getConnection(databaseUrl,postgres.getUsername(),postgres.getPassword())){assertThat(scalar(db,"select title from schedule.project_schedule where id=?",schedule)).isEqualTo("Legacy");assertThat(scalar(db,"select count(*) from schedule.schedule_participant where schedule_id=?",schedule)).isEqualTo(1L);assertThat(scalar(db,"select count(*) from schedule.schedule_acknowledgement where schedule_id=?",schedule)).isEqualTo(1L);assertThat(scalar(db,"select count(*) from schedule.schedule_change where schedule_id=?",schedule)).isEqualTo(1L);assertThat(scalar(db,"select business_revision from calendar_integration.calendar_projection where id=?",projection)).isEqualTo(2L);assertThat(scalar(db,"select count(*) from schedule.schedule_saved_view")).isEqualTo(0L);assertTypedValueConstraints(db,project,schedule);}
        } finally {try(var admin=DriverManager.getConnection(adminUrl,postgres.getUsername(),postgres.getPassword())){admin.createStatement().execute("DROP DATABASE IF EXISTS "+identifier(database));}}
    }
    private static void execute(Connection db,String sql,Object... values)throws SQLException{try(var s=db.prepareStatement(sql)){for(int i=0;i<values.length;i++)s.setObject(i+1,values[i]);s.executeUpdate();}}
    private static Object scalar(Connection db,String sql,Object... values)throws SQLException{try(var s=db.prepareStatement(sql)){for(int i=0;i<values.length;i++)s.setObject(i+1,values[i]);try(var r=s.executeQuery()){return r.next()?r.getObject(1):null;}}}
    private static void assertTypedValueConstraints(Connection db,UUID project,UUID schedule)throws SQLException {var text=UUID.randomUUID();var number=UUID.randomUUID();var checkbox=UUID.randomUUID();var date=UUID.randomUUID();var select=UUID.randomUUID();var option=UUID.randomUUID();execute(db,"insert into schedule.schedule_property(id,project_id,name,property_type,position) values (?,?,'T','TEXT',0),(?,?,'N','NUMBER',1),(?,?,'B','CHECKBOX',2),(?,?,'D','DATE',3),(?,?,'S','SINGLE_SELECT',4)",text,project,number,project,checkbox,project,date,project,select,project);execute(db,"insert into schedule.schedule_property_option(id,property_id,label,color,position) values (?,?,'One','blue',0)",option,select);execute(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,text_value) values (?,?,?,?, 'TEXT','ok')",UUID.randomUUID(),project,schedule,text);execute(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,number_value) values (?,?,?,?, 'NUMBER',1.25)",UUID.randomUUID(),project,schedule,number);execute(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,checkbox_value) values (?,?,?,?, 'CHECKBOX',true)",UUID.randomUUID(),project,schedule,checkbox);execute(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,date_value) values (?,?,?,?, 'DATE',DATE '2099-01-01')",UUID.randomUUID(),project,schedule,date);execute(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,option_id) values (?,?,?,?, 'SINGLE_SELECT',?)",UUID.randomUUID(),project,schedule,select,option);assertThat(scalar(db,"select count(*) from schedule.schedule_property_value where schedule_id=?",schedule)).isEqualTo(5L);assertRejected(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type) values (?,?,?,?, 'TEXT')",UUID.randomUUID(),project,schedule,UUID.randomUUID());assertRejected(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,text_value,number_value) values (?,?,?,?, 'TEXT','x',1)",UUID.randomUUID(),project,schedule,text);assertRejected(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,number_value) values (?,?,?,?, 'TEXT',1)",UUID.randomUUID(),project,schedule,text);assertRejected(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,text_value) values (?,?,?,?, 'TEXT','x')",UUID.randomUUID(),project,schedule,number);assertRejected(db,"insert into schedule.schedule_property_value(id,project_id,schedule_id,property_id,value_type,option_id) values (?,?,?,?, 'SINGLE_SELECT',?)",UUID.randomUUID(),project,schedule,text,option);}
    private static void assertRejected(Connection db,String sql,Object... values){assertThat(org.assertj.core.api.Assertions.catchThrowable(()->execute(db,sql,values))).isInstanceOf(SQLException.class);}
    private static String identifier(String value){return "\""+value.replace("\"","\"\"")+"\"";}
}
