package com.aierp.project.api;
import com.aierp.identity.api.ApplicationPrincipal; import com.aierp.project.*; import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") public class InvitationController {
 private final ProjectInvitationRepository invitations; private final ProjectMemberRepository members;
 public InvitationController(ProjectInvitationRepository i,ProjectMemberRepository m){invitations=i;members=m;}
 @PostMapping("/groups/{groupId}/invitations") @Transactional public InvitationResponse invite(@PathVariable UUID groupId,@RequestBody InviteRequest body,Authentication auth){ var p=principal(auth); var manager=members.findByProjectIdAndUserAccountId(body.projectId(),p.userId()).filter(x->x.role==ProjectRole.MANAGER).orElseThrow(()->new org.springframework.security.access.AccessDeniedException("MANAGER_REQUIRED")); var email=body.email().trim().toLowerCase(Locale.ROOT); if(invitations.existsByProjectIdAndEmailAndStatus(body.projectId(),email,ProjectInvitationEntity.Status.PENDING)) throw new IllegalStateException("INVITATION_CONFLICT"); var x=new ProjectInvitationEntity();x.id=UUID.randomUUID();x.projectId=body.projectId();x.email=email;x.token=UUID.randomUUID().toString();x.status=ProjectInvitationEntity.Status.PENDING;x.expiresAt=Instant.now().plus(Duration.ofDays(7));x.invitedBy=p.userId();invitations.save(x);return out(x); }
 @GetMapping("/invitations/{token}") public InvitationResponse get(@PathVariable String token){return out(find(token));}
 @PostMapping("/invitations/{token}/accept") @Transactional public InvitationResponse accept(@PathVariable String token,Authentication auth){var x=valid(find(token),principal(auth));x.status=ProjectInvitationEntity.Status.ACCEPTED; var m=new ProjectMemberEntity();m.projectId=x.projectId;m.userAccountId=principal(auth).userId();m.role=ProjectRole.MEMBER;members.save(m);return out(x);}
 @PostMapping("/invitations/{token}/reject") @Transactional public InvitationResponse reject(@PathVariable String token,Authentication auth){var x=valid(find(token),principal(auth));x.status=ProjectInvitationEntity.Status.REJECTED;return out(x);}
 private ProjectInvitationEntity valid(ProjectInvitationEntity x,ApplicationPrincipal p){if(!p.emailVerified()||!x.email.equals(p.email().trim().toLowerCase(Locale.ROOT)))throw new org.springframework.security.access.AccessDeniedException("VERIFIED_EMAIL_REQUIRED");if(x.status!=ProjectInvitationEntity.Status.PENDING||x.expiresAt.isBefore(Instant.now()))throw new IllegalStateException("INVITATION_CONFLICT");return x;}
 private ProjectInvitationEntity find(String t){return invitations.findByToken(t).orElseThrow(()->new NoSuchElementException("INVITATION_NOT_FOUND"));} private static ApplicationPrincipal principal(Authentication a){if(a.getPrincipal() instanceof ApplicationPrincipal p)return p;throw new org.springframework.security.access.AccessDeniedException("APPLICATION_PRINCIPAL_REQUIRED");} private static InvitationResponse out(ProjectInvitationEntity x){return new InvitationResponse(x.id,x.projectId,x.email,x.token,x.status,x.expiresAt);} public record InviteRequest(UUID projectId,String email){} public record InvitationResponse(UUID id,UUID projectId,String email,String token,ProjectInvitationEntity.Status status,Instant expiresAt){}
}
