package com.aierp.project.api;

import com.aierp.platform.web.ValidationFailure;
import com.aierp.project.*;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Project-owned API for definition facts and manager-authorized versioned writes. */
@Service
public class ProjectManagementDefinitionAccess {
    private final ProjectManagementDefinitionRepository definitions; private final ProjectAccess access; private final ManagementMutationAccess mutations; private final boolean enabled;
    public ProjectManagementDefinitionAccess(ProjectManagementDefinitionRepository definitions,ProjectAccess access,ManagementMutationAccess mutations,@Value("${app.project-management.enabled:true}") boolean enabled){this.definitions=definitions;this.access=access;this.mutations=mutations;this.enabled=enabled;}
    public boolean enabled(){return enabled;}
    @Transactional(readOnly=true) public DefinitionView read(UUID projectId,UUID actor){var project=access.readableProject(projectId,actor);var row=definitions.findById(projectId).orElse(null);return view(projectId,row,enabled&&project.role()==ProjectRole.MANAGER);}
    @Transactional public DefinitionView update(UUID projectId,DefinitionWrite input,UUID actor){validate(input);access.lockProject(projectId);access.requireManager(projectId,actor);if(!enabled)throw new IllegalStateException("PROJECT_MANAGEMENT_DISABLED");if(input.responsibleManagerId()!=null)access.requireManager(projectId,input.responsibleManagerId());var hash=hash(ManagementRequestCanonicalizer.definition("DEFINITION_UPDATE",projectId,input.purpose(),input.successCriteria(),input.responsibleManagerId(),input.health(),input.healthReason(),input.healthAsOf(),input.rowVersion()));var prior=mutations.lock(projectId,actor,input.requestId());if(prior.isPresent()){if(!hash.equals(prior.get().payloadHash())||!"DEFINITION".equals(prior.get().resourceType())||!projectId.equals(prior.get().resourceId()))throw new IllegalStateException("REQUEST_PAYLOAD_MISMATCH");return read(projectId,actor);}var row=definitions.lockByProjectId(projectId).orElseGet(()->{var r=new ProjectManagementDefinitionEntity();r.projectId=projectId;return r;});if(input.rowVersion()==null||input.rowVersion()<0)throw new ValidationFailure("rowVersion","rowVersion is required and must be non-negative");if(row.rowVersion!=input.rowVersion())throw new org.springframework.orm.ObjectOptimisticLockingFailureException("STALE_ROW_VERSION",null);var before=values(row);row.purpose=clean(input.purpose());row.successCriteria=clean(input.successCriteria());row.responsibleManagerId=input.responsibleManagerId();row.health=input.health()==null?null:ProjectManagementDefinitionEntity.Health.valueOf(input.health());row.healthReason=clean(input.healthReason());row.healthAsOf=input.healthAsOf();row.rowVersion++;row.updatedAt=Instant.now();definitions.saveAndFlush(row);mutations.audit(projectId,actor,"DEFINITION",projectId,row.rowVersion,"DEFINITION_UPDATE",before,values(row));mutations.saveReceipt(projectId,actor,input.requestId(),hash,"DEFINITION",projectId,row.rowVersion,"DEFINITION_UPDATE");return view(projectId,row,true);}
    private static void validate(DefinitionWrite i){if(i==null)throw new ValidationFailure("request","Request body is required");if(i.requestId()==null)throw new ValidationFailure("requestId","requestId is required");length(i.purpose(),2000,"purpose");length(i.successCriteria(),2000,"successCriteria");length(i.healthReason(),500,"healthReason");if(i.health()!=null&&(clean(i.healthReason())==null||i.healthAsOf()==null))throw new ValidationFailure("health","healthReason and healthAsOf are required when health is set");}
    private static void length(String v,int n,String f){if(v!=null&&v.trim().length()>n)throw new ValidationFailure(f,f+" is too long");}private static String clean(String v){return ManagementRequestCanonicalizer.normalize(v);}
    private static Map<String,Object> values(ProjectManagementDefinitionEntity r){var m=new LinkedHashMap<String,Object>();m.put("purpose",r.purpose);m.put("successCriteria",r.successCriteria);m.put("responsibleManagerId",r.responsibleManagerId==null?null:r.responsibleManagerId.toString());m.put("health",r.health==null?null:r.health.name());m.put("healthReason",r.healthReason);m.put("healthAsOf",r.healthAsOf==null?null:r.healthAsOf.toString());m.put("rowVersion",r.rowVersion);return m;}
    private static DefinitionView view(UUID id,ProjectManagementDefinitionEntity r,boolean edit){return r==null?new DefinitionView(id,null,null,null,null,null,null,0,edit):new DefinitionView(id,r.purpose,r.successCriteria,r.responsibleManagerId,r.health==null?null:r.health.name(),r.healthReason,r.healthAsOf,r.rowVersion,edit);}
    private static String hash(String s){try{return HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    public record DefinitionWrite(String purpose,String successCriteria,UUID responsibleManagerId,String health,String healthReason,LocalDate healthAsOf,Long rowVersion,UUID requestId){}
    public record DefinitionView(UUID projectId,String purpose,String successCriteria,UUID responsibleManagerId,String health,String healthReason,LocalDate healthAsOf,long rowVersion,boolean canEdit){}
}
